-- 0026 — AI result store (spec §27–§28, Steps 15–16)
--
-- docs/ai_architecture.md: AI results are never committed to canonical WMS
-- data directly — they land here, with a confidence and a PENDING_REVIEW
-- state, until a human confirms or rejects them. Nothing before this
-- migration persisted an AI call at all: the OCR edge function called
-- Gemini and handed the result straight back to the client with no record
-- of what was asked, what came back, or whether anyone reviewed it.
--
-- product_id/attachment_id are plain nullable bigint columns, not FKs —
-- neither a `products` nor an `attachments` table exists yet (future
-- work), and the result store is deliberately shaped to fit them once they
-- do rather than being redesigned later.
create table public.ai_analysis (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id),
  warehouse_id bigint references public.warehouses(id),
  delivery_plan_id bigint references public.delivery_plans(id) on delete set null,
  inspection_id bigint references public.inspections(id) on delete set null,
  product_id bigint,
  attachment_id bigint,
  provider text not null,
  model text,
  task_type text not null,
  input_uri text,
  input_hash text,
  output_json jsonb not null default '{}'::jsonb,
  confidence numeric,
  status text not null default 'PENDING_REVIEW'
    check (status in ('PENDING_REVIEW', 'CONFIRMED', 'REJECTED')),
  reviewed_by uuid references public.app_users(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

-- Idempotent re-use: the same delivery-note photo re-submitted (a retry, a
-- second crop attempt) skips a second Gemini call and reuses the prior
-- result instead of paying for it twice.
create index ai_analysis_hash_idx on public.ai_analysis (task_type, input_hash)
  where input_hash is not null;
create index ai_analysis_company_idx on public.ai_analysis (company_id, created_at desc);

alter table public.ai_analysis enable row level security;

create policy "ai_analysis: reviewers can read"
  on public.ai_analysis for select
  to authenticated
  using (public.has_permission('ai.review'));

-- No insert/update/delete policy: every write goes through the two
-- service_role-only functions below (called from the OCR edge function,
-- which holds the service role key server-side) or the two
-- ai.review-gated review functions — never directly from a client.

create or replace function public.find_ai_analysis_reuse(
  p_task_type text,
  p_input_hash text
) returns jsonb
language sql stable security definer set search_path = '' as $$
  select jsonb_build_object(
    'id', id, 'output_json', output_json, 'confidence', confidence, 'provider', provider)
    from public.ai_analysis
   where task_type = p_task_type and input_hash = p_input_hash and status <> 'REJECTED'
   order by created_at desc
   limit 1;
$$;

create or replace function public.record_ai_analysis(
  p_company_id bigint,
  p_warehouse_id bigint,
  p_delivery_plan_id bigint,
  p_inspection_id bigint,
  p_provider text,
  p_model text,
  p_task_type text,
  p_input_hash text,
  p_output_json jsonb,
  p_confidence numeric
) returns bigint
language plpgsql security definer set search_path = '' as $$
declare
  v_id bigint;
begin
  insert into public.ai_analysis (
    company_id, warehouse_id, delivery_plan_id, inspection_id,
    provider, model, task_type, input_hash, output_json, confidence)
  values (
    p_company_id, p_warehouse_id, p_delivery_plan_id, p_inspection_id,
    p_provider, p_model, p_task_type, p_input_hash, p_output_json, p_confidence)
  returning id into v_id;

  perform public.log_audit('ai.analysis_completed', 'ai_analysis', v_id::text, p_warehouse_id,
    jsonb_build_object('task_type', p_task_type, 'provider', p_provider));

  return v_id;
end;
$$;

-- An ai.review holder confirms or rejects a PENDING_REVIEW result. No
-- screen calls these yet (the review UI is future work — spec §31's
-- candidate-ranking flow is a separate, larger piece); they exist now so
-- the result store is usable end-to-end (e.g. via the dashboard) rather
-- than write-only until that UI lands.
create or replace function public.confirm_ai_analysis(p_id bigint)
returns boolean
language plpgsql security definer set search_path = '' as $$
declare
  v_warehouse_id bigint;
  v_task_type text;
begin
  if not public.has_permission('ai.review') then
    raise exception 'not permitted: ai.review required';
  end if;

  update public.ai_analysis
     set status = 'CONFIRMED', reviewed_by = auth.uid(), reviewed_at = now()
   where id = p_id and status = 'PENDING_REVIEW'
  returning warehouse_id, task_type into v_warehouse_id, v_task_type;

  if not found then
    raise exception 'ai_analysis % not found or not pending review', p_id;
  end if;

  perform public.log_audit('ai.confirmed', 'ai_analysis', p_id::text, v_warehouse_id,
    jsonb_build_object('task_type', v_task_type));
  return true;
end;
$$;

create or replace function public.reject_ai_analysis(p_id bigint, p_reason text default null)
returns boolean
language plpgsql security definer set search_path = '' as $$
declare
  v_warehouse_id bigint;
  v_task_type text;
begin
  if not public.has_permission('ai.review') then
    raise exception 'not permitted: ai.review required';
  end if;

  update public.ai_analysis
     set status = 'REJECTED', reviewed_by = auth.uid(), reviewed_at = now()
   where id = p_id and status = 'PENDING_REVIEW'
  returning warehouse_id, task_type into v_warehouse_id, v_task_type;

  if not found then
    raise exception 'ai_analysis % not found or not pending review', p_id;
  end if;

  perform public.log_audit('ai.rejected', 'ai_analysis', p_id::text, v_warehouse_id,
    jsonb_build_object('task_type', v_task_type, 'reason', p_reason));
  return true;
end;
$$;

revoke all on function public.find_ai_analysis_reuse(text, text) from public, anon, authenticated;
revoke all on function public.record_ai_analysis(
  bigint, bigint, bigint, bigint, text, text, text, text, jsonb, numeric)
  from public, anon, authenticated;
revoke all on function public.confirm_ai_analysis(bigint) from public, anon;
revoke all on function public.reject_ai_analysis(bigint, text) from public, anon;

-- Reuse-lookup and recording are internal: only the OCR edge function
-- (holding the service role key) ever calls them, never a client directly.
grant execute on function public.find_ai_analysis_reuse(text, text) to service_role;
grant execute on function public.record_ai_analysis(
  bigint, bigint, bigint, bigint, text, text, text, text, jsonb, numeric)
  to service_role;
grant execute on function public.confirm_ai_analysis(bigint) to authenticated, service_role;
grant execute on function public.reject_ai_analysis(bigint, text) to authenticated, service_role;
