-- 0028 — Connector/Adapter skeleton (spec §34, Step 17)
--
-- architecture_target.md §4: "external systems (Shopify, carriers, freee,
-- InventorOS…) behind adapters; never embedded in core logic." This is the
-- registry + run-history shape that lets a future adapter exist as
-- configuration and an audit trail, rather than a one-off HTTP call buried
-- inside a screen.
--
-- Deliberately scoped to the skeleton only (asked for explicitly): no
-- adapter actually talks to an external system yet. `inventoros` is seeded
-- as a registered-but-disabled row, matching architecture_target.md's own
-- framing ("InventorOS... can later become one Connector among others, not
-- the core") — a placeholder for where it belongs, not a working sync.
create table public.connectors (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  kind text not null,
  -- Connection details only (base URLs, flags) — never a secret. A real
  -- adapter reads its credential from an edge function's own environment,
  -- the same way GEMINI_API_KEY never appears in a table row.
  config jsonb not null default '{}'::jsonb,
  enabled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.connector_runs (
  id bigint generated by default as identity primary key,
  connector_id bigint not null references public.connectors(id) on delete cascade,
  direction text not null check (direction in ('import', 'export')),
  status text not null default 'PENDING'
    check (status in ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  summary jsonb not null default '{}'::jsonb,
  error text,
  triggered_by uuid references public.app_users(id)
);

create index connector_runs_connector_idx
  on public.connector_runs (connector_id, started_at desc);

alter table public.connectors enable row level security;
alter table public.connector_runs enable row level security;

create policy "connectors: managers can read"
  on public.connectors for select
  to authenticated
  using (public.has_permission('connector.manage'));

create policy "connector_runs: managers can read"
  on public.connector_runs for select
  to authenticated
  using (public.has_permission('connector.manage'));

-- New permission (22nd) — company_admin/system_admin only, same restriction
-- as user.manage (warehouse_manager does not hold it: connectors are a
-- company-wide integration concern, not a per-warehouse one).
insert into public.permissions (code, description)
values ('connector.manage', 'Register and configure external system connectors');

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
  from public.roles r, public.permissions p
 where r.code in ('system_admin', 'company_admin')
   and p.code = 'connector.manage';

create or replace function public.list_connectors()
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.has_permission('connector.manage') then
    raise exception 'not permitted: connector.manage required';
  end if;

  return coalesce(
    (select jsonb_agg(jsonb_build_object(
        'id', c.id, 'code', c.code, 'name', c.name, 'kind', c.kind,
        'enabled', c.enabled, 'config', c.config,
        'last_run', (
          select jsonb_build_object(
            'status', cr.status, 'direction', cr.direction,
            'started_at', cr.started_at, 'finished_at', cr.finished_at)
            from public.connector_runs cr
           where cr.connector_id = c.id
           order by cr.started_at desc
           limit 1)
      ) order by c.name)
      from public.connectors c),
    '[]'::jsonb);
end;
$$;

create or replace function public.set_connector_enabled(p_code text, p_enabled boolean)
returns boolean
language plpgsql security definer set search_path = '' as $$
declare
  v_id bigint;
begin
  if not public.has_permission('connector.manage') then
    raise exception 'not permitted: connector.manage required';
  end if;

  update public.connectors
     set enabled = p_enabled, updated_at = now()
   where code = p_code
  returning id into v_id;

  if not found then
    raise exception 'connector % not found', p_code;
  end if;

  perform public.log_audit(
    case when p_enabled then 'connector.enabled' else 'connector.disabled' end,
    'connector', v_id::text, null, jsonb_build_object('code', p_code));

  return true;
end;
$$;

revoke all on function public.list_connectors() from public, anon;
revoke all on function public.set_connector_enabled(text, boolean) from public, anon;
grant execute on function public.list_connectors() to authenticated, service_role;
grant execute on function public.set_connector_enabled(text, boolean) to authenticated, service_role;

-- Seed: InventorOS's position in this architecture, per architecture_target.md
-- — registered, disabled, no adapter behind it yet.
insert into public.connectors (code, name, kind, config, enabled)
values (
  'inventoros', 'InventorOS', 'wms',
  jsonb_build_object('note', 'Legacy REST backend; not currently reachable. No adapter implemented yet.'),
  false
);
