-- 0031 — Image/attachment storage (spec §32, "画像の収納")
--
-- Nothing in this app has ever stored a file: no Storage bucket existed, and
-- the OCR flow only ever sends image bytes transiently to an edge function.
-- This is the first real attachment capability — a polymorphic table
-- (domain_model.md §"attachments (→ any)") pointed at a private Storage
-- bucket, wired to inspections first (photo evidence for a failed/damaged
-- item), shaped to attach to other entities later without a redesign.
insert into storage.buckets (id, name, public)
values ('inspection-attachments', 'inspection-attachments', false)
on conflict (id) do nothing;

create table public.attachments (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id),
  entity_type text not null,
  entity_id text not null,
  storage_path text not null,
  content_type text,
  uploaded_by uuid references public.app_users(id),
  created_at timestamptz not null default now()
);

create index attachments_entity_idx on public.attachments (entity_type, entity_id, created_at desc);

alter table public.attachments enable row level security;

-- Read: anyone who can view inspections (today's only attachment consumer).
create policy "attachments: inspection viewers can read"
  on public.attachments for select
  to authenticated
  using (public.has_permission('inspection.view'));

-- No insert/update/delete policy — every write goes through
-- record_attachment below, never a direct client insert.

-- The actual file bytes go straight to Storage from the client (its own
-- upload call, not this function) — RLS on storage.objects below gates
-- that. This just records the metadata row once the upload succeeds.
create or replace function public.record_attachment(
  p_entity_type text,
  p_entity_id text,
  p_storage_path text,
  p_content_type text
) returns bigint
language plpgsql security definer set search_path = '' as $$
declare
  v_id bigint;
  v_company_id bigint;
begin
  if not public.has_permission('inspection.confirm') then
    raise exception 'not permitted: inspection.confirm required';
  end if;

  select id into v_company_id from public.companies order by id limit 1;

  insert into public.attachments (
    company_id, entity_type, entity_id, storage_path, content_type, uploaded_by)
  values (v_company_id, p_entity_type, p_entity_id, p_storage_path, p_content_type, auth.uid())
  returning id into v_id;

  perform public.log_audit('attachment.uploaded', p_entity_type, p_entity_id, null,
    jsonb_build_object('storage_path', p_storage_path));

  return v_id;
end;
$$;

revoke all on function public.record_attachment(text, text, text, text) from public, anon;
grant execute on function public.record_attachment(text, text, text, text) to authenticated, service_role;

-- Storage RLS: the same two permissions gate the bucket itself, so a client
-- can't upload/read bytes for a capability it doesn't hold even though the
-- upload call itself bypasses record_attachment.
create policy "inspection-attachments: uploaders can write"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'inspection-attachments'
    and public.has_permission('inspection.confirm')
  );

create policy "inspection-attachments: viewers can read"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'inspection-attachments'
    and public.has_permission('inspection.view')
  );
