-- 0032 — Product master (spec §19, domain_model.md §2)
--
-- No `products` table has ever existed in this Supabase project — every JAN
-- is a bare text column repeated across `stock_levels`, `stock_movements`,
-- `bin_stock` and `inspection_items`, each carrying its own denormalized
-- `product_name`. This is additive, deliberately narrow master data (name,
-- category, price — the JAN itself is the barcode already used everywhere
-- else) keyed by `jan_code`, not a new `product_id` foreign key threading
-- through the existing stock tables — that would be a much larger, riskier
-- migration for a want that's really just "look up and price a JAN".
create table public.products (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id),
  jan_code text not null,
  name text not null,
  category text,
  price numeric(12, 2),
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, jan_code)
);

create index products_search_idx on public.products (company_id, status, name);

alter table public.products enable row level security;

create policy "products: viewers can read"
  on public.products for select
  to authenticated
  using (public.has_permission('product.view'));

-- No insert/update/delete policy — every write goes through the RPCs below,
-- same discipline as attachments/connectors.

insert into public.permissions (code, description)
values
  ('product.view', 'View the product master'),
  ('product.manage', 'Create, edit and (de)activate products');

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
  from public.roles r, public.permissions p
 where p.code = 'product.view'
   and r.code in ('system_admin', 'company_admin', 'warehouse_manager',
                   'inventory_controller', 'receiving', 'putaway_operator',
                   'picker', 'viewer');

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
  from public.roles r, public.permissions p
 where p.code = 'product.manage'
   and r.code in ('system_admin', 'company_admin', 'warehouse_manager',
                   'inventory_controller');

create or replace function public.list_products(
  p_search text default null,
  p_status text default 'active'
) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.has_permission('product.view') then
    raise exception 'not permitted: product.view required';
  end if;

  return coalesce(
    (select jsonb_agg(jsonb_build_object(
        'id', p.id, 'jan_code', p.jan_code, 'name', p.name,
        'category', p.category, 'price', p.price, 'status', p.status,
        'created_at', p.created_at, 'updated_at', p.updated_at
      ) order by p.name)
      from public.products p
     where (p_status is null or p.status = p_status)
       and (p_search is null or p_search = '' or
            p.name ilike '%' || p_search || '%' or
            p.jan_code ilike '%' || p_search || '%')),
    '[]'::jsonb);
end;
$$;

create or replace function public.create_product(
  p_jan_code text,
  p_name text,
  p_category text default null,
  p_price numeric default null
) returns bigint
language plpgsql security definer set search_path = '' as $$
declare
  v_id bigint;
  v_company_id bigint;
begin
  if not public.has_permission('product.manage') then
    raise exception 'not permitted: product.manage required';
  end if;
  if p_jan_code is null or p_jan_code = '' then
    raise exception 'jan_code is required';
  end if;
  if p_name is null or p_name = '' then
    raise exception 'name is required';
  end if;

  select id into v_company_id from public.companies order by id limit 1;

  if exists (
    select 1 from public.products
     where company_id = v_company_id and jan_code = p_jan_code
  ) then
    raise exception 'a product with jan_code % already exists', p_jan_code;
  end if;

  insert into public.products (company_id, jan_code, name, category, price)
  values (v_company_id, p_jan_code, p_name, p_category, p_price)
  returning id into v_id;

  perform public.log_audit('product.created', 'product', v_id::text, null,
    jsonb_build_object('jan_code', p_jan_code, 'name', p_name));

  return v_id;
end;
$$;

create or replace function public.update_product(
  p_id bigint,
  p_name text,
  p_category text default null,
  p_price numeric default null
) returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not public.has_permission('product.manage') then
    raise exception 'not permitted: product.manage required';
  end if;
  if p_name is null or p_name = '' then
    raise exception 'name is required';
  end if;

  update public.products
     set name = p_name, category = p_category, price = p_price, updated_at = now()
   where id = p_id;

  if not found then
    raise exception 'product % not found', p_id;
  end if;

  perform public.log_audit('product.updated', 'product', p_id::text, null,
    jsonb_build_object('name', p_name));

  return true;
end;
$$;

create or replace function public.set_product_status(
  p_id bigint,
  p_status text
) returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not public.has_permission('product.manage') then
    raise exception 'not permitted: product.manage required';
  end if;
  if p_status not in ('active', 'inactive') then
    raise exception 'invalid status %', p_status;
  end if;

  update public.products set status = p_status, updated_at = now() where id = p_id;

  if not found then
    raise exception 'product % not found', p_id;
  end if;

  perform public.log_audit(
    case when p_status = 'active' then 'product.activated' else 'product.deactivated' end,
    'product', p_id::text, null, '{}'::jsonb);

  return true;
end;
$$;

revoke all on function public.list_products(text, text) from public, anon;
revoke all on function public.create_product(text, text, text, numeric) from public, anon;
revoke all on function public.update_product(bigint, text, text, numeric) from public, anon;
revoke all on function public.set_product_status(bigint, text) from public, anon;
grant execute on function public.list_products(text, text) to authenticated, service_role;
grant execute on function public.create_product(text, text, text, numeric) to authenticated, service_role;
grant execute on function public.update_product(bigint, text, text, numeric) to authenticated, service_role;
grant execute on function public.set_product_status(bigint, text) to authenticated, service_role;
