-- 0033 — Purchase orders (spec §46 checklist item 6)
--
-- "Purchase orders" were removed with InventorOS and never rebuilt on
-- Supabase. `delivery_plans` (0001+) is a related but distinct concept — an
-- *expected shipment*, usually created by importing a delivery note
-- (already shipped, quantities mostly known) and used for QC reconciliation
-- against what physically arrives. A purchase order is the earlier-stage
-- document: what was *ordered* from a supplier, before it ships. This is a
-- deliberately self-contained order-lifecycle module — draft → submit →
-- approve/reject → (cancel) → complete — that does not move stock and is
-- not wired into delivery_plans/reconciliation; "complete" here is a
-- bookkeeping close, not a receiving event. Wiring a PO into the existing
-- receiving flow (e.g. pre-filling a delivery plan from an approved PO) is
-- a natural follow-up, not required for this to be useful on its own.
--
-- Follows the state-machine and self-approval-refused shape transfer_orders
-- (0019) established, but grants execute directly to `authenticated` with
-- `has_permission()` checks inside — the pattern every RPC since 0024 (real
-- sign-in) uses, not 0019's now-superseded service_role-only grants.
create table public.purchase_orders (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id),
  po_number text,
  supplier_id bigint references public.delivery_suppliers(id),
  supplier_name text not null,
  warehouse_id bigint not null references public.warehouses(id),
  status text not null default 'DRAFT' check (status in (
    'DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED')),
  order_date date not null default current_date,
  expected_date date,
  note text,
  requested_by uuid references public.app_users(id),
  approved_by uuid references public.app_users(id),
  approved_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index purchase_orders_number_idx
  on public.purchase_orders (po_number) where po_number is not null;
create index purchase_orders_warehouse_idx
  on public.purchase_orders (warehouse_id, status);

create table public.purchase_order_lines (
  id bigint generated by default as identity primary key,
  purchase_order_id bigint not null references public.purchase_orders(id) on delete cascade,
  jan_code text not null,
  product_name text not null default '',
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 2),
  note text
);

create index purchase_order_lines_order_idx
  on public.purchase_order_lines (purchase_order_id);

alter table public.purchase_orders enable row level security;
alter table public.purchase_order_lines enable row level security;

create policy "purchase_orders: viewers can read"
  on public.purchase_orders for select
  to authenticated
  using (public.has_permission('purchase_order.view'));

create policy "purchase_order_lines: viewers can read"
  on public.purchase_order_lines for select
  to authenticated
  using (public.has_permission('purchase_order.view'));

-- No insert/update/delete policy on either table — every write goes through
-- the RPCs below, same discipline as attachments/connectors/products.

insert into public.permissions (code, description)
values
  ('purchase_order.view', 'View purchase orders'),
  ('purchase_order.manage', 'Create, submit, cancel and complete purchase orders'),
  ('purchase_order.approve', 'Approve or reject a submitted purchase order');

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
  from public.roles r, public.permissions p
 where p.code = 'purchase_order.view'
   and r.code in ('system_admin', 'company_admin', 'warehouse_manager',
                   'inventory_controller', 'receiving', 'viewer');

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
  from public.roles r, public.permissions p
 where p.code = 'purchase_order.manage'
   and r.code in ('system_admin', 'company_admin', 'warehouse_manager',
                   'inventory_controller');

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
  from public.roles r, public.permissions p
 where p.code = 'purchase_order.approve'
   and r.code in ('system_admin', 'company_admin', 'warehouse_manager');

-- --------------------------------------------------------------------- RPCs

create or replace function public.create_purchase_order(
  p_supplier_name text,
  p_warehouse_id bigint,
  p_lines jsonb,
  p_supplier_id bigint default null,
  p_expected_date date default null,
  p_note text default null
) returns bigint
language plpgsql security definer set search_path = '' as $$
declare
  v_id bigint;
  v_company_id bigint;
  v_line jsonb;
  v_qty integer;
begin
  if not public.has_permission('purchase_order.manage') then
    raise exception 'not permitted: purchase_order.manage required';
  end if;
  if p_supplier_name is null or p_supplier_name = '' then
    raise exception 'supplier_name is required';
  end if;
  if not exists (select 1 from public.warehouses where id = p_warehouse_id) then
    raise exception 'warehouse % not found', p_warehouse_id;
  end if;
  if jsonb_typeof(p_lines) is distinct from 'array' or jsonb_array_length(p_lines) = 0 then
    raise exception 'at least one line is required';
  end if;

  select id into v_company_id from public.companies order by id limit 1;

  insert into public.purchase_orders
    (company_id, supplier_id, supplier_name, warehouse_id, expected_date, note, requested_by)
  values
    (v_company_id, p_supplier_id, p_supplier_name, p_warehouse_id, p_expected_date,
     nullif(p_note, ''), auth.uid())
  returning id into v_id;

  update public.purchase_orders
     set po_number = 'PO-' || lpad(v_id::text, 6, '0')
   where id = v_id;

  for v_line in select * from jsonb_array_elements(p_lines) loop
    v_qty := coalesce((v_line->>'quantity')::int, 0);
    if v_qty > 0 and coalesce(v_line->>'jan_code', '') <> '' then
      insert into public.purchase_order_lines
        (purchase_order_id, jan_code, product_name, quantity, unit_price)
      values (
        v_id, v_line->>'jan_code', coalesce(v_line->>'product_name', ''), v_qty,
        nullif(v_line->>'unit_price', '')::numeric);
    end if;
  end loop;

  if not exists (select 1 from public.purchase_order_lines where purchase_order_id = v_id) then
    raise exception 'at least one line with a positive quantity is required';
  end if;

  perform public.log_audit('purchase_order.created', 'purchase_order', v_id::text,
    p_warehouse_id, jsonb_build_object('supplier_name', p_supplier_name));

  return v_id;
end;
$$;

create or replace function public.submit_purchase_order(p_id bigint)
returns boolean
language plpgsql security definer set search_path = '' as $$
declare
  v_status text;
  v_warehouse_id bigint;
begin
  if not public.has_permission('purchase_order.manage') then
    raise exception 'not permitted: purchase_order.manage required';
  end if;

  select status, warehouse_id into v_status, v_warehouse_id
    from public.purchase_orders where id = p_id;
  if v_status is null then raise exception 'purchase order % not found', p_id; end if;
  if v_status <> 'DRAFT' then
    raise exception 'purchase order % is % and cannot be submitted', p_id, v_status;
  end if;

  update public.purchase_orders set status = 'SUBMITTED' where id = p_id;
  perform public.log_audit(
    'purchase_order.submitted', 'purchase_order', p_id::text, v_warehouse_id, '{}'::jsonb);
  return true;
end;
$$;

-- Self-approval refused once both requester and approver are known — same
-- guard as transfer_orders (0019), inactive while auth.uid() is null.
create or replace function public.approve_purchase_order(p_id bigint)
returns boolean
language plpgsql security definer set search_path = '' as $$
declare
  v_status text;
  v_warehouse_id bigint;
  v_requested_by uuid;
  v_approver uuid := auth.uid();
begin
  if not public.has_permission('purchase_order.approve') then
    raise exception 'not permitted: purchase_order.approve required';
  end if;

  select status, warehouse_id, requested_by
    into v_status, v_warehouse_id, v_requested_by
    from public.purchase_orders where id = p_id;
  if v_status is null then raise exception 'purchase order % not found', p_id; end if;
  if v_status <> 'SUBMITTED' then
    raise exception 'purchase order % is % and cannot be approved', p_id, v_status;
  end if;
  if v_requested_by is not null and v_approver is not null and v_requested_by = v_approver then
    raise exception 'a purchase order cannot be approved by the person who requested it';
  end if;

  update public.purchase_orders
     set status = 'APPROVED', approved_by = v_approver, approved_at = now()
   where id = p_id;
  perform public.log_audit(
    'purchase_order.approved', 'purchase_order', p_id::text, v_warehouse_id, '{}'::jsonb);
  return true;
end;
$$;

create or replace function public.reject_purchase_order(p_id bigint, p_reason text default null)
returns boolean
language plpgsql security definer set search_path = '' as $$
declare
  v_status text;
  v_warehouse_id bigint;
begin
  if not public.has_permission('purchase_order.approve') then
    raise exception 'not permitted: purchase_order.approve required';
  end if;

  select status, warehouse_id into v_status, v_warehouse_id
    from public.purchase_orders where id = p_id;
  if v_status is null then raise exception 'purchase order % not found', p_id; end if;
  if v_status <> 'SUBMITTED' then
    raise exception 'purchase order % is % and cannot be rejected', p_id, v_status;
  end if;

  update public.purchase_orders set status = 'REJECTED' where id = p_id;
  perform public.log_audit('purchase_order.rejected', 'purchase_order', p_id::text,
    v_warehouse_id, jsonb_build_object('reason', p_reason));
  return true;
end;
$$;

-- DRAFT, SUBMITTED and APPROVED can all be cancelled — nothing has moved
-- yet in any of those states (a PO never moves stock on its own).
create or replace function public.cancel_purchase_order(p_id bigint)
returns boolean
language plpgsql security definer set search_path = '' as $$
declare
  v_status text;
  v_warehouse_id bigint;
begin
  if not public.has_permission('purchase_order.manage') then
    raise exception 'not permitted: purchase_order.manage required';
  end if;

  select status, warehouse_id into v_status, v_warehouse_id
    from public.purchase_orders where id = p_id;
  if v_status is null then raise exception 'purchase order % not found', p_id; end if;
  if v_status not in ('DRAFT', 'SUBMITTED', 'APPROVED') then
    raise exception 'purchase order % is % and can no longer be cancelled', p_id, v_status;
  end if;

  update public.purchase_orders set status = 'CANCELLED' where id = p_id;
  perform public.log_audit('purchase_order.cancelled', 'purchase_order', p_id::text,
    v_warehouse_id, jsonb_build_object('was', v_status));
  return true;
end;
$$;

-- Bookkeeping close only — no stock movement. Actual receipt still goes
-- through the existing delivery-plan/reconciliation flow, unchanged.
create or replace function public.complete_purchase_order(p_id bigint)
returns boolean
language plpgsql security definer set search_path = '' as $$
declare
  v_status text;
  v_warehouse_id bigint;
begin
  if not public.has_permission('purchase_order.manage') then
    raise exception 'not permitted: purchase_order.manage required';
  end if;

  select status, warehouse_id into v_status, v_warehouse_id
    from public.purchase_orders where id = p_id;
  if v_status is null then raise exception 'purchase order % not found', p_id; end if;
  if v_status <> 'APPROVED' then
    raise exception 'purchase order % is % and cannot be completed', p_id, v_status;
  end if;

  update public.purchase_orders set status = 'COMPLETED' where id = p_id;
  perform public.log_audit(
    'purchase_order.completed', 'purchase_order', p_id::text, v_warehouse_id, '{}'::jsonb);
  return true;
end;
$$;

-- ------------------------------------------------------------------- reading

create or replace function public.purchase_order_detail(p_id bigint)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.has_permission('purchase_order.view') then
    raise exception 'not permitted: purchase_order.view required';
  end if;

  return (
    select jsonb_build_object(
      'id', o.id,
      'po_number', o.po_number,
      'supplier_id', o.supplier_id,
      'supplier_name', o.supplier_name,
      'warehouse_id', o.warehouse_id,
      'warehouse_name', w.name,
      'status', o.status,
      'order_date', o.order_date,
      'expected_date', o.expected_date,
      'note', o.note,
      'approved_at', o.approved_at,
      'created_at', o.created_at,
      'lines', coalesce((
        select jsonb_agg(jsonb_build_object(
                 'id', l.id, 'jan_code', l.jan_code, 'product_name', l.product_name,
                 'quantity', l.quantity, 'unit_price', l.unit_price) order by l.id)
          from public.purchase_order_lines l
         where l.purchase_order_id = o.id), '[]'::jsonb))
    from public.purchase_orders o
    join public.warehouses w on w.id = o.warehouse_id
   where o.id = p_id);
end;
$$;

create or replace function public.purchase_order_index(
  p_warehouse_id bigint default null,
  p_status text default null,
  p_limit integer default 50
) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.has_permission('purchase_order.view') then
    raise exception 'not permitted: purchase_order.view required';
  end if;

  return coalesce((
    select jsonb_agg(row_to_json(x)::jsonb order by x.id desc)
    from (
      select o.id, o.po_number, o.supplier_name, o.warehouse_id, w.name as warehouse_name,
             o.status, o.order_date, o.expected_date, o.created_at,
             (select count(*) from public.purchase_order_lines l
               where l.purchase_order_id = o.id) as line_count,
             (select coalesce(sum(l.quantity * coalesce(l.unit_price, 0)), 0)
                from public.purchase_order_lines l
               where l.purchase_order_id = o.id) as total_amount
        from public.purchase_orders o
        join public.warehouses w on w.id = o.warehouse_id
       where (p_warehouse_id is null or o.warehouse_id = p_warehouse_id)
         and (p_status is null or o.status = p_status)
       order by o.id desc
       limit greatest(1, least(coalesce(p_limit, 50), 200))
    ) x), '[]'::jsonb);
end;
$$;

-- -------------------------------------------------------------------- grants

revoke all on function public.create_purchase_order(text, bigint, jsonb, bigint, date, text) from public, anon;
revoke all on function public.submit_purchase_order(bigint) from public, anon;
revoke all on function public.approve_purchase_order(bigint) from public, anon;
revoke all on function public.reject_purchase_order(bigint, text) from public, anon;
revoke all on function public.cancel_purchase_order(bigint) from public, anon;
revoke all on function public.complete_purchase_order(bigint) from public, anon;
revoke all on function public.purchase_order_detail(bigint) from public, anon;
revoke all on function public.purchase_order_index(bigint, text, integer) from public, anon;

grant execute on function public.create_purchase_order(text, bigint, jsonb, bigint, date, text) to authenticated, service_role;
grant execute on function public.submit_purchase_order(bigint) to authenticated, service_role;
grant execute on function public.approve_purchase_order(bigint) to authenticated, service_role;
grant execute on function public.reject_purchase_order(bigint, text) to authenticated, service_role;
grant execute on function public.cancel_purchase_order(bigint) to authenticated, service_role;
grant execute on function public.complete_purchase_order(bigint) to authenticated, service_role;
grant execute on function public.purchase_order_detail(bigint) to authenticated, service_role;
grant execute on function public.purchase_order_index(bigint, text, integer) to authenticated, service_role;
