-- 0034 — Sales orders (spec §46 checklist item 7)
--
-- The outbound counterpart to purchase orders (0033): "sales orders" were
-- removed with InventorOS and never rebuilt. `shipment_plans` is a related
-- but distinct concept — an already-committed shipment (feeds picking →
-- packing → shipping) — while a sales order is the earlier-stage document:
-- what a customer ordered, before fulfillment starts. Same self-contained
-- shape as 0033: draft → submit → approve/reject → cancel/complete, never
-- moves stock, not wired into shipment_plans/picking; "complete" here is a
-- bookkeeping close, not a shipping event. Wiring an approved sales order
-- into shipment_plans (e.g. pre-filling one for picking) is a natural
-- follow-up, not required for this to be useful on its own.
--
-- `customer_id` reuses `delivery_suppliers` rather than a new table:
-- `shipment_plans.party_id` already references it as a generic trading-
-- partner master for the outbound side, so this follows that precedent
-- instead of introducing a second, redundant reference table.
create table public.sales_orders (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id),
  so_number text,
  customer_id bigint references public.delivery_suppliers(id),
  customer_name text not null,
  warehouse_id bigint not null references public.warehouses(id),
  status text not null default 'DRAFT' check (status in (
    'DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED')),
  order_date date not null default current_date,
  requested_ship_date date,
  note text,
  requested_by uuid references public.app_users(id),
  approved_by uuid references public.app_users(id),
  approved_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index sales_orders_number_idx
  on public.sales_orders (so_number) where so_number is not null;
create index sales_orders_warehouse_idx
  on public.sales_orders (warehouse_id, status);

create table public.sales_order_lines (
  id bigint generated by default as identity primary key,
  sales_order_id bigint not null references public.sales_orders(id) on delete cascade,
  jan_code text not null,
  product_name text not null default '',
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 2),
  note text
);

create index sales_order_lines_order_idx
  on public.sales_order_lines (sales_order_id);

alter table public.sales_orders enable row level security;
alter table public.sales_order_lines enable row level security;

create policy "sales_orders: viewers can read"
  on public.sales_orders for select
  to authenticated
  using (public.has_permission('sales_order.view'));

create policy "sales_order_lines: viewers can read"
  on public.sales_order_lines for select
  to authenticated
  using (public.has_permission('sales_order.view'));

-- No insert/update/delete policy on either table — every write goes through
-- the RPCs below, same discipline as purchase_orders (0033).

insert into public.permissions (code, description)
values
  ('sales_order.view', 'View sales orders'),
  ('sales_order.manage', 'Create, submit, cancel and complete sales orders'),
  ('sales_order.approve', 'Approve or reject a submitted sales order');

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
  from public.roles r, public.permissions p
 where p.code = 'sales_order.view'
   and r.code in ('system_admin', 'company_admin', 'warehouse_manager',
                   'inventory_controller', 'shipper', 'viewer');

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
  from public.roles r, public.permissions p
 where p.code = 'sales_order.manage'
   and r.code in ('system_admin', 'company_admin', 'warehouse_manager',
                   'inventory_controller');

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
  from public.roles r, public.permissions p
 where p.code = 'sales_order.approve'
   and r.code in ('system_admin', 'company_admin', 'warehouse_manager');

-- --------------------------------------------------------------------- RPCs

create or replace function public.create_sales_order(
  p_customer_name text,
  p_warehouse_id bigint,
  p_lines jsonb,
  p_customer_id bigint default null,
  p_requested_ship_date date default null,
  p_note text default null
) returns bigint
language plpgsql security definer set search_path = '' as $$
declare
  v_id bigint;
  v_company_id bigint;
  v_line jsonb;
  v_qty integer;
begin
  if not public.has_permission('sales_order.manage') then
    raise exception 'not permitted: sales_order.manage required';
  end if;
  if p_customer_name is null or p_customer_name = '' then
    raise exception 'customer_name is required';
  end if;
  if not exists (select 1 from public.warehouses where id = p_warehouse_id) then
    raise exception 'warehouse % not found', p_warehouse_id;
  end if;
  if jsonb_typeof(p_lines) is distinct from 'array' or jsonb_array_length(p_lines) = 0 then
    raise exception 'at least one line is required';
  end if;

  select id into v_company_id from public.companies order by id limit 1;

  insert into public.sales_orders
    (company_id, customer_id, customer_name, warehouse_id, requested_ship_date, note, requested_by)
  values
    (v_company_id, p_customer_id, p_customer_name, p_warehouse_id, p_requested_ship_date,
     nullif(p_note, ''), auth.uid())
  returning id into v_id;

  update public.sales_orders
     set so_number = 'SO-' || lpad(v_id::text, 6, '0')
   where id = v_id;

  for v_line in select * from jsonb_array_elements(p_lines) loop
    v_qty := coalesce((v_line->>'quantity')::int, 0);
    if v_qty > 0 and coalesce(v_line->>'jan_code', '') <> '' then
      insert into public.sales_order_lines
        (sales_order_id, jan_code, product_name, quantity, unit_price)
      values (
        v_id, v_line->>'jan_code', coalesce(v_line->>'product_name', ''), v_qty,
        nullif(v_line->>'unit_price', '')::numeric);
    end if;
  end loop;

  if not exists (select 1 from public.sales_order_lines where sales_order_id = v_id) then
    raise exception 'at least one line with a positive quantity is required';
  end if;

  perform public.log_audit('sales_order.created', 'sales_order', v_id::text,
    p_warehouse_id, jsonb_build_object('customer_name', p_customer_name));

  return v_id;
end;
$$;

create or replace function public.submit_sales_order(p_id bigint)
returns boolean
language plpgsql security definer set search_path = '' as $$
declare
  v_status text;
  v_warehouse_id bigint;
begin
  if not public.has_permission('sales_order.manage') then
    raise exception 'not permitted: sales_order.manage required';
  end if;

  select status, warehouse_id into v_status, v_warehouse_id
    from public.sales_orders where id = p_id;
  if v_status is null then raise exception 'sales order % not found', p_id; end if;
  if v_status <> 'DRAFT' then
    raise exception 'sales order % is % and cannot be submitted', p_id, v_status;
  end if;

  update public.sales_orders set status = 'SUBMITTED' where id = p_id;
  perform public.log_audit(
    'sales_order.submitted', 'sales_order', p_id::text, v_warehouse_id, '{}'::jsonb);
  return true;
end;
$$;

-- Self-approval refused once both requester and approver are known — same
-- guard as approve_purchase_order (0033) / approve_transfer_order (0019).
create or replace function public.approve_sales_order(p_id bigint)
returns boolean
language plpgsql security definer set search_path = '' as $$
declare
  v_status text;
  v_warehouse_id bigint;
  v_requested_by uuid;
  v_approver uuid := auth.uid();
begin
  if not public.has_permission('sales_order.approve') then
    raise exception 'not permitted: sales_order.approve required';
  end if;

  select status, warehouse_id, requested_by
    into v_status, v_warehouse_id, v_requested_by
    from public.sales_orders where id = p_id;
  if v_status is null then raise exception 'sales order % not found', p_id; end if;
  if v_status <> 'SUBMITTED' then
    raise exception 'sales order % is % and cannot be approved', p_id, v_status;
  end if;
  if v_requested_by is not null and v_approver is not null and v_requested_by = v_approver then
    raise exception 'a sales order cannot be approved by the person who requested it';
  end if;

  update public.sales_orders
     set status = 'APPROVED', approved_by = v_approver, approved_at = now()
   where id = p_id;
  perform public.log_audit(
    'sales_order.approved', 'sales_order', p_id::text, v_warehouse_id, '{}'::jsonb);
  return true;
end;
$$;

create or replace function public.reject_sales_order(p_id bigint, p_reason text default null)
returns boolean
language plpgsql security definer set search_path = '' as $$
declare
  v_status text;
  v_warehouse_id bigint;
begin
  if not public.has_permission('sales_order.approve') then
    raise exception 'not permitted: sales_order.approve required';
  end if;

  select status, warehouse_id into v_status, v_warehouse_id
    from public.sales_orders where id = p_id;
  if v_status is null then raise exception 'sales order % not found', p_id; end if;
  if v_status <> 'SUBMITTED' then
    raise exception 'sales order % is % and cannot be rejected', p_id, v_status;
  end if;

  update public.sales_orders set status = 'REJECTED' where id = p_id;
  perform public.log_audit('sales_order.rejected', 'sales_order', p_id::text,
    v_warehouse_id, jsonb_build_object('reason', p_reason));
  return true;
end;
$$;

-- DRAFT, SUBMITTED and APPROVED can all be cancelled — nothing has moved
-- yet in any of those states (a sales order never moves stock on its own).
create or replace function public.cancel_sales_order(p_id bigint)
returns boolean
language plpgsql security definer set search_path = '' as $$
declare
  v_status text;
  v_warehouse_id bigint;
begin
  if not public.has_permission('sales_order.manage') then
    raise exception 'not permitted: sales_order.manage required';
  end if;

  select status, warehouse_id into v_status, v_warehouse_id
    from public.sales_orders where id = p_id;
  if v_status is null then raise exception 'sales order % not found', p_id; end if;
  if v_status not in ('DRAFT', 'SUBMITTED', 'APPROVED') then
    raise exception 'sales order % is % and can no longer be cancelled', p_id, v_status;
  end if;

  update public.sales_orders set status = 'CANCELLED' where id = p_id;
  perform public.log_audit('sales_order.cancelled', 'sales_order', p_id::text,
    v_warehouse_id, jsonb_build_object('was', v_status));
  return true;
end;
$$;

-- Bookkeeping close only — no stock movement. Actual fulfillment still goes
-- through the existing shipment-plan/picking/packing flow, unchanged.
create or replace function public.complete_sales_order(p_id bigint)
returns boolean
language plpgsql security definer set search_path = '' as $$
declare
  v_status text;
  v_warehouse_id bigint;
begin
  if not public.has_permission('sales_order.manage') then
    raise exception 'not permitted: sales_order.manage required';
  end if;

  select status, warehouse_id into v_status, v_warehouse_id
    from public.sales_orders where id = p_id;
  if v_status is null then raise exception 'sales order % not found', p_id; end if;
  if v_status <> 'APPROVED' then
    raise exception 'sales order % is % and cannot be completed', p_id, v_status;
  end if;

  update public.sales_orders set status = 'COMPLETED' where id = p_id;
  perform public.log_audit(
    'sales_order.completed', 'sales_order', p_id::text, v_warehouse_id, '{}'::jsonb);
  return true;
end;
$$;

-- ------------------------------------------------------------------- reading

create or replace function public.sales_order_detail(p_id bigint)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.has_permission('sales_order.view') then
    raise exception 'not permitted: sales_order.view required';
  end if;

  return (
    select jsonb_build_object(
      'id', o.id,
      'so_number', o.so_number,
      'customer_id', o.customer_id,
      'customer_name', o.customer_name,
      'warehouse_id', o.warehouse_id,
      'warehouse_name', w.name,
      'status', o.status,
      'order_date', o.order_date,
      'requested_ship_date', o.requested_ship_date,
      'note', o.note,
      'approved_at', o.approved_at,
      'created_at', o.created_at,
      'lines', coalesce((
        select jsonb_agg(jsonb_build_object(
                 'id', l.id, 'jan_code', l.jan_code, 'product_name', l.product_name,
                 'quantity', l.quantity, 'unit_price', l.unit_price) order by l.id)
          from public.sales_order_lines l
         where l.sales_order_id = o.id), '[]'::jsonb))
    from public.sales_orders o
    join public.warehouses w on w.id = o.warehouse_id
   where o.id = p_id);
end;
$$;

create or replace function public.sales_order_index(
  p_warehouse_id bigint default null,
  p_status text default null,
  p_limit integer default 50
) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.has_permission('sales_order.view') then
    raise exception 'not permitted: sales_order.view required';
  end if;

  return coalesce((
    select jsonb_agg(row_to_json(x)::jsonb order by x.id desc)
    from (
      select o.id, o.so_number, o.customer_name, o.warehouse_id, w.name as warehouse_name,
             o.status, o.order_date, o.requested_ship_date, o.created_at,
             (select count(*) from public.sales_order_lines l
               where l.sales_order_id = o.id) as line_count,
             (select coalesce(sum(l.quantity * coalesce(l.unit_price, 0)), 0)
                from public.sales_order_lines l
               where l.sales_order_id = o.id) as total_amount
        from public.sales_orders o
        join public.warehouses w on w.id = o.warehouse_id
       where (p_warehouse_id is null or o.warehouse_id = p_warehouse_id)
         and (p_status is null or o.status = p_status)
       order by o.id desc
       limit greatest(1, least(coalesce(p_limit, 50), 200))
    ) x), '[]'::jsonb);
end;
$$;

-- -------------------------------------------------------------------- grants

revoke all on function public.create_sales_order(text, bigint, jsonb, bigint, date, text) from public, anon;
revoke all on function public.submit_sales_order(bigint) from public, anon;
revoke all on function public.approve_sales_order(bigint) from public, anon;
revoke all on function public.reject_sales_order(bigint, text) from public, anon;
revoke all on function public.cancel_sales_order(bigint) from public, anon;
revoke all on function public.complete_sales_order(bigint) from public, anon;
revoke all on function public.sales_order_detail(bigint) from public, anon;
revoke all on function public.sales_order_index(bigint, text, integer) from public, anon;

grant execute on function public.create_sales_order(text, bigint, jsonb, bigint, date, text) to authenticated, service_role;
grant execute on function public.submit_sales_order(bigint) to authenticated, service_role;
grant execute on function public.approve_sales_order(bigint) to authenticated, service_role;
grant execute on function public.reject_sales_order(bigint, text) to authenticated, service_role;
grant execute on function public.cancel_sales_order(bigint) to authenticated, service_role;
grant execute on function public.complete_sales_order(bigint) to authenticated, service_role;
grant execute on function public.sales_order_detail(bigint) to authenticated, service_role;
grant execute on function public.sales_order_index(bigint, text, integer) to authenticated, service_role;
