-- 0036 — Work orders / kitting / assembly (spec §46 checklist item 9)
--
-- "Work orders / assembly / kitting" were removed with InventorOS. Unlike
-- purchase/sales orders (0033/0034), which are deliberately external
-- documents that never move stock, a work order IS a stock-moving
-- operation — the internal counterpart: consume a set of component JANs,
-- produce one output JAN, entirely inside one warehouse. Scoped to
-- assembly/kitting only (many components → one output), the reading the
-- checklist bullet actually asks for; disassembly (one input → many
-- components) would reuse this same shape and is a natural follow-up, not
-- required for this to be useful on its own.
--
-- Nothing moves until `complete_work_order` — same discipline as
-- transfers/counts: draft → start → complete (or cancel before anything
-- moved). Two new stock_movements types record the two sides of the
-- transformation on the existing per-JAN ledger, so a kitted item's history
-- is traceable the same way a pick or an adjustment already is.
alter table public.stock_movements drop constraint stock_movements_movement_type_check;
alter table public.stock_movements add constraint stock_movements_movement_type_check
  check (movement_type = any (array[
    'OPENING', 'RECEIPT', 'RECEIPT_CANCEL', 'PUTAWAY', 'PICK', 'SHIP', 'SHIP_CANCEL',
    'ADJUST', 'COUNT', 'TRANSFER_IN', 'TRANSFER_OUT',
    'WORK_ORDER_CONSUME', 'WORK_ORDER_PRODUCE'
  ]));

create table public.work_orders (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id),
  wo_number text,
  warehouse_id bigint not null references public.warehouses(id),
  output_jan_code text not null,
  output_product_name text not null default '',
  output_quantity integer not null check (output_quantity > 0),
  status text not null default 'DRAFT'
    check (status in ('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
  note text,
  created_by uuid references public.app_users(id),
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index work_orders_number_idx
  on public.work_orders (wo_number) where wo_number is not null;
create index work_orders_warehouse_idx
  on public.work_orders (warehouse_id, status);

create table public.work_order_components (
  id bigint generated by default as identity primary key,
  work_order_id bigint not null references public.work_orders(id) on delete cascade,
  jan_code text not null,
  product_name text not null default '',
  quantity_required integer not null check (quantity_required > 0)
);

create index work_order_components_order_idx
  on public.work_order_components (work_order_id);

alter table public.work_orders enable row level security;
alter table public.work_order_components enable row level security;

create policy "work_orders: viewers can read"
  on public.work_orders for select
  to authenticated
  using (public.has_permission('work_order.view'));

create policy "work_order_components: viewers can read"
  on public.work_order_components for select
  to authenticated
  using (public.has_permission('work_order.view'));

-- No insert/update/delete policy on either table — every write goes through
-- the RPCs below, same discipline as purchase_orders/sales_orders.

insert into public.permissions (code, description)
values
  ('work_order.view', 'View work orders'),
  ('work_order.manage', 'Create, start, complete and cancel work orders');

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
  from public.roles r, public.permissions p
 where p.code = 'work_order.view'
   and r.code in ('system_admin', 'company_admin', 'warehouse_manager',
                   'inventory_controller', 'receiving', 'putaway_operator',
                   'picker', 'viewer');

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
  from public.roles r, public.permissions p
 where p.code = 'work_order.manage'
   and r.code in ('system_admin', 'company_admin', 'warehouse_manager',
                   'inventory_controller');

-- --------------------------------------------------------------------- RPCs

create or replace function public.create_work_order(
  p_warehouse_id bigint,
  p_output_jan_code text,
  p_output_quantity integer,
  p_components jsonb,
  p_output_product_name text default '',
  p_note text default null
) returns bigint
language plpgsql security definer set search_path = '' as $$
declare
  v_id bigint;
  v_company_id bigint;
  v_component jsonb;
  v_qty integer;
begin
  if not public.has_permission('work_order.manage') then
    raise exception 'not permitted: work_order.manage required';
  end if;
  if not exists (select 1 from public.warehouses where id = p_warehouse_id) then
    raise exception 'warehouse % not found', p_warehouse_id;
  end if;
  if p_output_jan_code is null or p_output_jan_code = '' then
    raise exception 'output_jan_code is required';
  end if;
  if p_output_quantity is null or p_output_quantity <= 0 then
    raise exception 'output_quantity must be positive';
  end if;
  if jsonb_typeof(p_components) is distinct from 'array' or jsonb_array_length(p_components) = 0 then
    raise exception 'at least one component is required';
  end if;

  select id into v_company_id from public.companies order by id limit 1;

  insert into public.work_orders
    (company_id, warehouse_id, output_jan_code, output_product_name, output_quantity,
     note, created_by)
  values
    (v_company_id, p_warehouse_id, p_output_jan_code, coalesce(p_output_product_name, ''),
     p_output_quantity, nullif(p_note, ''), auth.uid())
  returning id into v_id;

  update public.work_orders
     set wo_number = 'WO-' || lpad(v_id::text, 6, '0')
   where id = v_id;

  for v_component in select * from jsonb_array_elements(p_components) loop
    v_qty := coalesce((v_component->>'quantity_required')::int, 0);
    if v_qty > 0 and coalesce(v_component->>'jan_code', '') <> '' then
      insert into public.work_order_components
        (work_order_id, jan_code, product_name, quantity_required)
      values (
        v_id, v_component->>'jan_code', coalesce(v_component->>'product_name', ''), v_qty);
    end if;
  end loop;

  if not exists (select 1 from public.work_order_components where work_order_id = v_id) then
    raise exception 'at least one component with a positive quantity is required';
  end if;

  perform public.log_audit('work_order.created', 'work_order', v_id::text, p_warehouse_id,
    jsonb_build_object('output_jan_code', p_output_jan_code, 'output_quantity', p_output_quantity));

  return v_id;
end;
$$;

create or replace function public.start_work_order(p_id bigint)
returns boolean
language plpgsql security definer set search_path = '' as $$
declare
  v_status text;
  v_warehouse_id bigint;
begin
  if not public.has_permission('work_order.manage') then
    raise exception 'not permitted: work_order.manage required';
  end if;

  select status, warehouse_id into v_status, v_warehouse_id
    from public.work_orders where id = p_id;
  if v_status is null then raise exception 'work order % not found', p_id; end if;
  if v_status <> 'DRAFT' then
    raise exception 'work order % is % and cannot be started', p_id, v_status;
  end if;

  update public.work_orders set status = 'IN_PROGRESS', started_at = now() where id = p_id;
  perform public.log_audit(
    'work_order.started', 'work_order', p_id::text, v_warehouse_id, '{}'::jsonb);
  return true;
end;
$$;

create or replace function public.cancel_work_order(p_id bigint)
returns boolean
language plpgsql security definer set search_path = '' as $$
declare
  v_status text;
  v_warehouse_id bigint;
begin
  if not public.has_permission('work_order.manage') then
    raise exception 'not permitted: work_order.manage required';
  end if;

  select status, warehouse_id into v_status, v_warehouse_id
    from public.work_orders where id = p_id;
  if v_status is null then raise exception 'work order % not found', p_id; end if;
  if v_status not in ('DRAFT', 'IN_PROGRESS') then
    raise exception 'work order % is % and can no longer be cancelled', p_id, v_status;
  end if;

  update public.work_orders set status = 'CANCELLED' where id = p_id;
  perform public.log_audit('work_order.cancelled', 'work_order', p_id::text,
    v_warehouse_id, jsonb_build_object('was', v_status));
  return true;
end;
$$;

-- The only step that moves stock: every component's required quantity
-- leaves, the output quantity arrives — both on the existing ledger, so a
-- kitted item's history is traceable the same way a pick or count is.
create or replace function public.complete_work_order(p_id bigint)
returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_status text;
  v_warehouse_id bigint;
  v_output_jan text;
  v_output_name text;
  v_output_qty integer;
  r record;
  v_summary jsonb;
begin
  if not public.has_permission('work_order.manage') then
    raise exception 'not permitted: work_order.manage required';
  end if;

  select status, warehouse_id, output_jan_code, output_product_name, output_quantity
    into v_status, v_warehouse_id, v_output_jan, v_output_name, v_output_qty
    from public.work_orders where id = p_id;
  if v_status is null then raise exception 'work order % not found', p_id; end if;
  if v_status <> 'IN_PROGRESS' then
    raise exception 'work order % is % and cannot be completed', p_id, v_status;
  end if;

  for r in
    select jan_code, product_name, quantity_required
      from public.work_order_components
     where work_order_id = p_id
  loop
    perform public.apply_stock_movement(
      v_warehouse_id, r.jan_code, -r.quantity_required, 'WORK_ORDER_CONSUME',
      'work_order', p_id::text, r.product_name);
  end loop;

  perform public.apply_stock_movement(
    v_warehouse_id, v_output_jan, v_output_qty, 'WORK_ORDER_PRODUCE',
    'work_order', p_id::text, v_output_name);

  update public.work_orders
     set status = 'COMPLETED', completed_at = now()
   where id = p_id;

  select jsonb_build_object(
           'work_order_id', p_id,
           'output_jan_code', v_output_jan,
           'output_quantity', v_output_qty,
           'components_consumed', count(*))
    into v_summary
    from public.work_order_components where work_order_id = p_id;

  perform public.log_audit('work_order.completed', 'work_order', p_id::text,
    v_warehouse_id, v_summary);
  return v_summary;
end;
$$;

-- ------------------------------------------------------------------- reading

create or replace function public.work_order_detail(p_id bigint)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.has_permission('work_order.view') then
    raise exception 'not permitted: work_order.view required';
  end if;

  return (
    select jsonb_build_object(
      'id', o.id,
      'wo_number', o.wo_number,
      'warehouse_id', o.warehouse_id,
      'warehouse_name', w.name,
      'output_jan_code', o.output_jan_code,
      'output_product_name', o.output_product_name,
      'output_quantity', o.output_quantity,
      'status', o.status,
      'note', o.note,
      'started_at', o.started_at,
      'completed_at', o.completed_at,
      'created_at', o.created_at,
      'components', coalesce((
        select jsonb_agg(jsonb_build_object(
                 'id', c.id, 'jan_code', c.jan_code, 'product_name', c.product_name,
                 'quantity_required', c.quantity_required) order by c.id)
          from public.work_order_components c
         where c.work_order_id = o.id), '[]'::jsonb))
    from public.work_orders o
    join public.warehouses w on w.id = o.warehouse_id
   where o.id = p_id);
end;
$$;

create or replace function public.work_order_index(
  p_warehouse_id bigint default null,
  p_status text default null,
  p_limit integer default 50
) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.has_permission('work_order.view') then
    raise exception 'not permitted: work_order.view required';
  end if;

  return coalesce((
    select jsonb_agg(row_to_json(x)::jsonb order by x.id desc)
    from (
      select o.id, o.wo_number, o.warehouse_id, w.name as warehouse_name,
             o.output_jan_code, o.output_product_name, o.output_quantity,
             o.status, o.created_at, o.started_at, o.completed_at,
             (select count(*) from public.work_order_components c
               where c.work_order_id = o.id) as component_count
        from public.work_orders o
        join public.warehouses w on w.id = o.warehouse_id
       where (p_warehouse_id is null or o.warehouse_id = p_warehouse_id)
         and (p_status is null or o.status = p_status)
       order by o.id desc
       limit greatest(1, least(coalesce(p_limit, 50), 200))
    ) x), '[]'::jsonb);
end;
$$;

-- -------------------------------------------------------------------- grants

revoke all on function public.create_work_order(bigint, text, integer, jsonb, text, text) from public, anon;
revoke all on function public.start_work_order(bigint) from public, anon;
revoke all on function public.cancel_work_order(bigint) from public, anon;
revoke all on function public.complete_work_order(bigint) from public, anon;
revoke all on function public.work_order_detail(bigint) from public, anon;
revoke all on function public.work_order_index(bigint, text, integer) from public, anon;

grant execute on function public.create_work_order(bigint, text, integer, jsonb, text, text) to authenticated, service_role;
grant execute on function public.start_work_order(bigint) to authenticated, service_role;
grant execute on function public.cancel_work_order(bigint) to authenticated, service_role;
grant execute on function public.complete_work_order(bigint) to authenticated, service_role;
grant execute on function public.work_order_detail(bigint) to authenticated, service_role;
grant execute on function public.work_order_index(bigint, text, integer) to authenticated, service_role;
