-- 0037 — Custom/saved report builder (spec §46 checklist item 10)
--
-- `report.view` has existed since 0012 (one of the original 22 permissions,
-- already granted to company_admin/system_admin/warehouse_manager/viewer)
-- but nothing has ever implemented it — this is the actual gap the
-- checklist calls out ("no Supabase equivalent"), not a missing permission.
--
-- Scoped deliberately: a fixed set of safe, server-defined report sources
-- (never arbitrary user SQL) each with a small structured filter set, plus
-- the ability to save a chosen source+filters combination by name for
-- reuse — the "custom/saved" part of the ask — without building a general
-- query language. Every source reads tables this app already has; nothing
-- new is computed.
create table public.report_definitions (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id),
  name text not null,
  source text not null check (source in (
    'stock_movements', 'purchase_orders', 'sales_orders', 'work_orders',
    'audit_log', 'products')),
  filters jsonb not null default '{}'::jsonb,
  created_by uuid references public.app_users(id),
  created_at timestamptz not null default now()
);

create index report_definitions_company_idx
  on public.report_definitions (company_id, created_at desc);

alter table public.report_definitions enable row level security;

create policy "report_definitions: viewers can read"
  on public.report_definitions for select
  to authenticated
  using (public.has_permission('report.view'));

-- No insert/update/delete policy — every write goes through the RPCs below.

insert into public.permissions (code, description)
values ('report.manage', 'Save and delete custom report definitions');

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
  from public.roles r, public.permissions p
 where p.code = 'report.manage'
   and r.code in ('system_admin', 'company_admin', 'warehouse_manager');

-- --------------------------------------------------------------------- RPCs

-- Runs one of the fixed report sources with its filters. p_filters keys are
-- read defensively (missing/wrong-typed keys are just treated as unset)
-- rather than raising, so a saved definition never breaks if a future
-- change narrows a filter's meaning.
create or replace function public.run_report(
  p_source text,
  p_filters jsonb default '{}'::jsonb,
  p_limit integer default 500
) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare
  v_warehouse_id bigint := nullif(p_filters->>'warehouse_id', '')::bigint;
  v_status text := nullif(p_filters->>'status', '');
  v_jan_code text := nullif(p_filters->>'jan_code', '');
  v_movement_type text := nullif(p_filters->>'movement_type', '');
  v_event_type text := nullif(p_filters->>'event_type', '');
  v_category text := nullif(p_filters->>'category', '');
  v_date_from timestamptz := nullif(p_filters->>'date_from', '')::timestamptz;
  v_date_to timestamptz := nullif(p_filters->>'date_to', '')::timestamptz;
  v_limit integer := greatest(1, least(coalesce(p_limit, 500), 2000));
  v_rows jsonb;
begin
  if not public.has_permission('report.view') then
    raise exception 'not permitted: report.view required';
  end if;
  if p_source not in ('stock_movements', 'purchase_orders', 'sales_orders',
                       'work_orders', 'audit_log', 'products') then
    raise exception 'unknown report source %', p_source;
  end if;

  if p_source = 'stock_movements' then
    select coalesce(jsonb_agg(row_to_json(t)), '[]'::jsonb) into v_rows
      from (
        select m.id, m.warehouse_id, w.name as warehouse_name, m.jan_code,
               m.product_name, m.movement_type, m.quantity, m.quantity_before,
               m.quantity_after, m.created_at
          from public.stock_movements m
          left join public.warehouses w on w.id = m.warehouse_id
         where (v_warehouse_id is null or m.warehouse_id = v_warehouse_id)
           and (v_jan_code is null or m.jan_code = v_jan_code)
           and (v_movement_type is null or m.movement_type = v_movement_type)
           and (v_date_from is null or m.created_at >= v_date_from)
           and (v_date_to is null or m.created_at <= v_date_to)
         order by m.created_at desc, m.id desc
         limit v_limit
      ) t;

  elsif p_source = 'purchase_orders' then
    select coalesce(jsonb_agg(row_to_json(t)), '[]'::jsonb) into v_rows
      from (
        select o.id, o.po_number, o.supplier_name, o.warehouse_id,
               w.name as warehouse_name, o.status, o.order_date,
               o.expected_date, o.created_at,
               (select count(*) from public.purchase_order_lines l
                 where l.purchase_order_id = o.id) as line_count
          from public.purchase_orders o
          join public.warehouses w on w.id = o.warehouse_id
         where (v_warehouse_id is null or o.warehouse_id = v_warehouse_id)
           and (v_status is null or o.status = v_status)
           and (v_date_from is null or o.created_at >= v_date_from)
           and (v_date_to is null or o.created_at <= v_date_to)
         order by o.id desc
         limit v_limit
      ) t;

  elsif p_source = 'sales_orders' then
    select coalesce(jsonb_agg(row_to_json(t)), '[]'::jsonb) into v_rows
      from (
        select o.id, o.so_number, o.customer_name, o.warehouse_id,
               w.name as warehouse_name, o.status, o.order_date,
               o.requested_ship_date, o.created_at,
               (select count(*) from public.sales_order_lines l
                 where l.sales_order_id = o.id) as line_count
          from public.sales_orders o
          join public.warehouses w on w.id = o.warehouse_id
         where (v_warehouse_id is null or o.warehouse_id = v_warehouse_id)
           and (v_status is null or o.status = v_status)
           and (v_date_from is null or o.created_at >= v_date_from)
           and (v_date_to is null or o.created_at <= v_date_to)
         order by o.id desc
         limit v_limit
      ) t;

  elsif p_source = 'work_orders' then
    select coalesce(jsonb_agg(row_to_json(t)), '[]'::jsonb) into v_rows
      from (
        select o.id, o.wo_number, o.warehouse_id, w.name as warehouse_name,
               o.output_jan_code, o.output_product_name, o.output_quantity,
               o.status, o.created_at, o.started_at, o.completed_at
          from public.work_orders o
          join public.warehouses w on w.id = o.warehouse_id
         where (v_warehouse_id is null or o.warehouse_id = v_warehouse_id)
           and (v_status is null or o.status = v_status)
           and (v_date_from is null or o.created_at >= v_date_from)
           and (v_date_to is null or o.created_at <= v_date_to)
         order by o.id desc
         limit v_limit
      ) t;

  elsif p_source = 'audit_log' then
    select coalesce(jsonb_agg(row_to_json(t)), '[]'::jsonb) into v_rows
      from (
        select a.id, a.created_at, a.warehouse_id, w.name as warehouse_name,
               a.actor_user_id, a.event_type, a.entity_type, a.entity_id, a.details
          from public.audit_log a
          left join public.warehouses w on w.id = a.warehouse_id
         where (v_warehouse_id is null or a.warehouse_id = v_warehouse_id)
           and (v_event_type is null or a.event_type = v_event_type)
           and (v_date_from is null or a.created_at >= v_date_from)
           and (v_date_to is null or a.created_at <= v_date_to)
         order by a.created_at desc, a.id desc
         limit v_limit
      ) t;

  elsif p_source = 'products' then
    select coalesce(jsonb_agg(row_to_json(t)), '[]'::jsonb) into v_rows
      from (
        select p.id, p.jan_code, p.name, p.category, p.price, p.status, p.created_at
          from public.products p
         where (v_status is null or p.status = v_status)
           and (v_category is null or p.category = v_category)
         order by p.name
         limit v_limit
      ) t;
  end if;

  return jsonb_build_object('source', p_source, 'rows', v_rows);
end;
$$;

create or replace function public.save_report_definition(
  p_name text,
  p_source text,
  p_filters jsonb default '{}'::jsonb
) returns bigint
language plpgsql security definer set search_path = '' as $$
declare
  v_id bigint;
  v_company_id bigint;
begin
  if not public.has_permission('report.manage') then
    raise exception 'not permitted: report.manage required';
  end if;
  if p_name is null or p_name = '' then
    raise exception 'name is required';
  end if;
  if p_source not in ('stock_movements', 'purchase_orders', 'sales_orders',
                       'work_orders', 'audit_log', 'products') then
    raise exception 'unknown report source %', p_source;
  end if;

  select id into v_company_id from public.companies order by id limit 1;

  insert into public.report_definitions (company_id, name, source, filters, created_by)
  values (v_company_id, p_name, p_source, coalesce(p_filters, '{}'::jsonb), auth.uid())
  returning id into v_id;

  perform public.log_audit('report.saved', 'report_definition', v_id::text, null,
    jsonb_build_object('name', p_name, 'source', p_source));

  return v_id;
end;
$$;

create or replace function public.list_report_definitions()
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.has_permission('report.view') then
    raise exception 'not permitted: report.view required';
  end if;

  return coalesce(
    (select jsonb_agg(jsonb_build_object(
        'id', d.id, 'name', d.name, 'source', d.source, 'filters', d.filters,
        'created_at', d.created_at) order by d.created_at desc)
      from public.report_definitions d),
    '[]'::jsonb);
end;
$$;

create or replace function public.delete_report_definition(p_id bigint)
returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not public.has_permission('report.manage') then
    raise exception 'not permitted: report.manage required';
  end if;

  delete from public.report_definitions where id = p_id;
  if not found then
    raise exception 'report definition % not found', p_id;
  end if;

  perform public.log_audit('report.deleted', 'report_definition', p_id::text, null, '{}'::jsonb);
  return true;
end;
$$;

revoke all on function public.run_report(text, jsonb, integer) from public, anon;
revoke all on function public.save_report_definition(text, text, jsonb) from public, anon;
revoke all on function public.list_report_definitions() from public, anon;
revoke all on function public.delete_report_definition(bigint) from public, anon;

grant execute on function public.run_report(text, jsonb, integer) to authenticated, service_role;
grant execute on function public.save_report_definition(text, text, jsonb) to authenticated, service_role;
grant execute on function public.list_report_definitions() to authenticated, service_role;
grant execute on function public.delete_report_definition(bigint) to authenticated, service_role;
