-- 0038 — Put-away queue (UI spec §13 "現在の重要ギャップ", §51 P0)
--
-- 0016 already built the bin side of put-away: `bin_stock`,
-- `apply_bin_movement`, a bin→bin `putaway()`, and `bin_stock_overview`. What
-- was missing is the part an operator actually needs, and the reason §13 calls
-- put-away the current critical gap:
--
--   * `putaway()` moves stock *between two bins*. Receiving posts a
--     WAREHOUSE-scoped RECEIPT (`apply_stock_movement`, no bin), so freshly
--     received stock sits in no bin at all — there is nothing to move *from*,
--     and that RPC can never put it away.
--   * Nothing anywhere answers "what is waiting to be put away?".
--   * `putaway()` is granted to `service_role` only and has no permission
--     check, so the Flutter client cannot call it. Meanwhile
--     `putaway.confirm` has existed as a permission since 0012 and has never
--     been used by anything — the same dormant-placeholder situation
--     `report.view` was in before 0037.
--
-- The queue is *derived*, not a new work table: per JAN, warehouse on-hand
-- minus what is already in this warehouse's bins is the amount still awaiting
-- put-away. That keeps the single source of truth in the ledger (§48
-- "Business Event → Stock Movement → Ledger → Derived On Hand") and means
-- receiving/QC need no changes to feed the queue — anything that raises
-- warehouse stock shows up automatically.
--
-- A put-away redistributes stock inside a warehouse; it never changes the
-- warehouse total. So confirming one writes a BIN-scoped movement only, via
-- 0016's existing `apply_bin_movement`.

-- Work record + idempotency guard (§49: double-tap must not double-count).
create table public.putaway_confirmations (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id),
  warehouse_id bigint not null references public.warehouses(id),
  bin_id bigint not null references public.bins(id),
  jan_code text not null,
  quantity integer not null check (quantity > 0),
  idempotency_key text,
  confirmed_by uuid references public.app_users(id),
  created_at timestamptz not null default now()
);

create unique index putaway_confirmations_idempotency_idx
  on public.putaway_confirmations (idempotency_key)
  where idempotency_key is not null;
create index putaway_confirmations_warehouse_idx
  on public.putaway_confirmations (warehouse_id, created_at desc);

alter table public.putaway_confirmations enable row level security;

create policy "putaway_confirmations: inventory viewers can read"
  on public.putaway_confirmations for select
  to authenticated
  using (public.has_permission('inventory.view'));

-- No insert/update/delete policy — writes go through confirm_putaway below.

-- --------------------------------------------------------------------- read

-- What is still waiting to be put away in this warehouse, newest-pressure
-- first (largest pending quantity). Empty for a warehouse that has not opted
-- into locations (0016): without bins there is no put-away step at all.
create or replace function public.putaway_queue(p_warehouse_id bigint)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.has_permission('inventory.view') then
    raise exception 'not permitted: inventory.view required';
  end if;
  if p_warehouse_id is null then
    raise exception 'warehouse is required';
  end if;
  if not public.warehouse_uses_locations(p_warehouse_id) then
    return '[]'::jsonb;
  end if;

  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'jan_code', q.jan_code,
      'product_name', q.product_name,
      'warehouse_on_hand', q.on_hand,
      'binned_quantity', q.binned,
      'pending_quantity', q.pending,
      -- The bin that already holds the most of this JAN here, so repeat
      -- receipts of the same item keep landing in the same place; falls back
      -- to the lowest-coded active pickable bin for a first-time item.
      'suggested_bin_id', q.suggested_bin_id,
      'suggested_bin_code', q.suggested_bin_code
    ) order by q.pending desc, q.jan_code)
    from (
      select s.jan_code,
             s.product_name,
             s.on_hand,
             coalesce(b.binned, 0) as binned,
             s.on_hand - coalesce(b.binned, 0) as pending,
             sg.bin_id as suggested_bin_id,
             sg.bin_code as suggested_bin_code
        from public.stock_levels s
        left join (
          select bs.jan_code, sum(bs.on_hand)::int as binned
            from public.bin_stock bs
            join public.bins bn on bn.id = bs.bin_id
           where bn.warehouse_id = p_warehouse_id
           group by bs.jan_code
        ) b on b.jan_code = s.jan_code
        left join lateral (
          select bn.id as bin_id, bn.code as bin_code
            from public.bins bn
            left join public.bin_stock bs
                   on bs.bin_id = bn.id and bs.jan_code = s.jan_code
           where bn.warehouse_id = p_warehouse_id
             and bn.is_active
             and bn.bin_type in ('PICKABLE', 'PICKABLE_STAGING')
           order by coalesce(bs.on_hand, 0) desc, bn.code
           limit 1
        ) sg on true
       where s.warehouse_id = p_warehouse_id
         and s.on_hand - coalesce(b.binned, 0) > 0
    ) q), '[]'::jsonb);
end;
$$;

-- Resolve a scanned location barcode to its bin, with what it currently holds
-- — exactly what §13's "ロケーションをスキャン → 現在: …" step needs. Code
-- match is case-insensitive and trimmed, because a scanner or a typed entry
-- may not match the stored casing.
create or replace function public.bin_by_code(p_warehouse_id bigint, p_code text)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare
  v_bin record;
begin
  if not public.has_permission('inventory.view') then
    raise exception 'not permitted: inventory.view required';
  end if;

  select b.id, b.code, b.bin_type, b.is_active
    into v_bin
    from public.bins b
   where b.warehouse_id = p_warehouse_id
     and upper(btrim(b.code)) = upper(btrim(coalesce(p_code, '')))
   limit 1;

  if v_bin.id is null then
    return null;
  end if;

  return jsonb_build_object(
    'bin_id', v_bin.id,
    'bin_code', v_bin.code,
    'bin_type', v_bin.bin_type,
    'is_active', v_bin.is_active,
    'lines', coalesce((
      select jsonb_agg(jsonb_build_object(
               'jan_code', bs.jan_code,
               'product_name', bs.product_name,
               'on_hand', bs.on_hand) order by bs.on_hand desc)
        from public.bin_stock bs
       where bs.bin_id = v_bin.id and bs.on_hand > 0), '[]'::jsonb));
end;
$$;

-- -------------------------------------------------------------------- write

-- Put a received quantity of one JAN into one bin. Uses 0016's
-- `apply_bin_movement`, so the warehouse total is untouched and the ledger
-- gets a BIN-scoped PUTAWAY row.
--
-- Refuses to put away more than is actually pending, so a double submit or a
-- stale screen cannot invent bin stock that the warehouse balance does not
-- back. `p_idempotency_key` makes a retried request return the first result
-- instead of posting twice (§49).
create or replace function public.confirm_putaway(
  p_warehouse_id bigint,
  p_jan_code text,
  p_bin_id bigint,
  p_quantity integer,
  p_idempotency_key text default null,
  p_note text default null
) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_company_id bigint;
  v_bin record;
  v_on_hand integer;
  v_binned integer;
  v_pending integer;
  v_product_name text;
  v_existing public.putaway_confirmations;
  v_id bigint;
begin
  if not public.has_permission('putaway.confirm') then
    raise exception 'not permitted: putaway.confirm required';
  end if;
  if coalesce(p_quantity, 0) <= 0 then
    raise exception 'quantity must be positive';
  end if;
  if p_jan_code is null or p_jan_code = '' then
    raise exception 'jan_code is required';
  end if;

  -- Idempotent replay: same key, same answer, nothing posted twice.
  if p_idempotency_key is not null and p_idempotency_key <> '' then
    select * into v_existing
      from public.putaway_confirmations
     where idempotency_key = p_idempotency_key;
    if v_existing.id is not null then
      return jsonb_build_object(
        'putaway_id', v_existing.id,
        'jan_code', v_existing.jan_code,
        'bin_id', v_existing.bin_id,
        'quantity', v_existing.quantity,
        'replayed', true);
    end if;
  end if;

  if not public.warehouse_uses_locations(p_warehouse_id) then
    raise exception 'warehouse % does not use locations', p_warehouse_id;
  end if;

  select b.id, b.code, b.warehouse_id, b.is_active
    into v_bin
    from public.bins b where b.id = p_bin_id;
  if v_bin.id is null then
    raise exception 'bin % not found', p_bin_id;
  end if;
  if v_bin.warehouse_id <> p_warehouse_id then
    raise exception 'bin % belongs to another warehouse', p_bin_id;
  end if;
  if not v_bin.is_active then
    raise exception 'bin % is inactive', v_bin.code;
  end if;

  select s.on_hand, s.product_name into v_on_hand, v_product_name
    from public.stock_levels s
   where s.warehouse_id = p_warehouse_id and s.jan_code = p_jan_code;
  if v_on_hand is null then
    raise exception '% is not in stock in this warehouse', p_jan_code;
  end if;

  select coalesce(sum(bs.on_hand), 0)::int into v_binned
    from public.bin_stock bs
    join public.bins bn on bn.id = bs.bin_id
   where bn.warehouse_id = p_warehouse_id and bs.jan_code = p_jan_code;

  v_pending := v_on_hand - v_binned;
  if p_quantity > v_pending then
    raise exception 'only % of % awaits put-away, cannot put away %',
      v_pending, p_jan_code, p_quantity;
  end if;

  perform public.apply_bin_movement(
    p_bin_id, p_jan_code, p_quantity, 'PUTAWAY',
    'putaway_queue', p_warehouse_id::text, v_product_name, p_note);

  select id into v_company_id from public.companies order by id limit 1;

  insert into public.putaway_confirmations (
    company_id, warehouse_id, bin_id, jan_code, quantity, idempotency_key, confirmed_by)
  values (
    v_company_id, p_warehouse_id, p_bin_id, p_jan_code, p_quantity,
    nullif(p_idempotency_key, ''), auth.uid())
  returning id into v_id;

  perform public.log_audit(
    'putaway.confirmed', 'bin', p_bin_id::text, p_warehouse_id,
    jsonb_build_object('jan_code', p_jan_code, 'quantity', p_quantity,
                       'bin_code', v_bin.code));

  return jsonb_build_object(
    'putaway_id', v_id,
    'jan_code', p_jan_code,
    'bin_id', p_bin_id,
    'bin_code', v_bin.code,
    'quantity', p_quantity,
    'bin_on_hand', (select on_hand from public.bin_stock
                     where bin_id = p_bin_id and jan_code = p_jan_code),
    'pending_after', v_pending - p_quantity,
    'replayed', false);
end;
$$;

-- ---------------------------------------------------------------- dashboard

-- 棚入れ待ち was one of §23's original six counts and the one key 0021 could
-- not supply, because no put-away concept existed to count. Same signature,
-- one more key — no overload ambiguity (0021's own lesson).
create or replace function public.dashboard_metrics(
  p_days integer default 14,
  p_low_threshold integer default 10,
  p_warehouse_id bigint default null
) returns jsonb
language sql security definer set search_path = 'public' as $function$
  with tz as (select 'Asia/Tokyo'::text as zone),
  today as (select (now() at time zone (select zone from tz))::date as d),
  span_start as (select (select d from today) - (greatest(p_days,1) - 1) as d),
  inbound as (
    select ((r.created_at at time zone (select zone from tz))::date) as day,
           coalesce(sum(rl.actual_quantity),0)::bigint as units,
           count(distinct r.id) as events
    from delivery_reconciliations r
    join delivery_plans dp on dp.id = r.delivery_plan_id
    left join reconciliation_lines rl on rl.reconciliation_id = r.id
    where coalesce(r.status,'') <> 'cancelled'
      and (p_warehouse_id is null or dp.warehouse_id = p_warehouse_id)
      and (r.created_at at time zone (select zone from tz))::date >= (select d from span_start)
    group by 1
  ),
  outbound as (
    select ((s.shipped_at at time zone (select zone from tz))::date) as day,
           coalesce(sum(sl.quantity),0)::bigint as units,
           count(distinct s.id) as events
    from shipment_plans s
    left join shipment_lines sl on sl.shipment_plan_id = s.id
    where s.status = 'shipped' and s.shipped_at is not null
      and (p_warehouse_id is null or s.warehouse_id = p_warehouse_id)
      and (s.shipped_at at time zone (select zone from tz))::date >= (select d from span_start)
    group by 1
  ),
  days as (
    select generate_series((select d from span_start), (select d from today), interval '1 day')::date as day
  ),
  trend as (
    select d.day,
           coalesce(i.units,0) as inbound,
           coalesce(o.units,0) as outbound
    from days d
    left join inbound i on i.day = d.day
    left join outbound o on o.day = d.day
  ),
  outstanding_plans as (
    select p.id, p.delivery_number, p.supplier_name,
           coalesce(sum(greatest(l.planned_quantity - coalesce(l.received_quantity,0),0)),0)::bigint as outstanding
    from delivery_plans p
    join delivery_plan_lines l on l.delivery_plan_id = p.id
    where p.status in ('open','reconciling','partial')
      and (p_warehouse_id is null or p.warehouse_id = p_warehouse_id)
    group by p.id, p.delivery_number, p.supplier_name
    having coalesce(sum(greatest(l.planned_quantity - coalesce(l.received_quantity,0),0)),0) > 0
  ),
  low_stock as (
    select jan_code, product_name, on_hand
    from stock_levels
    where on_hand <= p_low_threshold
      and (p_warehouse_id is null or warehouse_id = p_warehouse_id)
  ),
  stock_scope as (
    select * from stock_levels
    where (p_warehouse_id is null or warehouse_id = p_warehouse_id)
  ),
  -- 検品待ち: inbound lots not yet fully inspected.
  pending_inspections as (
    select count(*) as n from inspections i
    where i.status = 'PENDING'
      and (p_warehouse_id is null or i.warehouse_id = p_warehouse_id)
  ),
  -- 棚入れ待ち (0038): per-JAN warehouse stock not yet assigned to any bin,
  -- counted only for warehouses that opted into locations — without bins
  -- there is no put-away step. Same derivation as putaway_queue().
  putaway_pending as (
    select count(*) as n, coalesce(sum(pending),0)::bigint as units
    from (
      select s.warehouse_id, s.jan_code,
             s.on_hand - coalesce(b.binned,0) as pending
      from stock_levels s
      join warehouses w on w.id = s.warehouse_id and w.uses_locations
      left join (
        select bn.warehouse_id, bs.jan_code, sum(bs.on_hand)::int as binned
        from bin_stock bs join bins bn on bn.id = bs.bin_id
        group by bn.warehouse_id, bs.jan_code
      ) b on b.warehouse_id = s.warehouse_id and b.jan_code = s.jan_code
      where (p_warehouse_id is null or s.warehouse_id = p_warehouse_id)
    ) q
    where q.pending > 0
  ),
  -- ピッキング: pick lists currently being worked.
  open_picking as (
    select count(*) as n from pick_lists l
    where l.status = 'PICKING'
      and (p_warehouse_id is null or l.warehouse_id = p_warehouse_id)
  ),
  -- 梱包待ち / 出荷待ち: shipments not yet confirmed. 梱包待ち (still open, not
  -- even packing) and 出荷待ち (packing, ready to confirm) are both real
  -- states in shipment_plans.status.
  packing_wait as (
    select count(*) as n from shipment_plans s
    where s.status = 'open'
      and (p_warehouse_id is null or s.warehouse_id = p_warehouse_id)
  ),
  shipping_wait as (
    select count(*) as n from shipment_plans s
    where s.status = 'packing'
      and (p_warehouse_id is null or s.warehouse_id = p_warehouse_id)
  ),
  -- 棚卸: cycle counts still being counted.
  open_counts as (
    select count(*) as n from stock_counts c
    where c.status = 'COUNTING'
      and (p_warehouse_id is null or c.warehouse_id = p_warehouse_id)
  ),
  -- 倉庫間移動: transfers in flight, either direction for this warehouse.
  open_transfers as (
    select count(*) as n from transfer_orders t
    where t.status in ('PENDING_APPROVAL','APPROVED','PICKING','IN_TRANSIT','RECEIVING')
      and (p_warehouse_id is null
           or t.source_warehouse_id = p_warehouse_id
           or t.destination_warehouse_id = p_warehouse_id)
  )
  select jsonb_build_object(
    'as_of', (select d from today),
    'warehouse_id', p_warehouse_id,
    'inbound_today_units', (select coalesce(sum(units),0) from inbound where day = (select d from today)),
    'inbound_today_events', (select coalesce(sum(events),0) from inbound where day = (select d from today)),
    'outbound_today_units', (select coalesce(sum(units),0) from outbound where day = (select d from today)),
    'outbound_today_events', (select coalesce(sum(events),0) from outbound where day = (select d from today)),
    'outstanding_plan_count', (select count(*) from outstanding_plans),
    'outstanding_units', (select coalesce(sum(outstanding),0) from outstanding_plans),
    'total_skus', (select count(*) from stock_scope where on_hand > 0),
    'total_on_hand', (select coalesce(sum(on_hand),0) from stock_scope),
    'low_stock_count', (select count(*) from low_stock),
    'low_threshold', p_low_threshold,
    'pending_inspection_count', (select n from pending_inspections),
    'putaway_pending_count', (select n from putaway_pending),
    'putaway_pending_units', (select units from putaway_pending),
    'open_picking_count', (select n from open_picking),
    'packing_wait_count', (select n from packing_wait),
    'shipping_wait_count', (select n from shipping_wait),
    'open_count_count', (select n from open_counts),
    'open_transfer_count', (select n from open_transfers),
    'trend', (select coalesce(jsonb_agg(jsonb_build_object('day', to_char(day,'YYYY-MM-DD'), 'inbound', inbound, 'outbound', outbound) order by day), '[]'::jsonb) from trend),
    'outstanding_list', (
      select coalesce(jsonb_agg(jsonb_build_object('id', id, 'delivery_number', delivery_number, 'supplier_name', supplier_name, 'outstanding', outstanding) order by outstanding desc), '[]'::jsonb)
      from (select * from outstanding_plans order by outstanding desc limit 8) t
    ),
    'low_stock_list', (
      select coalesce(jsonb_agg(jsonb_build_object('jan_code', jan_code, 'product_name', product_name, 'on_hand', on_hand) order by on_hand asc), '[]'::jsonb)
      from (select * from low_stock order by on_hand asc, jan_code limit 8) t
    )
  );
$function$;

-- ------------------------------------------------------------------- grants

revoke all on function public.putaway_queue(bigint) from public, anon;
revoke all on function public.bin_by_code(bigint, text) from public, anon;
revoke all on function public.confirm_putaway(bigint, text, bigint, integer, text, text) from public, anon;

grant execute on function public.putaway_queue(bigint) to authenticated, service_role;
grant execute on function public.bin_by_code(bigint, text) to authenticated, service_role;
grant execute on function public.confirm_putaway(bigint, text, bigint, integer, text, text) to authenticated, service_role;
