-- Phase A, steps 1-2 of the InvenTree maturation spec: give a product a stable
-- internal identity, and let it carry more than one barcode.
--
-- Spec §3 and §37-8 both say the same thing from different angles: JAN must
-- stop being the product's primary key. Today it effectively is — `products`
-- has an `id`, but nothing references it, and `stock_levels`, `bin_stock`,
-- `stock_movements`, `pick_tasks`, `shipment_carton_items` and
-- `work_order_components` all key on `jan_code` text.
--
-- This migration does NOT change any of that. It is deliberately additive
-- (spec §2, §38): it builds the identity and the alias table that later steps
-- need, and leaves every existing column, RPC and client call working exactly
-- as before. Repointing the stock tables at `product_id` is a later step, and
-- it needs this mapping to exist first.
--
-- What it adds:
--
--   products.sku            the internal code §3 asks for, unique per company
--                           when present, free to be null while the operator
--                           has not assigned one
--   products.tracking_mode  §4's UNTRACKED / LOT / SERIAL / LOT_AND_SERIAL /
--                           EXPIRY, which is what will decide whether a lot or
--                           serial is required when steps 4-6 land. Defaults to
--                           UNTRACKED so every existing product keeps today's
--                           behaviour.
--   product_barcodes        §3's alias table: JAN, EAN/UPC, an internal SKU
--                           code, a case code, a QR, a logistics label — many
--                           per product, each resolving back to the one id.
--   normalize_barcode()     one place that decides what two scans being "the
--                           same code" means.
--   resolve_barcode()       §26's resolver, so no screen has to decide for
--                           itself what a scan was.
--
-- Multi-tenancy is respected even though there is one company today: barcode
-- uniqueness is per company, enforced by a composite foreign key rather than a
-- trigger, so `product_barcodes.company_id` cannot disagree with its product's.

-- ---------------------------------------------------------------------------
-- 1. Product identity
-- ---------------------------------------------------------------------------

alter table public.products
  add column if not exists sku text,
  add column if not exists tracking_mode text not null default 'UNTRACKED';

alter table public.products
  drop constraint if exists products_tracking_mode_check;
alter table public.products
  add constraint products_tracking_mode_check
  check (tracking_mode in
    ('UNTRACKED', 'LOT', 'SERIAL', 'LOT_AND_SERIAL', 'EXPIRY'));

-- Unique only where assigned: a product without an internal code yet is not in
-- conflict with every other product that also has none.
create unique index if not exists products_company_sku_key
  on public.products (company_id, sku) where sku is not null;

-- The FK target for product_barcodes. `id` alone is already unique, but the
-- composite is what lets the child carry company_id and be unable to lie
-- about it.
alter table public.products
  drop constraint if exists products_company_id_id_key;
alter table public.products
  add constraint products_company_id_id_key unique (company_id, id);

-- ---------------------------------------------------------------------------
-- 2. What counts as the same code
-- ---------------------------------------------------------------------------

-- Mirrors `normalizeJan` in supabase/functions/import-plan/index.ts so a code
-- typed by hand, scanned, or read off a delivery note by OCR all land on one
-- value: full-width digits folded to ASCII, separators dropped, and a 12-digit
-- UPC-A padded to the 13-digit EAN/JAN form it is the same article as.
--
-- Not restricted to digits, because CODE128 and internal SKUs are
-- alphanumeric; those are upper-cased so case is not a difference either.
create or replace function public.normalize_barcode(p_raw text)
returns text
language sql immutable
as $$
  with stripped as (
    select regexp_replace(
             translate(coalesce(p_raw, ''), '０１２３４５６７８９－', '0123456789-'),
             '[^0-9A-Za-z]', '', 'g') as code
  )
  select case
           when code = '' then null
           when code ~ '^[0-9]{12}$' then '0' || code
           else upper(code)
         end
    from stripped;
$$;

revoke all on function public.normalize_barcode(text) from public, anon;
grant execute on function public.normalize_barcode(text) to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 3. The alias table
-- ---------------------------------------------------------------------------

create table if not exists public.product_barcodes (
  id bigint generated by default as identity primary key,
  company_id bigint not null,
  product_id bigint not null,
  -- Always stored normalized, so a lookup never has to guess. The RPCs below
  -- are the only writers and they normalize on the way in.
  barcode text not null,
  barcode_type text not null default 'JAN',
  is_primary boolean not null default false,
  -- §21's "scan one case, get 12". 1 for a piece-level barcode.
  quantity_per_scan integer not null default 1,
  note text,
  created_at timestamptz not null default now(),
  constraint product_barcodes_type_check check (barcode_type in
    ('JAN', 'EAN', 'UPC', 'ITF', 'CODE128', 'QR', 'SKU', 'CASE', 'PALLET', 'OTHER')),
  constraint product_barcodes_quantity_check check (quantity_per_scan > 0),
  constraint product_barcodes_barcode_check check (barcode <> ''),
  -- Composite, so company_id is guaranteed to be the product's own.
  constraint product_barcodes_product_fkey
    foreign key (company_id, product_id)
    references public.products (company_id, id) on delete cascade,
  -- One scan, one product. This is the constraint the whole table exists for.
  constraint product_barcodes_company_barcode_key unique (company_id, barcode)
);

-- At most one primary per product; several products may each have one.
create unique index if not exists product_barcodes_one_primary
  on public.product_barcodes (product_id) where is_primary;
create index if not exists product_barcodes_product_idx
  on public.product_barcodes (product_id);

alter table public.product_barcodes enable row level security;

-- Company master data, not warehouse data, so this is permission-scoped rather
-- than warehouse-scoped — the same shape as the `products` policy it sits
-- beside. `inventory.view` is included because scanning happens during
-- receiving, picking and counting, not only on the product screen.
drop policy if exists "read product barcodes" on public.product_barcodes;
create policy "read product barcodes" on public.product_barcodes
  for select to authenticated
  using (public.has_permission('product.view')
         or public.has_permission('inventory.view'));

-- No INSERT/UPDATE/DELETE policy: writes go through the SECURITY DEFINER RPCs
-- below and the trigger, which is the same rule every other table follows.

-- ---------------------------------------------------------------------------
-- 4. Keep the write path honest
-- ---------------------------------------------------------------------------

-- Every product gets its JAN as a primary barcode, whatever created it —
-- `create_product`, a future importer, or a seed script. A trigger rather than
-- a line inside create_product() so there is exactly one place this happens.
create or replace function public.product_primary_barcode()
returns trigger
language plpgsql security definer set search_path = ''
as $$
declare
  v_code text := public.normalize_barcode(new.jan_code);
begin
  if v_code is null then
    return null;
  end if;
  insert into public.product_barcodes
    (company_id, product_id, barcode, barcode_type, is_primary)
  values (new.company_id, new.id, v_code, 'JAN', true);
  return null;
exception when unique_violation then
  -- Two products whose JANs differ only in punctuation or width normalize to
  -- the same code. Failing the insert is right: a barcode that resolves to two
  -- products is worse than a refused product, and the operator can see why.
  raise exception 'barcode % already belongs to another product', v_code;
end;
$$;

revoke all on function public.product_primary_barcode() from public, anon;

drop trigger if exists products_primary_barcode on public.products;
create trigger products_primary_barcode
  after insert on public.products
  for each row execute function public.product_primary_barcode();

-- Backfill. `products` is empty today, so this moves nothing; it is here so a
-- database rebuilt from the migration history, or one seeded before this point,
-- ends in the same state as one that grew into it.
insert into public.product_barcodes
  (company_id, product_id, barcode, barcode_type, is_primary)
select p.company_id, p.id, public.normalize_barcode(p.jan_code), 'JAN', true
  from public.products p
 where public.normalize_barcode(p.jan_code) is not null
on conflict (company_id, barcode) do nothing;

-- ---------------------------------------------------------------------------
-- 5. The resolver (§26)
-- ---------------------------------------------------------------------------

-- Returns a tagged object rather than a bare product row, so later Phase A
-- steps can add 'lot', 'serial', 'location', 'carton' and so on as new `kind`
-- values without any caller changing the shape it expects. An unknown code is
-- a normal answer, not an error — the operator scanned something, and the UI
-- needs to say "not registered", not show a failure.
create or replace function public.resolve_barcode(p_barcode text)
returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
declare
  v_code text;
  v_result jsonb;
begin
  if not (public.has_permission('product.view')
          or public.has_permission('inventory.view')) then
    raise exception 'not permitted: product.view required';
  end if;

  v_code := public.normalize_barcode(p_barcode);
  if v_code is null then
    return jsonb_build_object('kind', 'unknown', 'barcode', p_barcode);
  end if;

  select jsonb_build_object(
           'kind', 'product',
           'barcode', b.barcode,
           'barcode_type', b.barcode_type,
           'quantity_per_scan', b.quantity_per_scan,
           'is_primary', b.is_primary,
           'product_id', p.id,
           'jan_code', p.jan_code,
           'sku', p.sku,
           'name', p.name,
           'category', p.category,
           'tracking_mode', p.tracking_mode,
           'status', p.status)
    into v_result
    from public.product_barcodes b
    join public.products p on p.id = b.product_id
   where b.barcode = v_code;

  return coalesce(v_result,
                  jsonb_build_object('kind', 'unknown', 'barcode', v_code));
end;
$$;

revoke all on function public.resolve_barcode(text) from public, anon;
grant execute on function public.resolve_barcode(text) to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 6. Managing aliases and the new identity fields
-- ---------------------------------------------------------------------------

-- Existing signatures are left alone so no client call changes. These are new
-- entry points for the new data.

create or replace function public.add_product_barcode(
  p_product_id bigint,
  p_barcode text,
  p_barcode_type text default 'JAN',
  p_quantity_per_scan integer default 1,
  p_is_primary boolean default false,
  p_note text default null
) returns bigint
language plpgsql security definer set search_path = ''
as $$
declare
  v_code text;
  v_company_id bigint;
  v_id bigint;
begin
  if not public.has_permission('product.manage') then
    raise exception 'not permitted: product.manage required';
  end if;

  v_code := public.normalize_barcode(p_barcode);
  if v_code is null then
    raise exception 'barcode is required';
  end if;

  select company_id into v_company_id
    from public.products where id = p_product_id;
  if v_company_id is null then
    raise exception 'product % not found', p_product_id;
  end if;

  -- Demote the current primary first, or the partial unique index rejects the
  -- insert rather than the operator's intent being honoured.
  if p_is_primary then
    update public.product_barcodes
       set is_primary = false
     where product_id = p_product_id and is_primary;
  end if;

  begin
    insert into public.product_barcodes (company_id, product_id, barcode,
      barcode_type, is_primary, quantity_per_scan, note)
    values (v_company_id, p_product_id, v_code, upper(p_barcode_type),
      coalesce(p_is_primary, false), coalesce(p_quantity_per_scan, 1), p_note)
    returning id into v_id;
  exception when unique_violation then
    raise exception 'barcode % already belongs to another product', v_code;
  end;

  perform public.log_audit('product.barcode_added', 'product',
    p_product_id::text, null,
    jsonb_build_object('barcode', v_code, 'barcode_type', upper(p_barcode_type),
                       'quantity_per_scan', coalesce(p_quantity_per_scan, 1)));
  return v_id;
end;
$$;

revoke all on function public.add_product_barcode(bigint, text, text, integer, boolean, text)
  from public, anon;
grant execute on function public.add_product_barcode(bigint, text, text, integer, boolean, text)
  to authenticated, service_role;

create or replace function public.remove_product_barcode(p_barcode_id bigint)
returns boolean
language plpgsql security definer set search_path = ''
as $$
declare
  v_product_id bigint;
  v_code text;
  v_is_primary boolean;
begin
  if not public.has_permission('product.manage') then
    raise exception 'not permitted: product.manage required';
  end if;

  select product_id, barcode, is_primary
    into v_product_id, v_code, v_is_primary
    from public.product_barcodes where id = p_barcode_id;
  if v_product_id is null then
    raise exception 'barcode % not found', p_barcode_id;
  end if;
  -- The primary is how the product is identified on a scan; removing it would
  -- leave a product nothing resolves to. Promote another one first.
  if v_is_primary then
    raise exception 'cannot remove the primary barcode; promote another first';
  end if;

  delete from public.product_barcodes where id = p_barcode_id;

  perform public.log_audit('product.barcode_removed', 'product',
    v_product_id::text, null, jsonb_build_object('barcode', v_code));
  return true;
end;
$$;

revoke all on function public.remove_product_barcode(bigint) from public, anon;
grant execute on function public.remove_product_barcode(bigint) to authenticated, service_role;

create or replace function public.set_product_identity(
  p_id bigint,
  p_sku text default null,
  p_tracking_mode text default null
) returns boolean
language plpgsql security definer set search_path = ''
as $$
declare
  v_sku text := nullif(btrim(coalesce(p_sku, '')), '');
  v_mode text := nullif(btrim(upper(coalesce(p_tracking_mode, ''))), '');
begin
  if not public.has_permission('product.manage') then
    raise exception 'not permitted: product.manage required';
  end if;
  if v_mode is not null and v_mode not in
     ('UNTRACKED', 'LOT', 'SERIAL', 'LOT_AND_SERIAL', 'EXPIRY') then
    raise exception 'unknown tracking_mode %', v_mode;
  end if;

  -- coalesce, so passing only one field leaves the other as it was.
  update public.products
     set sku = coalesce(v_sku, sku),
         tracking_mode = coalesce(v_mode, tracking_mode),
         updated_at = now()
   where id = p_id;
  if not found then
    raise exception 'product % not found', p_id;
  end if;

  perform public.log_audit('product.identity_updated', 'product', p_id::text,
    null, jsonb_build_object('sku', v_sku, 'tracking_mode', v_mode));
  return true;
end;
$$;

revoke all on function public.set_product_identity(bigint, text, text) from public, anon;
grant execute on function public.set_product_identity(bigint, text, text)
  to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 7. Surface the new fields on the existing read
-- ---------------------------------------------------------------------------

-- Additive to the JSON only: `sku`, `tracking_mode` and `barcodes` are new
-- keys, every existing key keeps its name and meaning, and the Dart model
-- ignores keys it does not know. Search now also matches sku and any
-- registered barcode, which is what having aliases is for.
create or replace function public.list_products(
  p_search text default null,
  p_status text default 'active'
) returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
begin
  if not public.has_permission('product.view') then
    raise exception 'not permitted: product.view required';
  end if;

  return coalesce(
    (select jsonb_agg(jsonb_build_object(
        'id', p.id, 'jan_code', p.jan_code, 'name', p.name,
        'category', p.category, 'price', p.price, 'status', p.status,
        'sku', p.sku, 'tracking_mode', p.tracking_mode,
        'created_at', p.created_at, 'updated_at', p.updated_at,
        'barcodes', coalesce((
          select jsonb_agg(jsonb_build_object(
                   'id', b.id, 'barcode', b.barcode,
                   'barcode_type', b.barcode_type,
                   'is_primary', b.is_primary,
                   'quantity_per_scan', b.quantity_per_scan)
                 order by b.is_primary desc, b.barcode)
            from public.product_barcodes b where b.product_id = p.id
        ), '[]'::jsonb)
      ) order by p.name)
      from public.products p
     where (p_status is null or p.status = p_status)
       and (p_search is null or p_search = '' or
            p.name ilike '%' || p_search || '%' or
            p.jan_code ilike '%' || p_search || '%' or
            p.sku ilike '%' || p_search || '%' or
            exists (select 1 from public.product_barcodes b
                     where b.product_id = p.id
                       and b.barcode ilike '%' ||
                           coalesce(public.normalize_barcode(p_search), p_search) || '%'))),
    '[]'::jsonb);
end;
$$;

revoke all on function public.list_products(text, text) from public, anon;
grant execute on function public.list_products(text, text) to authenticated, service_role;
