-- Phase A, step 4: units of measure (§21).
--
-- §21's example is the whole feature: scan a box once and get twelve pieces,
-- scan a case and get 144. 0057 already put `quantity_per_scan` on
-- `product_barcodes`, which is that multiplier — but nothing said what the 12
-- was *twelve of*, or let an operator define the pack without inventing a
-- barcode for it. This adds the vocabulary and the per-product conversions.
--
-- Two tables, exactly as §21 splits them, and the split matters:
--
--   uoms          the vocabulary — PCS, BOX, CASE, KG, L, 巻, 枚. Global,
--                 because "box" means the same word everywhere.
--   product_uoms  the conversions — per product, because a box of pens and a
--                 box of copier paper are not the same number of pieces. A
--                 global "1 BOX = 12" would be wrong for almost everything.
--
-- `products.base_uom_id` is the unit its `on_hand` is counted in. Every
-- existing quantity in this database is already a count of pieces; declaring
-- PCS as the base states what was already true rather than changing anything.
--
-- WHAT THIS DOES NOT DO, AND WHY
--
-- The ledger is integer: `stock_levels.on_hand`, `stock_movements.quantity`
-- and every line quantity are `integer`. `conversion_factor` is numeric, so
-- master data can express a 500 g bag as 0.5 — but a barcode whose scan would
-- produce a fractional quantity is refused, because the row it would write
-- cannot hold it. Widening the ledger to numeric is its own migration with its
-- own risks (rounding, existing arithmetic, the report SQL) and does not belong
-- in the same change as introducing the vocabulary.

-- ---------------------------------------------------------------------------
-- 1. The vocabulary
-- ---------------------------------------------------------------------------

create table if not exists public.uoms (
  id bigint generated by default as identity primary key,
  code text not null,
  -- Japanese, because this is what an operator reads on a picking screen, and
  -- it matches how product and supplier names are already stored. The code is
  -- the stable key; the name is a label.
  name text not null,
  uom_type text not null default 'COUNT',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint uoms_code_key unique (code),
  constraint uoms_code_check check (code = upper(btrim(code)) and code <> ''),
  constraint uoms_type_check check (uom_type in ('COUNT', 'WEIGHT', 'VOLUME', 'LENGTH'))
);

alter table public.uoms enable row level security;

-- Readable by anyone who can see a product or stock: a unit label appears on
-- every receiving, picking and counting screen.
drop policy if exists "read uoms" on public.uoms;
create policy "read uoms" on public.uoms
  for select to authenticated
  using (public.has_permission('product.view')
         or public.has_permission('inventory.view'));

-- A modest starting vocabulary for a Japanese warehouse. Note that
-- set_product_uom() below rejects a unit that is not in this table rather than
-- creating it on demand: a typo would otherwise become a new unit, and a
-- vocabulary nobody curates stops meaning anything.
insert into public.uoms (code, name, uom_type) values
  ('PCS',    '個',       'COUNT'),
  ('SET',    'セット',   'COUNT'),
  ('PACK',   'パック',   'COUNT'),
  ('BOX',    '箱',       'COUNT'),
  ('CASE',   'ケース',   'COUNT'),
  ('BAG',    '袋',       'COUNT'),
  ('ROLL',   '巻',       'COUNT'),
  ('SHEET',  '枚',       'COUNT'),
  ('DOZEN',  'ダース',   'COUNT'),
  ('PALLET', 'パレット', 'COUNT'),
  ('KG',     'kg',       'WEIGHT'),
  ('G',      'g',        'WEIGHT'),
  ('L',      'L',        'VOLUME'),
  ('ML',     'mL',       'VOLUME'),
  ('M',      'm',        'LENGTH'),
  ('CM',     'cm',       'LENGTH')
on conflict (code) do nothing;

-- ---------------------------------------------------------------------------
-- 2. The product's base unit
-- ---------------------------------------------------------------------------

alter table public.products
  add column if not exists base_uom_id bigint references public.uoms (id);

-- Fills the base unit on insert so the column is never left empty. PCS,
-- because every quantity this database already holds is a count of pieces.
create or replace function public.fill_product_base_uom()
returns trigger
language plpgsql security definer set search_path = ''
as $$
begin
  if new.base_uom_id is null then
    select id into new.base_uom_id from public.uoms where code = 'PCS';
  end if;
  return new;
end;
$$;

drop trigger if exists products_fill_base_uom on public.products;
create trigger products_fill_base_uom
  before insert on public.products
  for each row execute function public.fill_product_base_uom();

update public.products
   set base_uom_id = (select id from public.uoms where code = 'PCS')
 where base_uom_id is null;

alter table public.products alter column base_uom_id set not null;

-- ---------------------------------------------------------------------------
-- 3. The conversions
-- ---------------------------------------------------------------------------

create table if not exists public.product_uoms (
  product_id bigint not null references public.products (id) on delete cascade,
  uom_id bigint not null references public.uoms (id) on delete restrict,
  -- How many BASE units one of this unit is. 1 BOX = 12 when the base is PCS.
  -- Numeric so a 500 g bag of a product based in KG is 0.5 — see the note at
  -- the top about the ledger still being integer.
  conversion_factor numeric(18, 6) not null,
  created_at timestamptz not null default now(),
  primary key (product_id, uom_id),
  constraint product_uoms_factor_check check (conversion_factor > 0)
);

create index if not exists product_uoms_uom_idx on public.product_uoms (uom_id);

alter table public.product_uoms enable row level security;

drop policy if exists "read product uoms" on public.product_uoms;
create policy "read product uoms" on public.product_uoms
  for select to authenticated
  using (public.has_permission('product.view')
         or public.has_permission('inventory.view'));

-- Deliberately NOT enforced: that a pack unit share the base unit's
-- `uom_type`. It looks like an invariant and is not — a product based in KG
-- legitimately comes in a BAG (a COUNT unit) of 5, and a product based in PCS
-- legitimately comes in a CASE. The factor is what carries the meaning, and it
-- is type-agnostic by design.

-- The base unit is one of itself. An explicit row rather than an implicit
-- special case, so `product_uoms` answers every conversion question on its own
-- and no caller has to remember to handle the base separately.
create or replace function public.seed_base_product_uom()
returns trigger
language plpgsql security definer set search_path = ''
as $$
begin
  insert into public.product_uoms (product_id, uom_id, conversion_factor)
  values (new.id, new.base_uom_id, 1)
  on conflict (product_id, uom_id) do nothing;
  return null;
end;
$$;

drop trigger if exists products_seed_base_uom on public.products;
create trigger products_seed_base_uom
  after insert on public.products
  for each row execute function public.seed_base_product_uom();

insert into public.product_uoms (product_id, uom_id, conversion_factor)
select p.id, p.base_uom_id, 1 from public.products p
on conflict (product_id, uom_id) do nothing;

-- ---------------------------------------------------------------------------
-- 4. Tie the scan multiplier to the conversions — one source of truth
-- ---------------------------------------------------------------------------

alter table public.product_barcodes
  add column if not exists uom_id bigint references public.uoms (id);

-- §5 warns against counting the same thing twice. `quantity_per_scan` and a
-- `product_uoms` factor are the same number said two ways, so when a barcode
-- names a unit the factor becomes authoritative and the multiplier is derived
-- from it. A barcode with no unit keeps its own multiplier, which is how a
-- plain JAN (one scan, one piece) works.
create or replace function public.derive_barcode_quantity()
returns trigger
language plpgsql security definer set search_path = ''
as $$
declare
  v_factor numeric;
begin
  if new.uom_id is null then
    return new;
  end if;

  select conversion_factor into v_factor
    from public.product_uoms
   where product_id = new.product_id and uom_id = new.uom_id;

  if v_factor is null then
    raise exception
      'product % has no conversion defined for unit %; add it first',
      new.product_id, (select code from public.uoms where id = new.uom_id);
  end if;
  -- The ledger is integer, so a scan that would write 0.5 is refused here
  -- rather than rounded silently somewhere downstream.
  if v_factor <> trunc(v_factor) then
    raise exception
      'unit % converts to %, which stock quantities cannot hold (they are integer)',
      (select code from public.uoms where id = new.uom_id), v_factor;
  end if;

  new.quantity_per_scan := v_factor::integer;
  return new;
end;
$$;

drop trigger if exists product_barcodes_derive_quantity on public.product_barcodes;
create trigger product_barcodes_derive_quantity
  before insert or update of uom_id, quantity_per_scan on public.product_barcodes
  for each row execute function public.derive_barcode_quantity();

-- ---------------------------------------------------------------------------
-- 5. Conversion, and the RPCs
-- ---------------------------------------------------------------------------

-- The function every later step will use: given a quantity in some unit, how
-- many base units is that? Returns null when the product has no conversion for
-- the unit, so a caller has to decide rather than get a silently wrong number.
create or replace function public.to_base_quantity(
  p_product_id bigint,
  p_quantity numeric,
  p_uom_code text default null
) returns numeric
language sql stable security definer set search_path = ''
as $$
  select case
    when p_quantity is null then null
    -- No unit named means the quantity is already in the base unit.
    when p_uom_code is null or btrim(p_uom_code) = '' then p_quantity
    else p_quantity * (
      select pu.conversion_factor
        from public.product_uoms pu
        join public.uoms u on u.id = pu.uom_id
       where pu.product_id = p_product_id
         and u.code = upper(btrim(p_uom_code)))
  end;
$$;

revoke all on function public.to_base_quantity(bigint, numeric, text) from public, anon;
grant execute on function public.to_base_quantity(bigint, numeric, text)
  to authenticated, service_role;

create or replace function public.list_uoms()
returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
begin
  if not (public.has_permission('product.view')
          or public.has_permission('inventory.view')) then
    raise exception 'not permitted: product.view required';
  end if;
  return coalesce((
    select jsonb_agg(jsonb_build_object(
             'id', u.id, 'code', u.code, 'name', u.name,
             'uom_type', u.uom_type, 'is_active', u.is_active)
           order by u.uom_type, u.code)
      from public.uoms u where u.is_active), '[]'::jsonb);
end;
$$;

revoke all on function public.list_uoms() from public, anon;
grant execute on function public.list_uoms() to authenticated, service_role;

-- Define or change one pack size. Upsert, because "a case is 144 not 120" is a
-- correction, not a new fact.
create or replace function public.set_product_uom(
  p_product_id bigint,
  p_uom_code text,
  p_conversion_factor numeric
) returns boolean
language plpgsql security definer set search_path = ''
as $$
declare
  v_uom_id bigint;
  v_base_uom_id bigint;
begin
  if not public.has_permission('product.manage') then
    raise exception 'not permitted: product.manage required';
  end if;
  if p_conversion_factor is null or p_conversion_factor <= 0 then
    raise exception 'conversion_factor must be greater than zero';
  end if;

  select id into v_uom_id from public.uoms
   where code = upper(btrim(coalesce(p_uom_code, ''))) and is_active;
  if v_uom_id is null then
    raise exception 'unknown unit %', p_uom_code;
  end if;

  select base_uom_id into v_base_uom_id from public.products where id = p_product_id;
  if v_base_uom_id is null then
    raise exception 'product % not found', p_product_id;
  end if;
  -- The base unit is one of itself by definition; letting it be edited would
  -- rescale every quantity already recorded against the product.
  if v_uom_id = v_base_uom_id and p_conversion_factor <> 1 then
    raise exception
      'the base unit is 1 by definition; change the base unit instead of its factor';
  end if;

  insert into public.product_uoms (product_id, uom_id, conversion_factor)
  values (p_product_id, v_uom_id, p_conversion_factor)
  on conflict (product_id, uom_id)
    do update set conversion_factor = excluded.conversion_factor;

  -- Any barcode that names this unit now means a different number of pieces.
  -- Touch them so the derive trigger recomputes rather than leaving a stale
  -- multiplier behind.
  update public.product_barcodes
     set uom_id = v_uom_id
   where product_id = p_product_id and uom_id = v_uom_id;

  perform public.log_audit('product.uom_set', 'product', p_product_id::text, null,
    jsonb_build_object('uom', upper(btrim(p_uom_code)),
                       'conversion_factor', p_conversion_factor));
  return true;
end;
$$;

revoke all on function public.set_product_uom(bigint, text, numeric) from public, anon;
grant execute on function public.set_product_uom(bigint, text, numeric)
  to authenticated, service_role;

create or replace function public.remove_product_uom(
  p_product_id bigint,
  p_uom_code text
) returns boolean
language plpgsql security definer set search_path = ''
as $$
declare
  v_uom_id bigint;
  v_base_uom_id bigint;
begin
  if not public.has_permission('product.manage') then
    raise exception 'not permitted: product.manage required';
  end if;

  select id into v_uom_id from public.uoms where code = upper(btrim(coalesce(p_uom_code, '')));
  if v_uom_id is null then
    raise exception 'unknown unit %', p_uom_code;
  end if;
  select base_uom_id into v_base_uom_id from public.products where id = p_product_id;
  if v_base_uom_id is null then
    raise exception 'product % not found', p_product_id;
  end if;
  if v_uom_id = v_base_uom_id then
    raise exception 'cannot remove the base unit';
  end if;
  if exists (select 1 from public.product_barcodes
              where product_id = p_product_id and uom_id = v_uom_id) then
    raise exception 'a barcode still uses unit %; remove the barcode first',
      upper(btrim(p_uom_code));
  end if;

  delete from public.product_uoms
   where product_id = p_product_id and uom_id = v_uom_id;

  perform public.log_audit('product.uom_removed', 'product', p_product_id::text,
    null, jsonb_build_object('uom', upper(btrim(p_uom_code))));
  return true;
end;
$$;

revoke all on function public.remove_product_uom(bigint, text) from public, anon;
grant execute on function public.remove_product_uom(bigint, text)
  to authenticated, service_role;

-- Changing the base unit rescales the meaning of every quantity already
-- recorded, so it is refused once there is any. That is the §37-15 rule —
-- a past transaction must not change meaning because master data changed.
create or replace function public.set_product_base_uom(
  p_product_id bigint,
  p_uom_code text
) returns boolean
language plpgsql security definer set search_path = ''
as $$
declare
  v_uom_id bigint;
  v_old_id bigint;
  v_rows bigint;
begin
  if not public.has_permission('product.manage') then
    raise exception 'not permitted: product.manage required';
  end if;

  select id into v_uom_id from public.uoms
   where code = upper(btrim(coalesce(p_uom_code, ''))) and is_active;
  if v_uom_id is null then
    raise exception 'unknown unit %', p_uom_code;
  end if;

  select base_uom_id into v_old_id from public.products where id = p_product_id;
  if v_old_id is null then
    raise exception 'product % not found', p_product_id;
  end if;
  if v_old_id = v_uom_id then
    return true;
  end if;

  select count(*) into v_rows from public.stock_movements where product_id = p_product_id;
  if v_rows > 0 then
    raise exception
      'product % already has % stock movements; changing its base unit would '
      'change what those quantities mean', p_product_id, v_rows;
  end if;

  update public.products set base_uom_id = v_uom_id, updated_at = now()
   where id = p_product_id;
  insert into public.product_uoms (product_id, uom_id, conversion_factor)
  values (p_product_id, v_uom_id, 1)
  on conflict (product_id, uom_id) do update set conversion_factor = 1;

  perform public.log_audit('product.base_uom_changed', 'product',
    p_product_id::text, null,
    jsonb_build_object('from_uom_id', v_old_id, 'to', upper(btrim(p_uom_code))));
  return true;
end;
$$;

revoke all on function public.set_product_base_uom(bigint, text) from public, anon;
grant execute on function public.set_product_base_uom(bigint, text)
  to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 6. Surface it on the existing read
-- ---------------------------------------------------------------------------

-- Additive again: `base_uom`, `uoms` and each barcode's `uom` are new keys.
create or replace function public.list_products(
  p_search text default null,
  p_status text default 'active'
) returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
begin
  if not public.has_permission('product.view') then
    raise exception 'not permitted: product.view required';
  end if;

  return coalesce(
    (select jsonb_agg(jsonb_build_object(
        'id', p.id, 'jan_code', p.jan_code, 'name', p.name,
        'category', p.category, 'price', p.price, 'status', p.status,
        'sku', p.sku, 'tracking_mode', p.tracking_mode,
        'created_at', p.created_at, 'updated_at', p.updated_at,
        'base_uom', (select jsonb_build_object('id', u.id, 'code', u.code, 'name', u.name)
                       from public.uoms u where u.id = p.base_uom_id),
        'uoms', coalesce((
          select jsonb_agg(jsonb_build_object(
                   'code', u.code, 'name', u.name,
                   'conversion_factor', pu.conversion_factor,
                   'is_base', pu.uom_id = p.base_uom_id)
                 order by pu.conversion_factor)
            from public.product_uoms pu
            join public.uoms u on u.id = pu.uom_id
           where pu.product_id = p.id), '[]'::jsonb),
        'barcodes', coalesce((
          select jsonb_agg(jsonb_build_object(
                   'id', b.id, 'barcode', b.barcode,
                   'barcode_type', b.barcode_type,
                   'is_primary', b.is_primary,
                   'quantity_per_scan', b.quantity_per_scan,
                   'uom', (select u.code from public.uoms u where u.id = b.uom_id))
                 order by b.is_primary desc, b.barcode)
            from public.product_barcodes b where b.product_id = p.id
        ), '[]'::jsonb)
      ) order by p.name)
      from public.products p
     where (p_status is null or p.status = p_status)
       and (p_search is null or p_search = '' or
            p.name ilike '%' || p_search || '%' or
            p.jan_code ilike '%' || p_search || '%' or
            p.sku ilike '%' || p_search || '%' or
            exists (select 1 from public.product_barcodes b
                     where b.product_id = p.id
                       and b.barcode ilike '%' ||
                           coalesce(public.normalize_barcode(p_search), p_search) || '%'))),
    '[]'::jsonb);
end;
$$;

revoke all on function public.list_products(text, text) from public, anon;
grant execute on function public.list_products(text, text) to authenticated, service_role;

-- `resolve_barcode` gains the unit and what one scan means in base units, which
-- is the number a scanning screen actually needs.
create or replace function public.resolve_barcode(p_barcode text)
returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
declare
  v_code text;
  v_result jsonb;
begin
  if not (public.has_permission('product.view')
          or public.has_permission('inventory.view')) then
    raise exception 'not permitted: product.view required';
  end if;

  v_code := public.normalize_barcode(p_barcode);
  if v_code is null then
    return jsonb_build_object('kind', 'unknown', 'barcode', p_barcode);
  end if;

  select jsonb_build_object(
           'kind', 'product',
           'barcode', b.barcode,
           'barcode_type', b.barcode_type,
           'quantity_per_scan', b.quantity_per_scan,
           'uom', (select u.code from public.uoms u where u.id = b.uom_id),
           'base_uom', (select u.code from public.uoms u where u.id = p.base_uom_id),
           'is_primary', b.is_primary,
           'product_id', p.id,
           'jan_code', p.jan_code,
           'sku', p.sku,
           'name', p.name,
           'category', p.category,
           'tracking_mode', p.tracking_mode,
           'status', p.status)
    into v_result
    from public.product_barcodes b
    join public.products p on p.id = b.product_id
   where b.barcode = v_code;

  return coalesce(v_result,
                  jsonb_build_object('kind', 'unknown', 'barcode', v_code));
end;
$$;

revoke all on function public.resolve_barcode(text) from public, anon;
grant execute on function public.resolve_barcode(text) to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 7. Let a barcode name its unit when it is registered
-- ---------------------------------------------------------------------------

-- 0057's add_product_barcode() could set `quantity_per_scan` but not say what
-- unit that quantity was, which leaves §21's feature half-connected. Adding a
-- parameter changes the signature, so the old one is dropped rather than left
-- beside the new one — two overloads is an ambiguity PostgREST would have to
-- guess at. Nothing calls it yet (it arrived in 0057 and the Flutter client
-- does not use it), so there is no call to break.
drop function if exists public.add_product_barcode(bigint, text, text, integer, boolean, text);

create or replace function public.add_product_barcode(
  p_product_id bigint,
  p_barcode text,
  p_barcode_type text default 'JAN',
  p_quantity_per_scan integer default 1,
  p_is_primary boolean default false,
  p_note text default null,
  p_uom_code text default null
) returns bigint
language plpgsql security definer set search_path = ''
as $$
declare
  v_code text;
  v_company_id bigint;
  v_uom_id bigint;
  v_id bigint;
begin
  if not public.has_permission('product.manage') then
    raise exception 'not permitted: product.manage required';
  end if;

  v_code := public.normalize_barcode(p_barcode);
  if v_code is null then
    raise exception 'barcode is required';
  end if;

  select company_id into v_company_id
    from public.products where id = p_product_id;
  if v_company_id is null then
    raise exception 'product % not found', p_product_id;
  end if;

  -- When a unit is named, the derive trigger takes `quantity_per_scan` from the
  -- product's conversion, so the two cannot drift apart.
  if p_uom_code is not null and btrim(p_uom_code) <> '' then
    select id into v_uom_id from public.uoms
     where code = upper(btrim(p_uom_code)) and is_active;
    if v_uom_id is null then
      raise exception 'unknown unit %', p_uom_code;
    end if;
  end if;

  if p_is_primary then
    update public.product_barcodes
       set is_primary = false
     where product_id = p_product_id and is_primary;
  end if;

  begin
    insert into public.product_barcodes (company_id, product_id, barcode,
      barcode_type, is_primary, quantity_per_scan, note, uom_id)
    values (v_company_id, p_product_id, v_code, upper(p_barcode_type),
      coalesce(p_is_primary, false), coalesce(p_quantity_per_scan, 1), p_note,
      v_uom_id)
    returning id into v_id;
  exception when unique_violation then
    raise exception 'barcode % already belongs to another product', v_code;
  end;

  perform public.log_audit('product.barcode_added', 'product',
    p_product_id::text, null,
    jsonb_build_object('barcode', v_code, 'barcode_type', upper(p_barcode_type),
                       'uom', upper(btrim(coalesce(p_uom_code, ''))),
                       'quantity_per_scan',
                       (select quantity_per_scan from public.product_barcodes
                         where id = v_id)));
  return v_id;
end;
$$;

revoke all on function
  public.add_product_barcode(bigint, text, text, integer, boolean, text, text)
  from public, anon;
grant execute on function
  public.add_product_barcode(bigint, text, text, integer, boolean, text, text)
  to authenticated, service_role;

-- Trigger functions added here are not client-callable, same as 0058.
do $tighten$
declare f record;
begin
  for f in
    select p.oid::regprocedure as sig
      from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.prorettype = 'trigger'::regtype
  loop
    execute format('revoke all on function %s from public, anon, authenticated', f.sig);
  end loop;
end $tighten$;
