-- Phase A, steps 4-6: Lot / Serial / Expiry as first-class data (§4).
--
-- Today a lot, a serial and an expiry date are three free-text columns on
-- `inspection_items` — `lot`, `serial`, `expiry`. They are written once at
-- inspection and never read again, because there is nothing to read them
-- *from*: no row says "this lot expires on the 31st", so no screen can warn
-- about it and no picker can be told to take the older one first.
--
-- §4 asks for the two tables that make those answers possible. The three steps
-- are one migration because they are one shape: expiry lives on the lot, and a
-- serial points at the lot it came in. Splitting them would mean a `lots` table
-- with no date column and a `serial_numbers` table with nothing to point at.
--
-- 0057 put `products.tracking_mode` in place for exactly this moment. It stops
-- being decoration here: the mode decides whether a lot or a serial is allowed,
-- required, or refused, and it cannot be lowered once the data exists (§37-15).
--
-- WHAT MAKES THIS MORE THAN TWO EMPTY TABLES
--
-- A table nothing writes to is worse than no table: it looks like a feature.
-- So the existing inspection path feeds it. `inspection_items` gains `lot_id`
-- and `serial_id`, and a trigger resolves them from the text columns already
-- being filled in — the same 併走 (run-in-parallel) pattern 0058 used for
-- `product_id`, and for the same reason: the new column becomes correct on live
-- data without any screen changing first.
--
-- This is not §30 being bent. §30 says a scan or an AI produces a *candidate*
-- and a human confirms domain data. A product is master data somebody curates,
-- which is why 0058 refuses to invent one from an unknown JAN. A lot is not
-- master data — it is an observation of what physically arrived, typed in by the
-- inspector who is holding the box. Recording it is the confirmation.

-- ---------------------------------------------------------------------------
-- 1. Lots
-- ---------------------------------------------------------------------------

create table if not exists public.lots (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id),
  product_id bigint not null,
  -- Uppercased and trimmed on the way in (see upsert_lot). Separators are kept:
  -- "A-2024/05" is a lot code an operator will read back off a carton, and
  -- unlike a barcode there is no standard that says the punctuation is noise.
  lot_code text not null,
  manufacture_date date,
  expiry_date date,
  supplier_id bigint references public.delivery_suppliers (id),
  received_at timestamptz,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- The composite FK from 0057: a lot cannot end up under another company's
  -- product, because the pair has to match a real (company_id, id) row.
  constraint lots_product_fk foreign key (company_id, product_id)
    references public.products (company_id, id) on delete cascade,
  constraint lots_code_check check (lot_code = btrim(lot_code) and lot_code <> ''),
  constraint lots_dates_check check (
    manufacture_date is null or expiry_date is null or expiry_date >= manufacture_date),
  constraint lots_product_code_key unique (product_id, lot_code),
  -- Not redundant with the primary key: it is the target `serial_numbers` needs
  -- so that a serial's lot is provably a lot *of the same product*.
  constraint lots_product_id_key unique (product_id, id)
);

create index if not exists lots_expiry_idx on public.lots (expiry_date)
  where expiry_date is not null;
create index if not exists lots_supplier_idx on public.lots (supplier_id);

alter table public.lots enable row level security;

-- SELECT only, and no write policy at all: every write goes through a SECURITY
-- DEFINER function below, which is what lets the tracking-mode rules be the
-- single gate rather than something a direct PostgREST insert can walk around.
drop policy if exists "read lots" on public.lots;
create policy "read lots" on public.lots
  for select to authenticated
  using (public.has_permission('inventory.view')
         or public.has_permission('product.view'));

-- ---------------------------------------------------------------------------
-- 2. Serial numbers
-- ---------------------------------------------------------------------------

create table if not exists public.serial_numbers (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id),
  product_id bigint not null,
  serial_number text not null,
  lot_id bigint,
  status text not null default 'IN_STOCK',
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint serial_numbers_product_fk foreign key (company_id, product_id)
    references public.products (company_id, id) on delete cascade,
  -- Composite, so the lot belongs to the same product. `restrict` rather than
  -- `set null`: a lot with serials against it is not something to delete, and
  -- silently detaching the serial from its lot loses the link that made the
  -- serial traceable in the first place.
  constraint serial_numbers_lot_fk foreign key (product_id, lot_id)
    references public.lots (product_id, id) on delete restrict,
  constraint serial_numbers_value_check check (
    serial_number = btrim(serial_number) and serial_number <> ''),
  constraint serial_numbers_status_check check (
    status in ('IN_STOCK', 'SHIPPED', 'RETURNED', 'SCRAPPED', 'HOLD')),
  -- Company-wide, NOT per product. Two manufacturers can legitimately stamp the
  -- same serial on different goods, so this refuses something that is possible
  -- in the world — but a serial that resolves to two rows is useless at a scan
  -- gun, and resolving a bare serial is the whole point of recording it. When a
  -- genuine collision turns up, the operator prefixes one of them; that is a
  -- cheaper problem than an ambiguous scan.
  constraint serial_numbers_company_value_key unique (company_id, serial_number),
  -- The same FK target trick as lots: it lets a row that references a serial
  -- prove the serial is one of that product's.
  constraint serial_numbers_product_id_key unique (product_id, id)
);

create index if not exists serial_numbers_product_idx
  on public.serial_numbers (product_id, status);
create index if not exists serial_numbers_lot_idx on public.serial_numbers (lot_id);

alter table public.serial_numbers enable row level security;

drop policy if exists "read serial numbers" on public.serial_numbers;
create policy "read serial numbers" on public.serial_numbers
  for select to authenticated
  using (public.has_permission('inventory.view')
         or public.has_permission('product.view'));

-- ---------------------------------------------------------------------------
-- 3. The tracking mode stops being decoration
-- ---------------------------------------------------------------------------

-- 0057 defined five modes. Here is what each one actually means:
--
--   UNTRACKED       no lots, no serials. The default, and what every existing
--                   product is.
--   LOT             lots allowed; expiry optional.
--   EXPIRY          lots allowed and every lot MUST carry an expiry date. This
--                   is the food/medical case: the date is the thing being
--                   tracked and a lot without one is a gap in the record.
--   SERIAL          serials allowed; lots are not.
--   LOT_AND_SERIAL  both, and every serial must name its lot — otherwise the
--                   mode says it tracks two things while recording one.
--
-- Enforced by triggers rather than by the RPCs, so a future caller (a receiving
-- flow, an import, another trigger) cannot get it wrong by forgetting to ask.
create or replace function public.lot_tracking_ok()
returns trigger
language plpgsql security definer set search_path = ''
as $$
declare
  v_mode text;
begin
  select tracking_mode into v_mode from public.products where id = new.product_id;
  if v_mode is null then
    raise exception 'product % not found', new.product_id;
  end if;
  if v_mode not in ('LOT', 'LOT_AND_SERIAL', 'EXPIRY') then
    raise exception
      'product % has tracking_mode %; set it to LOT, LOT_AND_SERIAL or EXPIRY '
      'before recording lots', new.product_id, v_mode;
  end if;
  if v_mode = 'EXPIRY' and new.expiry_date is null then
    raise exception
      'product % tracks expiry, so lot % needs an expiry date',
      new.product_id, new.lot_code;
  end if;
  return new;
end;
$$;

drop trigger if exists lots_tracking_ok on public.lots;
create trigger lots_tracking_ok
  before insert or update on public.lots
  for each row execute function public.lot_tracking_ok();

create or replace function public.serial_tracking_ok()
returns trigger
language plpgsql security definer set search_path = ''
as $$
declare
  v_mode text;
begin
  select tracking_mode into v_mode from public.products where id = new.product_id;
  if v_mode is null then
    raise exception 'product % not found', new.product_id;
  end if;
  if v_mode not in ('SERIAL', 'LOT_AND_SERIAL') then
    raise exception
      'product % has tracking_mode %; set it to SERIAL or LOT_AND_SERIAL '
      'before recording serial numbers', new.product_id, v_mode;
  end if;
  if v_mode = 'LOT_AND_SERIAL' and new.lot_id is null then
    raise exception
      'product % tracks lot and serial, so serial % needs a lot',
      new.product_id, new.serial_number;
  end if;
  return new;
end;
$$;

drop trigger if exists serial_numbers_tracking_ok on public.serial_numbers;
create trigger serial_numbers_tracking_ok
  before insert or update on public.serial_numbers
  for each row execute function public.serial_tracking_ok();

-- The other direction, and the §37-15 half: the mode cannot be changed into one
-- that contradicts data already recorded under it. Dropping to UNTRACKED with
-- lots on file would not delete them — it would leave them unreachable and make
-- every past inspection that referenced one mean something else.
create or replace function public.tracking_mode_change_ok()
returns trigger
language plpgsql security definer set search_path = ''
as $$
begin
  if new.tracking_mode = old.tracking_mode then
    return new;
  end if;

  if new.tracking_mode not in ('LOT', 'LOT_AND_SERIAL', 'EXPIRY')
     and exists (select 1 from public.lots where product_id = old.id) then
    raise exception
      'product % already has lots recorded; tracking_mode cannot become %',
      old.id, new.tracking_mode;
  end if;
  if new.tracking_mode not in ('SERIAL', 'LOT_AND_SERIAL')
     and exists (select 1 from public.serial_numbers where product_id = old.id) then
    raise exception
      'product % already has serial numbers recorded; tracking_mode cannot become %',
      old.id, new.tracking_mode;
  end if;
  -- Tightening is refused too when the existing rows would not satisfy the
  -- stricter mode, because the row triggers above only see rows being written.
  if new.tracking_mode = 'EXPIRY'
     and exists (select 1 from public.lots
                  where product_id = old.id and expiry_date is null) then
    raise exception
      'product % has lots with no expiry date; fill them in before switching to EXPIRY',
      old.id;
  end if;
  if new.tracking_mode = 'LOT_AND_SERIAL'
     and exists (select 1 from public.serial_numbers
                  where product_id = old.id and lot_id is null) then
    raise exception
      'product % has serial numbers with no lot; link them before switching to LOT_AND_SERIAL',
      old.id;
  end if;
  return new;
end;
$$;

drop trigger if exists products_tracking_mode_change_ok on public.products;
create trigger products_tracking_mode_change_ok
  before update of tracking_mode on public.products
  for each row execute function public.tracking_mode_change_ok();

-- ---------------------------------------------------------------------------
-- 4. Writing lots and serials
-- ---------------------------------------------------------------------------

-- The internal upsert. No permission check, because its callers are the
-- permission-checked RPC below and the inspection trigger (whose caller already
-- passed `inspection.confirm`). Granted to nothing: only SECURITY DEFINER
-- callers reach it, and they run as the owner.
--
-- Idempotent on (product_id, lot_code): the second receipt of the same lot is
-- the same lot, and it may be the receipt that finally learns the expiry date.
-- Known dates are filled in, never overwritten with null.
create or replace function public.upsert_lot(
  p_product_id bigint,
  p_lot_code text default null,
  p_expiry_date date default null,
  p_manufacture_date date default null,
  p_supplier_id bigint default null,
  p_received_at timestamptz default null,
  p_note text default null
) returns bigint
language plpgsql security definer set search_path = ''
as $$
declare
  v_code text := nullif(upper(btrim(coalesce(p_lot_code, ''))), '');
  v_company_id bigint;
  v_id bigint;
begin
  select company_id into v_company_id from public.products where id = p_product_id;
  if v_company_id is null then
    raise exception 'product % not found', p_product_id;
  end if;

  -- An EXPIRY-tracked product often has no lot code on the carton at all — the
  -- date IS the identity. Deriving the code here, in one place, keeps
  -- `lot_code` the single handle every other query can rely on instead of
  -- spreading a nullable key through the schema.
  if v_code is null and p_expiry_date is not null then
    v_code := 'EXP-' || to_char(p_expiry_date, 'YYYYMMDD');
  end if;
  if v_code is null then
    raise exception 'a lot needs either a lot code or an expiry date';
  end if;

  insert into public.lots as l (company_id, product_id, lot_code, expiry_date,
                                manufacture_date, supplier_id, received_at, note)
  values (v_company_id, p_product_id, v_code, p_expiry_date,
          p_manufacture_date, p_supplier_id, coalesce(p_received_at, now()), p_note)
  on conflict (product_id, lot_code) do update
     set expiry_date      = coalesce(l.expiry_date, excluded.expiry_date),
         manufacture_date = coalesce(l.manufacture_date, excluded.manufacture_date),
         supplier_id      = coalesce(l.supplier_id, excluded.supplier_id),
         note             = coalesce(l.note, excluded.note),
         updated_at       = now()
  returning l.id into v_id;
  return v_id;
end;
$$;

revoke all on function
  public.upsert_lot(bigint, text, date, date, bigint, timestamptz, text)
  from public, anon, authenticated;

-- Same split, same reason.
create or replace function public.upsert_serial(
  p_product_id bigint,
  p_serial_number text,
  p_lot_id bigint default null,
  p_status text default null,
  p_note text default null
) returns bigint
language plpgsql security definer set search_path = ''
as $$
declare
  v_value text := nullif(upper(btrim(coalesce(p_serial_number, ''))), '');
  v_company_id bigint;
  v_owner bigint;
  v_id bigint;
begin
  if v_value is null then
    raise exception 'serial_number is required';
  end if;
  select company_id into v_company_id from public.products where id = p_product_id;
  if v_company_id is null then
    raise exception 'product % not found', p_product_id;
  end if;

  -- A serial identifies one physical unit, so the same string arriving against
  -- a different product is a data error worth naming rather than a second row
  -- the unique constraint would reject with a generic message.
  select product_id into v_owner from public.serial_numbers
   where company_id = v_company_id and serial_number = v_value;
  if v_owner is not null and v_owner <> p_product_id then
    raise exception 'serial % already belongs to product %', v_value, v_owner;
  end if;

  insert into public.serial_numbers as sn (company_id, product_id, serial_number,
                                          lot_id, status, note)
  values (v_company_id, p_product_id, v_value, p_lot_id,
          coalesce(nullif(upper(btrim(coalesce(p_status, ''))), ''), 'IN_STOCK'), p_note)
  on conflict (company_id, serial_number) do update
     set lot_id     = coalesce(excluded.lot_id, sn.lot_id),
         note       = coalesce(sn.note, excluded.note),
         updated_at = now()
  returning sn.id into v_id;
  return v_id;
end;
$$;

revoke all on function
  public.upsert_serial(bigint, text, bigint, text, text)
  from public, anon, authenticated;

-- The client-facing pair. `inventory.adjust` or `product.manage`: a lot is
-- recorded by whoever is receiving stock, not only by whoever curates the
-- product master.
create or replace function public.register_lot(
  p_product_id bigint,
  p_lot_code text default null,
  p_expiry_date date default null,
  p_manufacture_date date default null,
  p_supplier_id bigint default null,
  p_note text default null
) returns bigint
language plpgsql security definer set search_path = ''
as $$
declare
  v_id bigint;
begin
  if not (public.has_permission('inventory.adjust')
          or public.has_permission('product.manage')) then
    raise exception 'not permitted: inventory.adjust required';
  end if;
  v_id := public.upsert_lot(p_product_id, p_lot_code, p_expiry_date,
                            p_manufacture_date, p_supplier_id, null, p_note);
  perform public.log_audit('product.lot_registered', 'product', p_product_id::text,
    null, jsonb_build_object('lot_id', v_id,
      'lot_code', (select lot_code from public.lots where id = v_id),
      'expiry_date', p_expiry_date));
  return v_id;
end;
$$;

revoke all on function
  public.register_lot(bigint, text, date, date, bigint, text) from public, anon;
grant execute on function
  public.register_lot(bigint, text, date, date, bigint, text)
  to authenticated, service_role;

create or replace function public.register_serial(
  p_product_id bigint,
  p_serial_number text,
  p_lot_code text default null,
  p_note text default null
) returns bigint
language plpgsql security definer set search_path = ''
as $$
declare
  v_lot_id bigint;
  v_id bigint;
begin
  if not (public.has_permission('inventory.adjust')
          or public.has_permission('product.manage')) then
    raise exception 'not permitted: inventory.adjust required';
  end if;
  -- Takes a lot *code*, not an id: at the point of registering a serial the
  -- operator is reading a carton, and an id is not printed on it.
  if nullif(btrim(coalesce(p_lot_code, '')), '') is not null then
    v_lot_id := public.upsert_lot(p_product_id, p_lot_code);
  end if;
  v_id := public.upsert_serial(p_product_id, p_serial_number, v_lot_id, null, p_note);
  perform public.log_audit('product.serial_registered', 'product',
    p_product_id::text, null,
    jsonb_build_object('serial_id', v_id, 'lot_id', v_lot_id));
  return v_id;
end;
$$;

revoke all on function
  public.register_serial(bigint, text, text, text) from public, anon;
grant execute on function
  public.register_serial(bigint, text, text, text) to authenticated, service_role;

create or replace function public.set_serial_status(
  p_serial_id bigint,
  p_status text,
  p_note text default null
) returns boolean
language plpgsql security definer set search_path = ''
as $$
declare
  v_status text := upper(btrim(coalesce(p_status, '')));
  v_found text;
begin
  if not (public.has_permission('inventory.adjust')
          or public.has_permission('product.manage')) then
    raise exception 'not permitted: inventory.adjust required';
  end if;
  if v_status not in ('IN_STOCK', 'SHIPPED', 'RETURNED', 'SCRAPPED', 'HOLD') then
    raise exception 'unknown serial status %', p_status;
  end if;

  update public.serial_numbers
     set status = v_status, note = coalesce(p_note, note), updated_at = now()
   where id = p_serial_id
  -- RETURNING gives back the row it wrote, so a null here means no row matched.
  returning status into v_found;
  if v_found is null then
    raise exception 'serial % not found', p_serial_id;
  end if;

  perform public.log_audit('product.serial_status', 'serial', p_serial_id::text,
    null, jsonb_build_object('status', v_status));
  return true;
end;
$$;

revoke all on function public.set_serial_status(bigint, text, text) from public, anon;
grant execute on function public.set_serial_status(bigint, text, text)
  to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 5. Feed it from the work already being done
-- ---------------------------------------------------------------------------

alter table public.inspection_items add column if not exists lot_id bigint;
alter table public.inspection_items add column if not exists serial_id bigint;

-- Composite FKs, so an inspection line cannot cite a lot belonging to a
-- different product than the one it resolved. MATCH SIMPLE means the constraint
-- is satisfied whenever either column is null, which is what makes it safe to
-- add to a table whose `product_id` is still nullable (0058): unlinked rows are
-- unaffected, and a row with both set is checked.
do $fk$
begin
  if not exists (select 1 from pg_constraint
                  where conname = 'inspection_items_lot_fk'
                    and conrelid = 'public.inspection_items'::regclass) then
    alter table public.inspection_items
      add constraint inspection_items_lot_fk foreign key (product_id, lot_id)
        references public.lots (product_id, id) on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint
                  where conname = 'inspection_items_serial_fk'
                    and conrelid = 'public.inspection_items'::regclass) then
    alter table public.inspection_items
      add constraint inspection_items_serial_fk foreign key (product_id, serial_id)
        references public.serial_numbers (product_id, id) on delete restrict;
  end if;
end $fk$;

create index if not exists inspection_items_lot_idx on public.inspection_items (lot_id);
create index if not exists inspection_items_serial_idx on public.inspection_items (serial_id);

-- Resolves `lot` / `serial` / `expiry` — columns the inspection screen already
-- fills in — into real rows, but only when the product is known and its mode
-- says so. An UNTRACKED product keeps the text and gets no lot: the operator
-- wrote something worth keeping, and inventing a lot the product does not track
-- would put a row in `lots` that nothing will ever look up.
--
-- Never overwrites an id a caller supplied, same as 0058's fill_product_id.
create or replace function public.fill_inspection_identity()
returns trigger
language plpgsql security definer set search_path = ''
as $$
declare
  v_mode text;
  v_lot text := nullif(btrim(coalesce(new.lot, '')), '');
  v_serial text := nullif(btrim(coalesce(new.serial, '')), '');
begin
  if new.product_id is null then
    return new;
  end if;
  select tracking_mode into v_mode from public.products where id = new.product_id;
  if v_mode is null or v_mode = 'UNTRACKED' then
    return new;
  end if;

  if new.lot_id is null
     and v_mode in ('LOT', 'LOT_AND_SERIAL', 'EXPIRY')
     and (v_lot is not null or new.expiry is not null) then
    new.lot_id := public.upsert_lot(new.product_id, v_lot, new.expiry);
  end if;

  if new.serial_id is null
     and v_serial is not null
     and v_mode in ('SERIAL', 'LOT_AND_SERIAL') then
    new.serial_id := public.upsert_serial(new.product_id, v_serial, new.lot_id);
  end if;
  return new;
end;
$$;

-- `zz` so it sorts after `inspection_items_fill_product_id` from 0058: Postgres
-- fires same-timing triggers in name order, and this one needs the product_id
-- that one resolves.
drop trigger if exists inspection_items_zz_fill_identity on public.inspection_items;
create trigger inspection_items_zz_fill_identity
  before insert or update of lot, serial, expiry, product_id, lot_id, serial_id
  on public.inspection_items
  for each row execute function public.fill_inspection_identity();

-- ---------------------------------------------------------------------------
-- 6. Reading it back
-- ---------------------------------------------------------------------------

create or replace function public.product_lots(p_product_id bigint)
returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
begin
  if not (public.has_permission('inventory.view')
          or public.has_permission('product.view')) then
    raise exception 'not permitted: inventory.view required';
  end if;
  return coalesce((
    select jsonb_agg(jsonb_build_object(
             'id', l.id, 'lot_code', l.lot_code,
             'expiry_date', l.expiry_date,
             'manufacture_date', l.manufacture_date,
             'received_at', l.received_at,
             'supplier_id', l.supplier_id,
             'supplier_name', (select s.name from public.delivery_suppliers s
                                where s.id = l.supplier_id),
             'days_to_expiry', case when l.expiry_date is null then null
                               else l.expiry_date - current_date end,
             'serial_count', (select count(*) from public.serial_numbers sn
                               where sn.lot_id = l.id),
             'note', l.note)
           -- Nulls last: a lot with no expiry is not "expiring soonest".
           order by l.expiry_date asc nulls last, l.lot_code)
      from public.lots l where l.product_id = p_product_id), '[]'::jsonb);
end;
$$;

revoke all on function public.product_lots(bigint) from public, anon;
grant execute on function public.product_lots(bigint) to authenticated, service_role;

create or replace function public.product_serials(
  p_product_id bigint,
  p_status text default null
) returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
declare
  v_status text := nullif(upper(btrim(coalesce(p_status, ''))), '');
begin
  if not (public.has_permission('inventory.view')
          or public.has_permission('product.view')) then
    raise exception 'not permitted: inventory.view required';
  end if;
  return coalesce((
    select jsonb_agg(jsonb_build_object(
             'id', sn.id, 'serial_number', sn.serial_number,
             'status', sn.status, 'lot_id', sn.lot_id,
             'lot_code', (select l.lot_code from public.lots l where l.id = sn.lot_id),
             'created_at', sn.created_at, 'note', sn.note)
           order by sn.serial_number)
      from public.serial_numbers sn
     where sn.product_id = p_product_id
       and (v_status is null or sn.status = v_status)), '[]'::jsonb);
end;
$$;

revoke all on function public.product_serials(bigint, text) from public, anon;
grant execute on function public.product_serials(bigint, text)
  to authenticated, service_role;

-- The read §4 exists for. Deliberately not warehouse-scoped: a lot belongs to a
-- product, not to a building, and `lots` carries no warehouse — the same reason
-- list_products is not scoped. It becomes a per-warehouse number in Phase A
-- step 8, when stock rows start carrying `lot_id` and the question changes from
-- "which lots expire" to "how many of them are sitting in bin A-01".
create or replace function public.expiring_lots(
  p_days integer default 30,
  p_include_expired boolean default true
) returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
declare
  v_days integer := greatest(coalesce(p_days, 30), 0);
  v_expired boolean := coalesce(p_include_expired, true);
begin
  if not (public.has_permission('inventory.view')
          or public.has_permission('product.view')) then
    raise exception 'not permitted: inventory.view required';
  end if;
  return coalesce((
    select jsonb_agg(jsonb_build_object(
             'lot_id', l.id, 'lot_code', l.lot_code,
             'expiry_date', l.expiry_date,
             'days_to_expiry', l.expiry_date - current_date,
             'is_expired', l.expiry_date < current_date,
             'product_id', p.id, 'jan_code', p.jan_code, 'sku', p.sku,
             'product_name', p.name,
             'tracking_mode', p.tracking_mode,
             'serial_count', (select count(*) from public.serial_numbers sn
                               where sn.lot_id = l.id))
           order by l.expiry_date, p.name)
      from public.lots l
      join public.products p on p.id = l.product_id
     where l.expiry_date is not null
       and l.expiry_date <= current_date + v_days
       and (v_expired or l.expiry_date >= current_date)), '[]'::jsonb);
end;
$$;

revoke all on function public.expiring_lots(integer, boolean) from public, anon;
grant execute on function public.expiring_lots(integer, boolean)
  to authenticated, service_role;

-- §26 wants one resolver, so a scanned serial answers from the same call a
-- scanned barcode does. A serial label and a product barcode are physically
-- the same gesture at the same scan gun; making the operator pick the right
-- screen first is the kind of thing that gets skipped on the floor.
create or replace function public.resolve_barcode(p_barcode text)
returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
declare
  v_code text;
  v_raw text := nullif(upper(btrim(coalesce(p_barcode, ''))), '');
  v_result jsonb;
begin
  if not (public.has_permission('product.view')
          or public.has_permission('inventory.view')) then
    raise exception 'not permitted: product.view required';
  end if;

  v_code := public.normalize_barcode(p_barcode);
  if v_code is null then
    return jsonb_build_object('kind', 'unknown', 'barcode', p_barcode);
  end if;

  select jsonb_build_object(
           'kind', 'product',
           'barcode', b.barcode,
           'barcode_type', b.barcode_type,
           'quantity_per_scan', b.quantity_per_scan,
           'uom', (select u.code from public.uoms u where u.id = b.uom_id),
           'base_uom', (select u.code from public.uoms u where u.id = p.base_uom_id),
           'is_primary', b.is_primary,
           'product_id', p.id,
           'jan_code', p.jan_code,
           'sku', p.sku,
           'name', p.name,
           'category', p.category,
           'tracking_mode', p.tracking_mode,
           'status', p.status)
    into v_result
    from public.product_barcodes b
    join public.products p on p.id = b.product_id
   where b.barcode = v_code;
  if v_result is not null then
    return v_result;
  end if;

  -- Only after the barcode tables have had their say: a product barcode is the
  -- common case, and a serial that happens to look like one should still
  -- resolve as the product. Matched against both the raw uppercased input and
  -- the normalized code, because normalize_barcode strips the separators a
  -- serial may legitimately contain.
  select jsonb_build_object(
           'kind', 'serial',
           'barcode', sn.serial_number,
           'serial_id', sn.id,
           'serial_number', sn.serial_number,
           'serial_status', sn.status,
           'lot_id', sn.lot_id,
           'lot_code', (select l.lot_code from public.lots l where l.id = sn.lot_id),
           'expiry_date', (select l.expiry_date from public.lots l where l.id = sn.lot_id),
           'quantity_per_scan', 1,
           'base_uom', (select u.code from public.uoms u where u.id = p.base_uom_id),
           'product_id', p.id,
           'jan_code', p.jan_code,
           'sku', p.sku,
           'name', p.name,
           'category', p.category,
           'tracking_mode', p.tracking_mode,
           'status', p.status)
    into v_result
    from public.serial_numbers sn
    join public.products p on p.id = sn.product_id
   where sn.serial_number in (v_raw, v_code)
   order by case when sn.serial_number = v_raw then 0 else 1 end
   limit 1;

  return coalesce(v_result,
                  jsonb_build_object('kind', 'unknown', 'barcode', v_code));
end;
$$;

revoke all on function public.resolve_barcode(text) from public, anon;
grant execute on function public.resolve_barcode(text) to authenticated, service_role;

-- `inspection_detail` is the one existing read that already shows lot / serial /
-- expiry text, so it is where the resolved ids belong. Additive: the text
-- columns stay exactly as they are, and `lot_id` / `serial_id` / `lot_code`
-- appear beside them.
do $patch$
declare
  v_src text;
  v_new text;
  v_old constant text := $$'expiry', it.expiry,$$;
  v_add constant text := $$'expiry', it.expiry,
        'lot_id', it.lot_id,
        'serial_id', it.serial_id,
        'lot_code', (select l.lot_code from public.lots l where l.id = it.lot_id),
        'lot_expiry_date',
          (select l.expiry_date from public.lots l where l.id = it.lot_id),
        'serial_status',
          (select s.status from public.serial_numbers s where s.id = it.serial_id),$$;
begin
  select pg_get_functiondef(p.oid) into v_src
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'inspection_detail_impl';
  if v_src is null then
    raise exception 'inspection_detail_impl not found';
  end if;
  -- Asserted transform, same discipline as 0056: if the body has drifted from
  -- what this expects, the migration stops instead of silently doing nothing.
  if (length(v_src) - length(replace(v_src, v_old, ''))) / length(v_old) <> 1 then
    raise exception
      'inspection_detail_impl no longer contains exactly one %, refusing to patch it',
      v_old;
  end if;
  v_new := replace(v_src, v_old, v_add);
  execute v_new;
end $patch$;

-- ---------------------------------------------------------------------------
-- 7. Housekeeping
-- ---------------------------------------------------------------------------

-- Trigger functions are not client-callable, same as 0058 and 0059.
do $tighten$
declare f record;
begin
  for f in
    select p.oid::regprocedure as sig
      from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.prorettype = 'trigger'::regtype
  loop
    execute format('revoke all on function %s from public, anon, authenticated', f.sig);
  end loop;
end $tighten$;
