-- Phase A, steps 7-8: Stock Status, and Stock Identity / Stock Unit (§5).
--
-- §5's complaint is that `on_hand = 100` is too weak a sentence. It cannot say
-- that twenty of those hundred are quarantined, that ten are damaged, or that
-- the oldest lot expires on Friday — and so it cannot answer the only question
-- an outbound flow actually asks, which is how many can be shipped *today*.
--
--     Available = on-hand that is usable  -  Reserved  -  Blocked/Hold etc.
--
-- and, the sentence that decides the whole design:
--
--     二重計上しないよう、実装上の正規ソースを決める
--     (pick the canonical source so nothing is counted twice)
--
-- WHAT IS ALREADY HERE, AND WHICH SOURCE IS CANONICAL
--
-- `stock_movements` is the ledger and stays the record of what happened (§37-4).
-- Two projections of it exist:
--
--   stock_levels  (warehouse, jan_code) -> on_hand, written by apply_stock_movement
--   bin_stock     (bin, jan_code)       -> on_hand, written by apply_bin_movement
--
-- They are not two copies of one number. A WAREHOUSE-scope movement changes what
-- the warehouse holds; a BIN-scope movement (put-away) only moves stock *inside*
-- the warehouse and leaves the total alone. `stock_movements.balance_scope` is
-- what keeps them apart, and no function writes both for one event.
--
-- `stock_units` joins that picture as a third projection of the same ledger —
-- never as a second writer. One trigger, on WAREHOUSE-scope movements only,
-- keeps it in step with `stock_levels`, so for every warehouse:
--
--     sum(stock_units.quantity) == stock_levels.on_hand
--
-- That equality is the whole safety property. `stock_reconciliation()` checks it
-- on demand, and everything below is arranged so it cannot quietly stop holding.
--
-- WHAT THIS DELIBERATELY DOES NOT DO
--
-- **Bins.** `stock_units.bin_id` exists and stays null. Putting bin granularity
-- in here would mean modelling put-away as a transfer between parcels, and a
-- put-away that outruns its receipt would either drive a parcel negative or
-- silently break the equality above. Bins are step 9's subject, where the
-- location tree is what is actually being worked on; `bin_stock` remains the
-- bin-level answer until then.
--
-- **RESERVED and ALLOCATED are not statuses.** They are in §5's list, but a
-- reserved unit is still physically on hand and still in its own condition —
-- making RESERVED a bucket would move the quantity out of OK and count the
-- reservation twice, once as a missing unit and once as a claim. They become
-- rows in their own table in step 12, and `available` subtracts them there.
--
-- **Every status counts toward on-hand.** Statuses differ only in whether they
-- are *available*. Scrapping is not a status change; it is a stock movement
-- that reduces the total, and it leaves a ledger entry the way §37-4 requires.
-- This is what lets a status change always conserve the warehouse total, which
-- is what keeps the equality above true without a second ledger.

-- ---------------------------------------------------------------------------
-- 1. The status vocabulary
-- ---------------------------------------------------------------------------

create table if not exists public.stock_statuses (
  id bigint generated by default as identity primary key,
  code text not null,
  name text not null,
  -- The §5 formula, as data rather than as a list of codes buried in a query.
  -- There is no `counts_on_hand`: every status does (see the header).
  counts_available boolean not null default false,
  sort_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint stock_statuses_code_key unique (code),
  constraint stock_statuses_code_check check (code = upper(btrim(code)) and code <> '')
);

alter table public.stock_statuses enable row level security;

drop policy if exists "read stock statuses" on public.stock_statuses;
create policy "read stock statuses" on public.stock_statuses
  for select to authenticated
  using (public.has_permission('inventory.view')
         or public.has_permission('product.view'));

insert into public.stock_statuses (code, name, counts_available, sort_order) values
  ('OK',         '良品',     true,  10),
  ('QC_PENDING', '検品待ち', false, 20),
  ('HOLD',       '保留',     false, 30),
  ('QUARANTINE', '隔離',     false, 40),
  ('DAMAGED',    '破損',     false, 50),
  ('EXPIRED',    '期限切れ', false, 60),
  ('BLOCKED',    '出荷停止', false, 70)
on conflict (code) do nothing;

-- ---------------------------------------------------------------------------
-- 2. The stock unit
-- ---------------------------------------------------------------------------

-- One row per distinguishable parcel of stock: this product, in this warehouse,
-- from this lot, in this condition. `quantity` is in the product's base unit
-- (0059) — the conversions exist so a scan can say "one case"; what gets stored
-- is always pieces.
create table if not exists public.stock_units (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id),
  product_id bigint not null,
  warehouse_id bigint not null references public.warehouses (id),
  -- Reserved for step 9; the trigger below never sets it. See the header.
  bin_id bigint references public.bins (id),
  lot_id bigint,
  serial_id bigint,
  status_id bigint not null references public.stock_statuses (id),
  quantity integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint stock_units_product_fk foreign key (company_id, product_id)
    references public.products (company_id, id) on delete restrict,
  constraint stock_units_lot_fk foreign key (product_id, lot_id)
    references public.lots (product_id, id) on delete restrict,
  constraint stock_units_serial_fk foreign key (product_id, serial_id)
    references public.serial_numbers (product_id, id) on delete restrict,
  constraint stock_units_quantity_check check (quantity >= 0),
  -- A serial is one physical unit, so a parcel holding one cannot hold two.
  constraint stock_units_serial_quantity_check check (serial_id is null or quantity <= 1),
  -- NULLS NOT DISTINCT is the point: without it, every parcel with no lot and no
  -- serial would be distinct from every other, and the trigger would add a new
  -- row per movement instead of finding the one it should be adding to.
  constraint stock_units_identity_key unique nulls not distinct
    (product_id, warehouse_id, bin_id, lot_id, serial_id, status_id)
);

create index if not exists stock_units_warehouse_idx
  on public.stock_units (warehouse_id, product_id);
create index if not exists stock_units_lot_idx on public.stock_units (lot_id)
  where lot_id is not null;

alter table public.stock_units enable row level security;

-- Warehouse data, unlike lots and products: scoped, the same way every other
-- stock read has been since 0052.
drop policy if exists "read stock units" on public.stock_units;
create policy "read stock units" on public.stock_units
  for select to authenticated
  using (public.has_permission('inventory.view')
         and public.can_access_warehouse(warehouse_id));

-- ---------------------------------------------------------------------------
-- 3. The projection
-- ---------------------------------------------------------------------------

-- Adds to (or takes from) the parcels of one product in one warehouse, and
-- returns what it could not do — which is always zero when `stock_units` is in
-- step with the ledger, and is the drift when it is not.
--
-- Taking draws from the most available, soonest-expiring parcel first: an
-- outbound should consume the stock that is usable and closest to its date, and
-- should only reach into held or damaged stock when there is nothing else —
-- which in practice means the ledger and the parcels have drifted apart.
create or replace function public.apply_stock_unit_delta(
  p_product_id bigint,
  p_warehouse_id bigint,
  p_delta integer
) returns integer
language plpgsql security definer set search_path = ''
as $$
declare
  v_company_id bigint;
  v_status_id bigint;
  v_left integer := abs(coalesce(p_delta, 0));
  v_take integer;
  v_row record;
begin
  if coalesce(p_delta, 0) = 0 then
    return 0;
  end if;
  select company_id into v_company_id from public.products where id = p_product_id;
  if v_company_id is null then
    return coalesce(p_delta, 0);
  end if;

  if p_delta > 0 then
    select id into v_status_id from public.stock_statuses where code = 'OK';
    insert into public.stock_units as su
      (company_id, product_id, warehouse_id, status_id, quantity)
    values (v_company_id, p_product_id, p_warehouse_id, v_status_id, p_delta)
    on conflict (product_id, warehouse_id, bin_id, lot_id, serial_id, status_id)
      do update set quantity = su.quantity + excluded.quantity, updated_at = now();
    return 0;
  end if;

  for v_row in
    select su.id, su.quantity
      from public.stock_units su
      join public.stock_statuses st on st.id = su.status_id
      left join public.lots l on l.id = su.lot_id
     where su.product_id = p_product_id
       and su.warehouse_id = p_warehouse_id
       and su.quantity > 0
     order by st.counts_available desc, l.expiry_date asc nulls last,
              st.sort_order, su.id
  loop
    exit when v_left <= 0;
    v_take := least(v_left, v_row.quantity);
    update public.stock_units
       set quantity = quantity - v_take, updated_at = now()
     where id = v_row.id;
    v_left := v_left - v_take;
  end loop;

  -- Empty parcels are not history — the ledger holds that — so they go rather
  -- than accumulating as a long tail of zero rows behind every product.
  delete from public.stock_units
   where product_id = p_product_id and warehouse_id = p_warehouse_id
     and quantity = 0 and serial_id is null;

  return -v_left;
end;
$$;

revoke all on function public.apply_stock_unit_delta(bigint, bigint, integer)
  from public, anon, authenticated;

-- The one writer. AFTER INSERT on the ledger, WAREHOUSE scope only, so this
-- cannot become a second source of truth: if it is not in the ledger, it is not
-- in `stock_units`.
create or replace function public.project_stock_movement()
returns trigger
language plpgsql security definer set search_path = ''
as $$
declare
  v_delta integer;
begin
  if coalesce(new.balance_scope, 'WAREHOUSE') <> 'WAREHOUSE' then
    return null;
  end if;
  -- A movement whose JAN no product accounts for cannot be projected onto a
  -- product. 0058 made that case visible and closable (unlinked_jan_codes);
  -- link the product and link_products_by_jan() fills the column, after which
  -- backfill_stock_units() brings the parcels up to date.
  if new.product_id is null then
    return null;
  end if;

  -- The signed effect of the row, taken from the balance it recorded rather
  -- than from `quantity` and a sign convention per movement_type.
  v_delta := new.quantity_after - new.quantity_before;
  perform public.apply_stock_unit_delta(new.product_id, new.warehouse_id, v_delta);
  return null;
end;
$$;

drop trigger if exists stock_movements_project_units on public.stock_movements;
create trigger stock_movements_project_units
  after insert on public.stock_movements
  for each row execute function public.project_stock_movement();

-- Brings `stock_units` to what `stock_levels` says, for every product the rows
-- can be attributed to. Safe to re-run: it computes the difference and applies
-- only that, so running it twice changes nothing the second time. This is the
-- function to run after `link_products_by_jan()` links a JAN that had stock
-- before its product existed.
create or replace function public.backfill_stock_units(
  p_warehouse_id bigint default null
) returns jsonb
language plpgsql security definer set search_path = ''
as $$
declare
  v_row record;
  v_units integer;
  v_delta integer;
  v_adjusted integer := 0;
  v_skipped integer := 0;
begin
  for v_row in
    select sl.warehouse_id, sl.product_id, sl.jan_code, sl.on_hand
      from public.stock_levels sl
     where (p_warehouse_id is null or sl.warehouse_id = p_warehouse_id)
  loop
    if v_row.product_id is null then
      v_skipped := v_skipped + 1;
      continue;
    end if;
    select coalesce(sum(quantity), 0) into v_units
      from public.stock_units
     where product_id = v_row.product_id and warehouse_id = v_row.warehouse_id;
    v_delta := v_row.on_hand - v_units;
    if v_delta <> 0 then
      perform public.apply_stock_unit_delta(
        v_row.product_id, v_row.warehouse_id, v_delta);
      v_adjusted := v_adjusted + 1;
    end if;
  end loop;
  return jsonb_build_object('adjusted', v_adjusted, 'skipped_unlinked', v_skipped);
end;
$$;

revoke all on function public.backfill_stock_units(bigint) from public, anon;
grant execute on function public.backfill_stock_units(bigint) to service_role;

select public.backfill_stock_units();

-- ---------------------------------------------------------------------------
-- 4. Changing a parcel's condition
-- ---------------------------------------------------------------------------

-- Quarantining twenty of a hundred does not change what the warehouse holds; it
-- changes what can be shipped. So this moves quantity between two parcels of
-- the same product in the same warehouse and writes no ledger entry — the total
-- is untouched, which is exactly why the equality with `stock_levels` survives
-- it. Anything that *does* change the total is a stock movement instead.
create or replace function public.move_stock_status(
  p_product_id bigint,
  p_warehouse_id bigint,
  p_quantity integer,
  p_to_status text,
  p_from_status text default 'OK',
  p_note text default null
) returns jsonb
language plpgsql security definer set search_path = ''
as $$
declare
  v_company_id bigint;
  v_from_id bigint;
  v_to_id bigint;
  v_available integer;
  v_left integer := coalesce(p_quantity, 0);
  v_take integer;
  v_row record;
begin
  if not public.has_permission('inventory.adjust') then
    raise exception 'not permitted: inventory.adjust required';
  end if;
  if not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  if v_left <= 0 then
    raise exception 'quantity must be greater than zero';
  end if;

  select id into v_from_id from public.stock_statuses
   where code = upper(btrim(coalesce(p_from_status, 'OK')));
  select id into v_to_id from public.stock_statuses
   where code = upper(btrim(coalesce(p_to_status, ''))) and is_active;
  if v_from_id is null then
    raise exception 'unknown stock status %', p_from_status;
  end if;
  if v_to_id is null then
    raise exception 'unknown stock status %', p_to_status;
  end if;
  if v_from_id = v_to_id then
    raise exception 'the stock is already %', upper(btrim(p_to_status));
  end if;

  select company_id into v_company_id from public.products where id = p_product_id;
  if v_company_id is null then
    raise exception 'product % not found', p_product_id;
  end if;

  select coalesce(sum(quantity), 0) into v_available
    from public.stock_units
   where product_id = p_product_id and warehouse_id = p_warehouse_id
     and status_id = v_from_id;
  if v_available < v_left then
    raise exception 'only % in %, cannot move %',
      v_available, upper(btrim(coalesce(p_from_status, 'OK'))), v_left;
  end if;

  -- Parcel by parcel, so a lot keeps its identity across the change: holding
  -- "20 of lot A" must not come out the other side as "20 of no lot".
  for v_row in
    select su.id, su.quantity, su.lot_id, su.serial_id, su.bin_id
      from public.stock_units su
      left join public.lots l on l.id = su.lot_id
     where su.product_id = p_product_id and su.warehouse_id = p_warehouse_id
       and su.status_id = v_from_id and su.quantity > 0
     order by l.expiry_date asc nulls last, su.id
  loop
    exit when v_left <= 0;
    v_take := least(v_left, v_row.quantity);

    insert into public.stock_units as su
      (company_id, product_id, warehouse_id, bin_id, lot_id, serial_id,
       status_id, quantity)
    values (v_company_id, p_product_id, p_warehouse_id, v_row.bin_id,
            v_row.lot_id, v_row.serial_id, v_to_id, v_take)
    on conflict (product_id, warehouse_id, bin_id, lot_id, serial_id, status_id)
      do update set quantity = su.quantity + excluded.quantity, updated_at = now();

    update public.stock_units
       set quantity = quantity - v_take, updated_at = now()
     where id = v_row.id;
    v_left := v_left - v_take;
  end loop;

  delete from public.stock_units
   where product_id = p_product_id and warehouse_id = p_warehouse_id
     and quantity = 0 and serial_id is null;

  perform public.log_audit('inventory.status_moved', 'product',
    p_product_id::text, p_warehouse_id,
    jsonb_build_object('quantity', p_quantity,
                       'from', upper(btrim(coalesce(p_from_status, 'OK'))),
                       'to', upper(btrim(p_to_status)), 'note', p_note));

  return jsonb_build_object(
    'product_id', p_product_id, 'warehouse_id', p_warehouse_id,
    'moved', p_quantity,
    'available', public.stock_available(p_product_id, p_warehouse_id));
end;
$$;

revoke all on function
  public.move_stock_status(bigint, bigint, integer, text, text, text)
  from public, anon;
grant execute on function
  public.move_stock_status(bigint, bigint, integer, text, text, text)
  to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 5. Reading it — the §5 distinction, finally expressible
-- ---------------------------------------------------------------------------

-- Everything the warehouse physically holds, in every condition.
create or replace function public.stock_on_hand(
  p_product_id bigint,
  p_warehouse_id bigint default null
) returns integer
language sql stable security definer set search_path = ''
as $$
  select coalesce(sum(su.quantity), 0)::integer
    from public.stock_units su
   where su.product_id = p_product_id
     and (p_warehouse_id is null or su.warehouse_id = p_warehouse_id)
     and public.can_access_warehouse(su.warehouse_id);
$$;

revoke all on function public.stock_on_hand(bigint, bigint) from public, anon;
grant execute on function public.stock_on_hand(bigint, bigint)
  to authenticated, service_role;

-- What can actually be shipped. Today that is on-hand in an available status;
-- step 12 subtracts reservations here, and the subtraction belongs *here* so
-- there is one definition of "available" rather than one per caller.
create or replace function public.stock_available(
  p_product_id bigint,
  p_warehouse_id bigint default null
) returns integer
language sql stable security definer set search_path = ''
as $$
  select coalesce(sum(su.quantity), 0)::integer
    from public.stock_units su
    join public.stock_statuses st on st.id = su.status_id
   where su.product_id = p_product_id
     and st.counts_available
     and (p_warehouse_id is null or su.warehouse_id = p_warehouse_id)
     and public.can_access_warehouse(su.warehouse_id);
$$;

revoke all on function public.stock_available(bigint, bigint) from public, anon;
grant execute on function public.stock_available(bigint, bigint)
  to authenticated, service_role;

create or replace function public.list_stock_statuses()
returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
begin
  if not (public.has_permission('inventory.view')
          or public.has_permission('product.view')) then
    raise exception 'not permitted: inventory.view required';
  end if;
  return coalesce((
    select jsonb_agg(jsonb_build_object(
             'id', s.id, 'code', s.code, 'name', s.name,
             'counts_available', s.counts_available)
           order by s.sort_order, s.code)
      from public.stock_statuses s where s.is_active), '[]'::jsonb);
end;
$$;

revoke all on function public.list_stock_statuses() from public, anon;
grant execute on function public.list_stock_statuses() to authenticated, service_role;

-- The screen §5 is asking for: not one number, but the split that explains it.
create or replace function public.stock_status_breakdown(
  p_product_id bigint default null,
  p_warehouse_id bigint default null
) returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
begin
  if not public.has_permission('inventory.view') then
    raise exception 'not permitted: inventory.view required';
  end if;
  if p_warehouse_id is not null and not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;

  return coalesce((
    select jsonb_agg(row_to_json(t)::jsonb order by t.product_name, t.warehouse_id)
      from (
        select su.product_id,
               p.name as product_name,
               p.jan_code,
               p.sku,
               su.warehouse_id,
               w.name as warehouse_name,
               sum(su.quantity)::integer as on_hand,
               coalesce(sum(su.quantity) filter (where st.counts_available), 0)::integer
                 as available,
               jsonb_agg(jsonb_build_object(
                 'status', st.code, 'name', st.name,
                 'quantity', su.quantity,
                 'lot_id', su.lot_id,
                 'lot_code', (select l.lot_code from public.lots l where l.id = su.lot_id),
                 'expiry_date', (select l.expiry_date from public.lots l where l.id = su.lot_id))
                 order by st.sort_order) as parcels
          from public.stock_units su
          join public.stock_statuses st on st.id = su.status_id
          join public.products p on p.id = su.product_id
          join public.warehouses w on w.id = su.warehouse_id
         where (p_product_id is null or su.product_id = p_product_id)
           and (p_warehouse_id is null or su.warehouse_id = p_warehouse_id)
           -- Null warehouse means "every warehouse I may see", never "all".
           and public.can_access_warehouse(su.warehouse_id)
         group by su.product_id, p.name, p.jan_code, p.sku, su.warehouse_id, w.name
      ) t), '[]'::jsonb);
end;
$$;

revoke all on function public.stock_status_breakdown(bigint, bigint) from public, anon;
grant execute on function public.stock_status_breakdown(bigint, bigint)
  to authenticated, service_role;

-- The safety property, made checkable. Every row it returns is a place where
-- the parcels and the ledger's own projection disagree, which means either a
-- movement that could not be attributed to a product (0058's unlinked JANs) or
-- a writer that has gone around the trigger. An empty result is the invariant
-- holding.
create or replace function public.stock_reconciliation(
  p_warehouse_id bigint default null
) returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
begin
  if not public.has_permission('inventory.view') then
    raise exception 'not permitted: inventory.view required';
  end if;
  if p_warehouse_id is not null and not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;

  return coalesce((
    select jsonb_agg(row_to_json(t)::jsonb order by t.warehouse_id, t.jan_code)
      from (
        select sl.warehouse_id,
               sl.jan_code,
               sl.product_id,
               sl.on_hand as stock_levels_on_hand,
               coalesce((select sum(su.quantity) from public.stock_units su
                          where su.product_id = sl.product_id
                            and su.warehouse_id = sl.warehouse_id), 0)::integer
                 as stock_units_on_hand,
               case when sl.product_id is null then 'unlinked jan_code'
                    else 'quantity drift' end as reason
          from public.stock_levels sl
         where (p_warehouse_id is null or sl.warehouse_id = p_warehouse_id)
           and public.can_access_warehouse(sl.warehouse_id)
           and (sl.product_id is null
                or sl.on_hand <> coalesce((select sum(su.quantity)
                                             from public.stock_units su
                                            where su.product_id = sl.product_id
                                              and su.warehouse_id = sl.warehouse_id), 0))
      ) t), '[]'::jsonb);
end;
$$;

revoke all on function public.stock_reconciliation(bigint) from public, anon;
grant execute on function public.stock_reconciliation(bigint)
  to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 6. Housekeeping
-- ---------------------------------------------------------------------------

do $tighten$
declare f record;
begin
  for f in
    select p.oid::regprocedure as sig
      from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.prorettype = 'trigger'::regtype
  loop
    execute format('revoke all on function %s from public, anon, authenticated', f.sig);
  end loop;
end $tighten$;
