-- Phase A, step 9: the location tree (§7, §8).
--
-- The current shape is exactly two levels deep:
--
--     Warehouse -> Zone -> Bin
--
-- §7 says keep it and make it a general tree, so that a warehouse which is
-- actually laid out as
--
--     Warehouse -> Zone -> Aisle -> Rack -> Shelf -> Bin
--
-- can say so instead of flattening three of those levels into a bin code and
-- hoping everyone reads it the same way. §8 adds the second half: a location
-- has a *type*, so "can this shelf hold ordinary stock?" is a column rather
-- than a convention, and RECEIVING / QC / SHIPPING / TRANSIT / DAMAGED become
-- real places that stock can sit in rather than states invented per screen.
--
-- HOW THIS FITS WHAT IS ALREADY HERE
--
-- `bins` is what `bin_stock` keys on and what every put-away RPC references.
-- Rewriting those onto a new table would be a large change to working code for
-- no gain today, so this migration does not touch them. Instead:
--
--     locations   the tree, canonical for STRUCTURE
--     bins        unchanged, canonical for BIN-LEVEL QUANTITY (bin_stock)
--
-- Every zone and every bin gets a location row, kept in step by triggers, and
-- the location carries a back-pointer (`zone_id` / `bin_id`) so the two can
-- always be lined up. Locations that are not bins — an aisle, a rack, a virtual
-- RECEIVING area — simply have no back-pointer. The sync is one-way on purpose:
-- bins and zones are what the running system writes, so they lead and the tree
-- follows. When Phase B moves put-away onto locations, that migration flips the
-- direction and says so.
--
-- WHAT THIS DOES NOT DO
--
-- It does not move quantity. `stock_units.bin_id` stays null (0061) and
-- `bin_stock` stays the bin-level answer. A tree with no stock hanging off it is
-- still worth having — it is what makes put-away suggestion, pick paths and
-- zone-level counting possible later — but pretending the quantity moved with
-- it would be the double count §5 warns about.

-- ---------------------------------------------------------------------------
-- 1. Location types (§8)
-- ---------------------------------------------------------------------------

-- A table rather than a check constraint, because the point of §8 is that the
-- behaviour of a type is *data*: "can stock be picked from here" is answered by
-- a column, not by a list of codes written into each query that asks.
create table if not exists public.location_types (
  code text primary key,
  name text not null,
  -- The defaults a new location of this type starts with. They are defaults,
  -- not rules: a particular shelf can be marked unpickable without inventing a
  -- type for it.
  default_pickable boolean not null default true,
  default_receivable boolean not null default false,
  default_shipping boolean not null default false,
  default_quarantine boolean not null default false,
  default_virtual boolean not null default false,
  sort_order integer not null default 100,
  constraint location_types_code_check check (code = upper(btrim(code)) and code <> '')
);

alter table public.location_types enable row level security;

drop policy if exists "read location types" on public.location_types;
create policy "read location types" on public.location_types
  for select to authenticated
  using (public.has_permission('warehouse.view')
         or public.has_permission('inventory.view'));

insert into public.location_types
  (code, name, default_pickable, default_receivable, default_shipping,
   default_quarantine, default_virtual, sort_order) values
  ('STORAGE',    '保管',     true,  false, false, false, false, 10),
  ('PICKING',    'ピッキング', true,  false, false, false, false, 20),
  ('RECEIVING',  '入荷',     false, true,  false, false, true,  30),
  ('QC',         '検品',     false, true,  false, false, true,  40),
  ('PACKING',    '梱包',     false, false, false, false, true,  50),
  ('SHIPPING',   '出荷',     false, false, true,  false, true,  60),
  ('QUARANTINE', '隔離',     false, false, false, true,  true,  70),
  ('DAMAGED',    '破損',     false, false, false, true,  true,  80),
  ('RETURN',     '返品',     false, true,  false, false, true,  90),
  ('TRANSIT',    '移動中',   false, false, false, false, true,  100),
  ('VIRTUAL',    '仮想',     false, false, false, false, true,  110)
on conflict (code) do nothing;

-- ---------------------------------------------------------------------------
-- 2. The tree
-- ---------------------------------------------------------------------------

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id),
  warehouse_id bigint not null references public.warehouses (id) on delete cascade,
  -- Null means "directly under the warehouse". The warehouse itself is not a
  -- row here: it already exists, and giving it a second identity in this table
  -- would mean two places to keep its name.
  parent_id bigint,
  code text not null,
  name text,
  location_type text not null default 'STORAGE' references public.location_types (code),
  -- What a scan gun reads off the shelf label. Normalized the same way a
  -- product barcode is (0057), so the one resolver can answer for both.
  barcode text,
  is_active boolean not null default true,
  pickable boolean not null default true,
  receivable boolean not null default false,
  shipping boolean not null default false,
  quarantine boolean not null default false,
  is_virtual boolean not null default false,
  -- Back-pointers to the rows the running system still writes. At most one of
  -- them is set; a rack or a virtual RECEIVING area has neither.
  zone_id bigint unique references public.zones (id) on delete cascade,
  bin_id bigint unique references public.bins (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint locations_code_check check (code = btrim(code) and code <> ''),
  constraint locations_warehouse_code_key unique (warehouse_id, code),
  constraint locations_warehouse_barcode_key unique (warehouse_id, barcode),
  -- The FK target that keeps a parent in the same warehouse as its child.
  constraint locations_warehouse_id_key unique (warehouse_id, id),
  constraint locations_parent_fk foreign key (warehouse_id, parent_id)
    references public.locations (warehouse_id, id) on delete restrict,
  constraint locations_not_own_parent_check check (parent_id is distinct from id),
  constraint locations_single_source_check check (zone_id is null or bin_id is null)
);

create index if not exists locations_parent_idx on public.locations (parent_id);
create index if not exists locations_warehouse_type_idx
  on public.locations (warehouse_id, location_type);

alter table public.locations enable row level security;

drop policy if exists "read locations" on public.locations;
create policy "read locations" on public.locations
  for select to authenticated
  using ((public.has_permission('warehouse.view')
          or public.has_permission('inventory.view'))
         and public.can_access_warehouse(warehouse_id));

-- The FK stops a location pointing at a parent in another warehouse and the
-- check stops it pointing at itself, but neither can see a longer cycle:
-- A -> B -> A satisfies both. Walking up is the only way to know, and the depth
-- limit doubles as the guard against a tree someone has nested absurdly.
create or replace function public.locations_no_cycle()
returns trigger
language plpgsql security definer set search_path = ''
as $$
declare
  v_parent bigint := new.parent_id;
  v_steps integer := 0;
begin
  while v_parent is not null loop
    if v_parent = new.id then
      raise exception 'location % cannot be its own ancestor', new.code;
    end if;
    v_steps := v_steps + 1;
    if v_steps > 32 then
      raise exception 'location tree deeper than 32 levels under %', new.code;
    end if;
    select parent_id into v_parent from public.locations where id = v_parent;
  end loop;
  return new;
end;
$$;

drop trigger if exists locations_no_cycle on public.locations;
create trigger locations_no_cycle
  before insert or update of parent_id on public.locations
  for each row execute function public.locations_no_cycle();

-- ---------------------------------------------------------------------------
-- 3. Keeping the tree in step with zones and bins
-- ---------------------------------------------------------------------------

-- A code is unique within a warehouse so that scanning one, or naming a parent
-- by it, has exactly one answer. That makes a collision possible in principle —
-- a zone and a bin both called "A" — and this sync must never be the reason a
-- warehouse edit fails, so it disambiguates instead of raising. In a warehouse
-- named sensibly this never fires.
create or replace function public.location_code_for(
  p_warehouse_id bigint,
  p_code text,
  p_zone_id bigint,
  p_bin_id bigint
) returns text
language sql stable security definer set search_path = ''
as $$
  select case when exists (
           select 1 from public.locations l
            where l.warehouse_id = p_warehouse_id
              and l.code = btrim(p_code)
              and l.zone_id is distinct from p_zone_id
              and l.bin_id is distinct from p_bin_id)
         then btrim(p_code) || '#' || coalesce(p_bin_id, p_zone_id)::text
         else btrim(p_code) end;
$$;

revoke all on function public.location_code_for(bigint, text, bigint, bigint)
  from public, anon, authenticated;

-- A zone becomes a location directly under the warehouse; a bin becomes one
-- under its zone. Two functions rather than one, because the two rows differ in
-- what they carry (a zone has a name, a bin has a type and an active flag), and
-- both are idempotent on the back-pointer — so renaming a bin moves its location
-- instead of leaving a stale one behind.
create or replace function public.sync_zone_location()
returns trigger
language plpgsql security definer set search_path = ''
as $$
declare
  v_company_id bigint;
begin
  select company_id into v_company_id from public.warehouses where id = new.warehouse_id;

  insert into public.locations (company_id, warehouse_id, code, name,
                                location_type, zone_id)
  values (v_company_id, new.warehouse_id,
          public.location_code_for(new.warehouse_id, new.code, new.id, null),
          new.name, 'STORAGE', new.id)
  on conflict (zone_id) do update
     set code = excluded.code, name = excluded.name, updated_at = now();
  return null;
end;
$$;

drop trigger if exists zones_sync_location on public.zones;
create trigger zones_sync_location
  after insert or update of code, name, warehouse_id on public.zones
  for each row execute function public.sync_zone_location();

create or replace function public.sync_bin_location()
returns trigger
language plpgsql security definer set search_path = ''
as $$
declare
  v_company_id bigint;
  v_parent bigint;
  v_type text;
begin
  select company_id into v_company_id from public.warehouses where id = new.warehouse_id;
  if new.zone_id is not null then
    select id into v_parent from public.locations where zone_id = new.zone_id;
  end if;
  -- `bins.bin_type` is free text today and predates the type vocabulary, so it
  -- is taken as a hint and ignored when it names nothing this schema knows.
  select code into v_type from public.location_types
   where code = upper(btrim(coalesce(new.bin_type, '')));

  insert into public.locations (company_id, warehouse_id, parent_id, code,
                                location_type, is_active, bin_id)
  values (v_company_id, new.warehouse_id, v_parent,
          public.location_code_for(new.warehouse_id, new.code, null, new.id),
          coalesce(v_type, 'STORAGE'), coalesce(new.is_active, true), new.id)
  on conflict (bin_id) do update
     set code = excluded.code,
         parent_id = excluded.parent_id,
         is_active = excluded.is_active,
         updated_at = now();
  return null;
end;
$$;

drop trigger if exists bins_sync_location on public.bins;
create trigger bins_sync_location
  after insert or update of code, zone_id, bin_type, is_active, warehouse_id
  on public.bins
  for each row execute function public.sync_bin_location();

-- Backfill, zones first so the bins have parents to find. Re-runnable: both
-- upserts key on the back-pointer.
do $backfill$
declare z record; b record;
begin
  for z in select * from public.zones loop
    insert into public.locations (company_id, warehouse_id, code, name,
                                  location_type, zone_id)
    select w.company_id, z.warehouse_id, z.code, z.name, 'STORAGE', z.id
      from public.warehouses w where w.id = z.warehouse_id
    on conflict (zone_id) do update
       set code = excluded.code, name = excluded.name, updated_at = now();
  end loop;

  for b in select * from public.bins loop
    insert into public.locations (company_id, warehouse_id, parent_id, code,
                                  location_type, is_active, bin_id)
    select w.company_id, b.warehouse_id,
           (select l.id from public.locations l where l.zone_id = b.zone_id),
           b.code,
           coalesce((select t.code from public.location_types t
                      where t.code = upper(btrim(coalesce(b.bin_type, '')))), 'STORAGE'),
           coalesce(b.is_active, true), b.id
      from public.warehouses w where w.id = b.warehouse_id
    on conflict (bin_id) do update
       set code = excluded.code, parent_id = excluded.parent_id,
           is_active = excluded.is_active, updated_at = now();
  end loop;
end $backfill$;

-- ---------------------------------------------------------------------------
-- 4. Writing the parts of the tree that are not bins
-- ---------------------------------------------------------------------------

create or replace function public.create_location(
  p_warehouse_id bigint,
  p_code text,
  p_name text default null,
  p_location_type text default 'STORAGE',
  p_parent_code text default null,
  p_barcode text default null,
  p_pickable boolean default null,
  p_receivable boolean default null,
  p_shipping boolean default null,
  p_quarantine boolean default null,
  p_is_virtual boolean default null
) returns bigint
language plpgsql security definer set search_path = ''
as $$
declare
  v_company_id bigint;
  v_type record;
  v_parent bigint;
  v_code text := btrim(coalesce(p_code, ''));
  v_id bigint;
begin
  if not public.has_permission('warehouse.manage') then
    raise exception 'not permitted: warehouse.manage required';
  end if;
  if not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  if v_code = '' then
    raise exception 'code is required';
  end if;

  select company_id into v_company_id from public.warehouses where id = p_warehouse_id;
  if v_company_id is null then
    raise exception 'warehouse % not found', p_warehouse_id;
  end if;

  select * into v_type from public.location_types
   where code = upper(btrim(coalesce(p_location_type, 'STORAGE')));
  if v_type is null then
    raise exception 'unknown location type %', p_location_type;
  end if;

  if nullif(btrim(coalesce(p_parent_code, '')), '') is not null then
    select id into v_parent from public.locations
     where warehouse_id = p_warehouse_id and code = btrim(p_parent_code);
    if v_parent is null then
      raise exception 'parent location % not found in this warehouse', p_parent_code;
    end if;
  end if;

  -- The flags default from the type (§8's point) and are overridden only where
  -- the caller actually said something, which is why they arrive nullable.
  insert into public.locations (
    company_id, warehouse_id, parent_id, code, name, location_type, barcode,
    pickable, receivable, shipping, quarantine, is_virtual)
  values (
    v_company_id, p_warehouse_id, v_parent, v_code,
    nullif(btrim(coalesce(p_name, '')), ''), v_type.code,
    public.normalize_barcode(p_barcode),
    coalesce(p_pickable, v_type.default_pickable),
    coalesce(p_receivable, v_type.default_receivable),
    coalesce(p_shipping, v_type.default_shipping),
    coalesce(p_quarantine, v_type.default_quarantine),
    coalesce(p_is_virtual, v_type.default_virtual))
  returning id into v_id;

  perform public.log_audit('warehouse.location_created', 'location', v_id::text,
    p_warehouse_id, jsonb_build_object('code', v_code, 'type', v_type.code,
                                       'parent_code', p_parent_code));
  return v_id;
end;
$$;

revoke all on function public.create_location(
  bigint, text, text, text, text, text, boolean, boolean, boolean, boolean, boolean)
  from public, anon;
grant execute on function public.create_location(
  bigint, text, text, text, text, text, boolean, boolean, boolean, boolean, boolean)
  to authenticated, service_role;

-- Only the fields a caller names are changed; everything else keeps its value,
-- so this can be used to flip one flag without restating the row.
create or replace function public.update_location(
  p_location_id bigint,
  p_name text default null,
  p_location_type text default null,
  p_parent_code text default null,
  p_barcode text default null,
  p_is_active boolean default null,
  p_pickable boolean default null,
  p_receivable boolean default null,
  p_shipping boolean default null,
  p_quarantine boolean default null
) returns boolean
language plpgsql security definer set search_path = ''
as $$
declare
  v_loc record;
  v_parent bigint;
  v_type text;
begin
  if not public.has_permission('warehouse.manage') then
    raise exception 'not permitted: warehouse.manage required';
  end if;
  select * into v_loc from public.locations where id = p_location_id;
  if v_loc is null then
    raise exception 'location % not found', p_location_id;
  end if;
  if not public.can_access_warehouse(v_loc.warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;

  if nullif(btrim(coalesce(p_location_type, '')), '') is not null then
    select code into v_type from public.location_types
     where code = upper(btrim(p_location_type));
    if v_type is null then
      raise exception 'unknown location type %', p_location_type;
    end if;
  end if;

  if nullif(btrim(coalesce(p_parent_code, '')), '') is not null then
    select id into v_parent from public.locations
     where warehouse_id = v_loc.warehouse_id and code = btrim(p_parent_code);
    if v_parent is null then
      raise exception 'parent location % not found in this warehouse', p_parent_code;
    end if;
  end if;

  update public.locations
     set name = coalesce(nullif(btrim(coalesce(p_name, '')), ''), name),
         location_type = coalesce(v_type, location_type),
         parent_id = coalesce(v_parent, parent_id),
         barcode = coalesce(public.normalize_barcode(p_barcode), barcode),
         is_active = coalesce(p_is_active, is_active),
         pickable = coalesce(p_pickable, pickable),
         receivable = coalesce(p_receivable, receivable),
         shipping = coalesce(p_shipping, shipping),
         quarantine = coalesce(p_quarantine, quarantine),
         updated_at = now()
   where id = p_location_id;

  perform public.log_audit('warehouse.location_updated', 'location',
    p_location_id::text, v_loc.warehouse_id,
    jsonb_build_object('type', v_type, 'parent_code', p_parent_code,
                       'is_active', p_is_active));
  return true;
end;
$$;

revoke all on function public.update_location(
  bigint, text, text, text, text, boolean, boolean, boolean, boolean, boolean)
  from public, anon;
grant execute on function public.update_location(
  bigint, text, text, text, text, boolean, boolean, boolean, boolean, boolean)
  to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 5. Reading the tree
-- ---------------------------------------------------------------------------

-- One node with its whole subtree nested inside it. Recursive rather than a
-- recursive CTE: a CTE walks *down* a tree easily but has to be turned inside
-- out to build JSON *up* from the leaves, and the inside-out version is the kind
-- of query that silently loses grandchildren. The depth is bounded by the
-- no-cycle trigger's 32 levels.
--
-- `on_hand` is read from `bin_stock` for nodes that are bins, because that is
-- still the canonical bin-level quantity (0061). Nodes that are not bins report
-- null rather than 0: "no stock here" and "this is not somewhere stock is
-- counted" are different answers.
create or replace function public.location_subtree(
  p_location_id bigint,
  p_include_inactive boolean default false
) returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
declare
  v_node jsonb;
begin
  select jsonb_build_object(
           'id', l.id, 'code', l.code, 'name', l.name,
           'location_type', l.location_type,
           'barcode', l.barcode,
           'is_active', l.is_active,
           'pickable', l.pickable, 'receivable', l.receivable,
           'shipping', l.shipping, 'quarantine', l.quarantine,
           'is_virtual', l.is_virtual,
           'zone_id', l.zone_id, 'bin_id', l.bin_id,
           'on_hand', case when l.bin_id is null then null
                      else (select coalesce(sum(bs.on_hand), 0)
                              from public.bin_stock bs where bs.bin_id = l.bin_id)
                      end,
           'children', coalesce((
             select jsonb_agg(public.location_subtree(c.id, p_include_inactive)
                              order by c.code)
               from public.locations c
              where c.parent_id = l.id
                and (coalesce(p_include_inactive, false) or c.is_active)),
             '[]'::jsonb))
    into v_node
    from public.locations l
   where l.id = p_location_id;
  return v_node;
end;
$$;

revoke all on function public.location_subtree(bigint, boolean)
  from public, anon, authenticated;

-- Nested, not flat: the shape of the answer is the shape of the warehouse, and
-- a client that has to rebuild the hierarchy from parent ids will do it
-- differently on every screen.
create or replace function public.location_tree(
  p_warehouse_id bigint,
  p_include_inactive boolean default false
) returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
declare
  v_all boolean := coalesce(p_include_inactive, false);
begin
  if not (public.has_permission('warehouse.view')
          or public.has_permission('inventory.view')) then
    raise exception 'not permitted: warehouse.view required';
  end if;
  if not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;

  return coalesce((
    select jsonb_agg(public.location_subtree(l.id, v_all) order by l.code)
      from public.locations l
     where l.warehouse_id = p_warehouse_id
       and l.parent_id is null
       and (v_all or l.is_active)), '[]'::jsonb);
end;
$$;

revoke all on function public.location_tree(bigint, boolean) from public, anon;
grant execute on function public.location_tree(bigint, boolean)
  to authenticated, service_role;

create or replace function public.list_location_types()
returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
begin
  if not (public.has_permission('warehouse.view')
          or public.has_permission('inventory.view')) then
    raise exception 'not permitted: warehouse.view required';
  end if;
  return coalesce((
    select jsonb_agg(jsonb_build_object(
             'code', t.code, 'name', t.name,
             'default_pickable', t.default_pickable,
             'default_receivable', t.default_receivable,
             'default_shipping', t.default_shipping,
             'default_quarantine', t.default_quarantine,
             'default_virtual', t.default_virtual)
           order by t.sort_order)
      from public.location_types t), '[]'::jsonb);
end;
$$;

revoke all on function public.list_location_types() from public, anon;
grant execute on function public.list_location_types()
  to authenticated, service_role;

-- §26's one resolver again: the label on a shelf is read with the same gun as
-- the label on a carton, and the operator should not have to know which screen
-- turns which one into an answer. Answered after products and serials, because
-- a location barcode is the rarer scan and an overlap should favour the goods.
create or replace function public.resolve_barcode(p_barcode text)
returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
declare
  v_code text;
  v_raw text := nullif(upper(btrim(coalesce(p_barcode, ''))), '');
  v_result jsonb;
begin
  if not (public.has_permission('product.view')
          or public.has_permission('inventory.view')) then
    raise exception 'not permitted: product.view required';
  end if;

  v_code := public.normalize_barcode(p_barcode);
  if v_code is null then
    return jsonb_build_object('kind', 'unknown', 'barcode', p_barcode);
  end if;

  select jsonb_build_object(
           'kind', 'product',
           'barcode', b.barcode,
           'barcode_type', b.barcode_type,
           'quantity_per_scan', b.quantity_per_scan,
           'uom', (select u.code from public.uoms u where u.id = b.uom_id),
           'base_uom', (select u.code from public.uoms u where u.id = p.base_uom_id),
           'is_primary', b.is_primary,
           'product_id', p.id,
           'jan_code', p.jan_code,
           'sku', p.sku,
           'name', p.name,
           'category', p.category,
           'tracking_mode', p.tracking_mode,
           'status', p.status)
    into v_result
    from public.product_barcodes b
    join public.products p on p.id = b.product_id
   where b.barcode = v_code;
  if v_result is not null then
    return v_result;
  end if;

  select jsonb_build_object(
           'kind', 'serial',
           'barcode', sn.serial_number,
           'serial_id', sn.id,
           'serial_number', sn.serial_number,
           'serial_status', sn.status,
           'lot_id', sn.lot_id,
           'lot_code', (select l.lot_code from public.lots l where l.id = sn.lot_id),
           'expiry_date', (select l.expiry_date from public.lots l where l.id = sn.lot_id),
           'quantity_per_scan', 1,
           'base_uom', (select u.code from public.uoms u where u.id = p.base_uom_id),
           'product_id', p.id,
           'jan_code', p.jan_code,
           'sku', p.sku,
           'name', p.name,
           'category', p.category,
           'tracking_mode', p.tracking_mode,
           'status', p.status)
    into v_result
    from public.serial_numbers sn
    join public.products p on p.id = sn.product_id
   where sn.serial_number in (v_raw, v_code)
   order by case when sn.serial_number = v_raw then 0 else 1 end
   limit 1;
  if v_result is not null then
    return v_result;
  end if;

  -- Scoped, unlike the two above: a product is master data any operator may
  -- look up, but a location belongs to a building, and which buildings this
  -- operator may see is the §37 rule every other warehouse read follows.
  select jsonb_build_object(
           'kind', 'location',
           'barcode', coalesce(l.barcode, l.code),
           'location_id', l.id,
           'code', l.code,
           'name', l.name,
           'location_type', l.location_type,
           'warehouse_id', l.warehouse_id,
           'bin_id', l.bin_id,
           'zone_id', l.zone_id,
           'is_active', l.is_active,
           'pickable', l.pickable,
           'receivable', l.receivable,
           'quarantine', l.quarantine,
           'is_virtual', l.is_virtual)
    into v_result
    from public.locations l
   where (l.barcode = v_code or upper(l.code) in (v_raw, v_code))
     and public.can_access_warehouse(l.warehouse_id)
   order by case when l.barcode = v_code then 0 else 1 end, l.id
   limit 1;

  return coalesce(v_result,
                  jsonb_build_object('kind', 'unknown', 'barcode', v_code));
end;
$$;

revoke all on function public.resolve_barcode(text) from public, anon;
grant execute on function public.resolve_barcode(text) to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 6. Housekeeping
-- ---------------------------------------------------------------------------

do $tighten$
declare f record;
begin
  for f in
    select p.oid::regprocedure as sig
      from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.prorettype = 'trigger'::regtype
  loop
    execute format('revoke all on function %s from public, anon, authenticated', f.sig);
  end loop;
end $tighten$;
