-- Phase A, steps 11-12: Available / Reserved, and Reservation / Allocation
-- (§5, §6).
--
-- §6's flow is the point:
--
--     Sales Order -> Reservation -> Allocation -> Pick -> Pack -> Ship
--
--     Reservation = held for an order
--     Allocation  = which stock will actually be taken
--
--     **Allocationしただけでは在庫を減らさない.**
--
-- That last line is the whole reason these are rows and not a status. 0061
-- already refused to make RESERVED a stock status, because a reserved unit is
-- still physically on hand and still in its own condition — moving the quantity
-- into a RESERVED bucket would count the promise twice, once as a missing unit
-- and once as a claim. So the promise lives here, beside the stock rather than
-- inside it, and `stock_available()` subtracts it. This migration is where 0061's
-- comment — "step 12 subtracts reservations here, and the subtraction belongs
-- *here* so there is one definition of available" — comes true.
--
-- THE TWO LEVELS, AND WHY BOTH
--
--   stock_reservations   the promise: 30 of this product, in this warehouse, for
--                        this order. Says nothing about which 30.
--   stock_allocations    the plan: these particular parcels will supply it —
--                        this lot, in this condition. Says nothing about
--                        anything having moved.
--
-- A reservation with no allocation is a perfectly good state: the promise is made
-- and the picker has not been told which shelf yet. An allocation without a
-- reservation is not, which is why it hangs off one.
--
-- WHAT DELIBERATELY DOES NOT HAPPEN
--
-- **Neither one moves stock.** No ledger entry, no change to `stock_units`. The
-- quantity moves when a pick and a ship say so, which is the only place §37-4's
-- record of what happened can come from.
--
-- **An allocation never blocks a stock movement.** If a shipment consumes stock
-- that was allocated to someone else, the shipment wins: it is what physically
-- happened, and refusing it would be the tail wagging the dog. The allocation
-- becomes over-committed instead, and `over_allocated_stock()` is the read that
-- says so. This is also why `stock_allocations` cascades when a parcel is
-- deleted: an allocation is a plan against a parcel, and the promise (the
-- reservation) outlives the plan.
--
-- **Expiry is honoured by the read, not by a job.** A reservation past its
-- `expires_at` stops counting against availability immediately, because
-- `stock_available()` looks at the clock. `expire_stale_reservations()` exists to
-- tidy the status afterwards, but nothing depends on it having run — a
-- correctness property that needs a cron to hold is not a correctness property.

-- ---------------------------------------------------------------------------
-- 1. The promise
-- ---------------------------------------------------------------------------

create table if not exists public.stock_reservations (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id),
  product_id bigint not null,
  warehouse_id bigint not null references public.warehouses (id) on delete cascade,
  quantity integer not null,
  fulfilled_quantity integer not null default 0,
  -- A loose pair, the same shape `stock_movements` already uses for its
  -- reference: the orders these point at live in tables Phase C builds, and a
  -- hard FK now would either block this migration on them or invent them badly.
  reference_type text not null default 'manual',
  reference_id text,
  status text not null default 'ACTIVE',
  expires_at timestamptz,
  note text,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint stock_reservations_product_fk foreign key (company_id, product_id)
    references public.products (company_id, id) on delete restrict,
  constraint stock_reservations_quantity_check check (quantity > 0),
  constraint stock_reservations_fulfilled_check check (
    fulfilled_quantity >= 0 and fulfilled_quantity <= quantity),
  constraint stock_reservations_status_check check (
    status in ('ACTIVE', 'FULFILLED', 'RELEASED')),
  constraint stock_reservations_reference_check check (
    reference_type in ('sales_order', 'shipment', 'transfer', 'work_order', 'manual'))
);

-- The index availability is read through, so it carries the ACTIVE predicate.
create index if not exists stock_reservations_active_idx
  on public.stock_reservations (warehouse_id, product_id)
  where status = 'ACTIVE';
create index if not exists stock_reservations_reference_idx
  on public.stock_reservations (reference_type, reference_id);

alter table public.stock_reservations enable row level security;

drop policy if exists "read stock reservations" on public.stock_reservations;
create policy "read stock reservations" on public.stock_reservations
  for select to authenticated
  using (public.has_permission('inventory.view')
         and public.can_access_warehouse(warehouse_id));

-- ---------------------------------------------------------------------------
-- 2. The plan
-- ---------------------------------------------------------------------------

create table if not exists public.stock_allocations (
  id bigint generated by default as identity primary key,
  reservation_id bigint not null
    references public.stock_reservations (id) on delete cascade,
  -- Cascade, not restrict: see the header. A parcel that no longer exists cannot
  -- be the plan for anything, and the promise survives it.
  stock_unit_id bigint not null references public.stock_units (id) on delete cascade,
  quantity integer not null,
  note text,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint stock_allocations_quantity_check check (quantity > 0),
  -- One row per pair; a second allocation of the same parcel to the same
  -- reservation is the same allocation with a bigger number.
  constraint stock_allocations_pair_key unique (reservation_id, stock_unit_id)
);

create index if not exists stock_allocations_unit_idx
  on public.stock_allocations (stock_unit_id);

alter table public.stock_allocations enable row level security;

drop policy if exists "read stock allocations" on public.stock_allocations;
create policy "read stock allocations" on public.stock_allocations
  for select to authenticated
  using (public.has_permission('inventory.view')
         and exists (select 1 from public.stock_reservations r
                      where r.id = stock_allocations.reservation_id
                        and public.can_access_warehouse(r.warehouse_id)));

-- Three things no check constraint can see, because each one needs other rows.
create or replace function public.stock_allocation_fits()
returns trigger
language plpgsql security definer set search_path = ''
as $$
declare
  v_res record;
  v_unit record;
  v_allocated integer;
begin
  select * into v_res from public.stock_reservations where id = new.reservation_id;
  select * into v_unit from public.stock_units where id = new.stock_unit_id;

  -- 1. The parcel has to be able to satisfy this reservation at all.
  if v_unit.product_id <> v_res.product_id
     or v_unit.warehouse_id <> v_res.warehouse_id then
    raise exception
      'stock unit % is not the same product and warehouse as reservation %',
      new.stock_unit_id, new.reservation_id;
  end if;
  if v_res.status <> 'ACTIVE' then
    raise exception 'reservation % is %', new.reservation_id, v_res.status;
  end if;

  -- 2. A parcel cannot be promised to more reservations than it holds. This is
  --    the check that keeps two orders from being told they both have the last
  --    box; it is enforced at allocation time because that is when the claim is
  --    made, not when the stock leaves.
  select coalesce(sum(a.quantity), 0) into v_allocated
    from public.stock_allocations a
   where a.stock_unit_id = new.stock_unit_id
     and (tg_op = 'INSERT' or a.id <> new.id);
  if v_allocated + new.quantity > v_unit.quantity then
    raise exception
      'stock unit % holds % and already has % allocated; cannot allocate % more',
      new.stock_unit_id, v_unit.quantity, v_allocated, new.quantity;
  end if;

  -- 3. Nor can a reservation be over-supplied: allocating 40 against a promise
  --    of 30 means someone has lost track of which order they are picking for.
  select coalesce(sum(a.quantity), 0) into v_allocated
    from public.stock_allocations a
   where a.reservation_id = new.reservation_id
     and (tg_op = 'INSERT' or a.id <> new.id);
  if v_allocated + new.quantity > v_res.quantity then
    raise exception
      'reservation % is for % and already has % allocated; cannot allocate % more',
      new.reservation_id, v_res.quantity, v_allocated, new.quantity;
  end if;

  return new;
end;
$$;

drop trigger if exists stock_allocations_fits on public.stock_allocations;
create trigger stock_allocations_fits
  before insert or update of quantity, stock_unit_id, reservation_id
  on public.stock_allocations
  for each row execute function public.stock_allocation_fits();

-- ---------------------------------------------------------------------------
-- 3. Available, finally complete (§5, step 11)
-- ---------------------------------------------------------------------------

-- What is actually promised away right now. Expiry is read from the clock, so a
-- lapsed reservation stops holding stock the moment it lapses, whether or not
-- anything has tidied its status.
create or replace function public.stock_reserved(
  p_product_id bigint,
  p_warehouse_id bigint default null
) returns integer
language sql stable security definer set search_path = ''
as $$
  select coalesce(sum(r.quantity - r.fulfilled_quantity), 0)::integer
    from public.stock_reservations r
   where r.product_id = p_product_id
     and r.status = 'ACTIVE'
     and (r.expires_at is null or r.expires_at > now())
     and (p_warehouse_id is null or r.warehouse_id = p_warehouse_id)
     and public.can_access_warehouse(r.warehouse_id);
$$;

revoke all on function public.stock_reserved(bigint, bigint) from public, anon;
grant execute on function public.stock_reserved(bigint, bigint)
  to authenticated, service_role;

-- §5's formula, whole at last:
--
--     Available = on-hand in a usable condition  -  Reserved
--
-- Redefined rather than wrapped, so there stays exactly one definition of
-- "available" and every existing caller — `warehouse_product_settings`,
-- `replenishment_suggestions`, `move_stock_status` — gets the complete answer
-- without being touched.
--
-- It is NOT floored at zero. A negative available means more has been promised
-- than can be shipped, and that is worth seeing rather than rounding away;
-- callers that ask "is there enough for N" compare against N and are unaffected.
create or replace function public.stock_available(
  p_product_id bigint,
  p_warehouse_id bigint default null
) returns integer
language sql stable security definer set search_path = ''
as $$
  select (coalesce((
            select sum(su.quantity)
              from public.stock_units su
              join public.stock_statuses st on st.id = su.status_id
             where su.product_id = p_product_id
               and st.counts_available
               and (p_warehouse_id is null or su.warehouse_id = p_warehouse_id)
               and public.can_access_warehouse(su.warehouse_id)), 0)
          - public.stock_reserved(p_product_id, p_warehouse_id))::integer;
$$;

revoke all on function public.stock_available(bigint, bigint) from public, anon;
grant execute on function public.stock_available(bigint, bigint)
  to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 4. Making and unmaking a promise
-- ---------------------------------------------------------------------------

create or replace function public.reserve_stock(
  p_product_id bigint,
  p_warehouse_id bigint,
  p_quantity integer,
  p_reference_type text default 'manual',
  p_reference_id text default null,
  p_expires_at timestamptz default null,
  p_note text default null
) returns jsonb
language plpgsql security definer set search_path = ''
as $$
declare
  v_company_id bigint;
  v_type text := lower(btrim(coalesce(p_reference_type, 'manual')));
  v_available integer;
  v_id bigint;
begin
  if not (public.has_permission('sales_order.manage')
          or public.has_permission('inventory.adjust')) then
    raise exception 'not permitted: inventory.adjust required';
  end if;
  if not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  if coalesce(p_quantity, 0) <= 0 then
    raise exception 'quantity must be greater than zero';
  end if;
  if v_type not in ('sales_order', 'shipment', 'transfer', 'work_order', 'manual') then
    raise exception 'unknown reference_type %', p_reference_type;
  end if;

  select company_id into v_company_id from public.products where id = p_product_id;
  if v_company_id is null then
    raise exception 'product % not found', p_product_id;
  end if;

  -- The over-promise guard, and the reason `available` had to be right before
  -- this step could exist: the comparison is against usable stock less what is
  -- already promised, not against on-hand.
  v_available := public.stock_available(p_product_id, p_warehouse_id);
  if v_available < p_quantity then
    raise exception 'only % available, cannot reserve %', v_available, p_quantity;
  end if;

  insert into public.stock_reservations (
    company_id, product_id, warehouse_id, quantity, reference_type,
    reference_id, expires_at, note)
  values (v_company_id, p_product_id, p_warehouse_id, p_quantity, v_type,
          nullif(btrim(coalesce(p_reference_id, '')), ''), p_expires_at,
          nullif(btrim(coalesce(p_note, '')), ''))
  returning id into v_id;

  perform public.log_audit('inventory.reserved', 'stock_reservation', v_id::text,
    p_warehouse_id,
    jsonb_build_object('product_id', p_product_id, 'quantity', p_quantity,
                       'reference_type', v_type, 'reference_id', p_reference_id));

  return jsonb_build_object(
    'reservation_id', v_id,
    'product_id', p_product_id,
    'warehouse_id', p_warehouse_id,
    'quantity', p_quantity,
    'reserved', public.stock_reserved(p_product_id, p_warehouse_id),
    'available', public.stock_available(p_product_id, p_warehouse_id));
end;
$$;

revoke all on function public.reserve_stock(
  bigint, bigint, integer, text, text, timestamptz, text) from public, anon;
grant execute on function public.reserve_stock(
  bigint, bigint, integer, text, text, timestamptz, text)
  to authenticated, service_role;

-- Releasing is not deleting. The row stays with `status = 'RELEASED'` so the
-- audit trail has something to point at, and it stops counting against
-- availability because only ACTIVE rows ever did. Its allocations go, because a
-- plan for a promise nobody is keeping is noise.
create or replace function public.release_reservation(
  p_reservation_id bigint,
  p_note text default null
) returns jsonb
language plpgsql security definer set search_path = ''
as $$
declare
  v_res record;
begin
  if not (public.has_permission('sales_order.manage')
          or public.has_permission('inventory.adjust')) then
    raise exception 'not permitted: inventory.adjust required';
  end if;
  select * into v_res from public.stock_reservations where id = p_reservation_id;
  if v_res is null then
    raise exception 'reservation % not found', p_reservation_id;
  end if;
  if not public.can_access_warehouse(v_res.warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  if v_res.status <> 'ACTIVE' then
    raise exception 'reservation % is already %', p_reservation_id, v_res.status;
  end if;

  delete from public.stock_allocations where reservation_id = p_reservation_id;
  update public.stock_reservations
     set status = 'RELEASED',
         note = coalesce(nullif(btrim(coalesce(p_note, '')), ''), note),
         updated_at = now()
   where id = p_reservation_id;

  perform public.log_audit('inventory.reservation_released', 'stock_reservation',
    p_reservation_id::text, v_res.warehouse_id,
    jsonb_build_object('quantity', v_res.quantity, 'note', p_note));

  return jsonb_build_object(
    'reservation_id', p_reservation_id, 'status', 'RELEASED',
    'available', public.stock_available(v_res.product_id, v_res.warehouse_id));
end;
$$;

revoke all on function public.release_reservation(bigint, text) from public, anon;
grant execute on function public.release_reservation(bigint, text)
  to authenticated, service_role;

-- Called when stock has actually left against this promise. It does NOT move
-- stock: the shipment's own movement did that, and doing it here as well is the
-- double count §5 warns about. What this records is that the promise has been
-- kept, so it stops holding the quantity it was holding.
create or replace function public.fulfil_reservation(
  p_reservation_id bigint,
  p_quantity integer default null
) returns jsonb
language plpgsql security definer set search_path = ''
as $$
declare
  v_res record;
  v_add integer;
  v_total integer;
begin
  if not (public.has_permission('sales_order.manage')
          or public.has_permission('inventory.adjust')
          or public.has_permission('ship.complete')) then
    raise exception 'not permitted: inventory.adjust required';
  end if;
  select * into v_res from public.stock_reservations where id = p_reservation_id;
  if v_res is null then
    raise exception 'reservation % not found', p_reservation_id;
  end if;
  if not public.can_access_warehouse(v_res.warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  if v_res.status <> 'ACTIVE' then
    raise exception 'reservation % is %', p_reservation_id, v_res.status;
  end if;

  -- No quantity means "all of it", which is the common case at shipping time.
  v_add := coalesce(p_quantity, v_res.quantity - v_res.fulfilled_quantity);
  if v_add <= 0 then
    raise exception 'quantity must be greater than zero';
  end if;
  v_total := v_res.fulfilled_quantity + v_add;
  if v_total > v_res.quantity then
    raise exception 'reservation % is for % and % is already fulfilled',
      p_reservation_id, v_res.quantity, v_res.fulfilled_quantity;
  end if;

  update public.stock_reservations
     set fulfilled_quantity = v_total,
         status = case when v_total = quantity then 'FULFILLED' else status end,
         updated_at = now()
   where id = p_reservation_id;
  -- A fully kept promise has nothing left to plan for.
  if v_total = v_res.quantity then
    delete from public.stock_allocations where reservation_id = p_reservation_id;
  end if;

  perform public.log_audit('inventory.reservation_fulfilled', 'stock_reservation',
    p_reservation_id::text, v_res.warehouse_id,
    jsonb_build_object('quantity', v_add, 'fulfilled_total', v_total));

  return jsonb_build_object(
    'reservation_id', p_reservation_id,
    'fulfilled_quantity', v_total,
    'status', case when v_total = v_res.quantity then 'FULFILLED' else 'ACTIVE' end,
    'available', public.stock_available(v_res.product_id, v_res.warehouse_id));
end;
$$;

revoke all on function public.fulfil_reservation(bigint, integer) from public, anon;
grant execute on function public.fulfil_reservation(bigint, integer)
  to authenticated, service_role;

-- Tidies the status of reservations the clock has already stopped counting.
-- service_role only: this is housekeeping for a scheduled call, not an operator
-- action, and nothing's correctness waits on it.
create or replace function public.expire_stale_reservations()
returns integer
language plpgsql security definer set search_path = ''
as $$
declare
  v_count integer;
begin
  with expired as (
    update public.stock_reservations
       set status = 'RELEASED', updated_at = now()
     where status = 'ACTIVE' and expires_at is not null and expires_at <= now()
    returning id)
  select count(*) into v_count from expired;
  delete from public.stock_allocations a
   using public.stock_reservations r
   where r.id = a.reservation_id and r.status <> 'ACTIVE';
  return v_count;
end;
$$;

revoke all on function public.expire_stale_reservations()
  from public, anon, authenticated;
grant execute on function public.expire_stale_reservations() to service_role;

-- ---------------------------------------------------------------------------
-- 5. Choosing which stock will supply it
-- ---------------------------------------------------------------------------

create or replace function public.allocate_stock(
  p_reservation_id bigint,
  p_quantity integer default null,
  p_stock_unit_id bigint default null
) returns jsonb
language plpgsql security definer set search_path = ''
as $$
declare
  v_res record;
  v_left integer;
  v_take integer;
  v_row record;
  v_made integer := 0;
begin
  if not (public.has_permission('pick.confirm')
          or public.has_permission('inventory.adjust')) then
    raise exception 'not permitted: inventory.adjust required';
  end if;
  select * into v_res from public.stock_reservations where id = p_reservation_id;
  if v_res is null then
    raise exception 'reservation % not found', p_reservation_id;
  end if;
  if not public.can_access_warehouse(v_res.warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;

  -- No quantity means "whatever is still unallocated on this reservation".
  v_left := coalesce(p_quantity,
    v_res.quantity - coalesce((select sum(a.quantity) from public.stock_allocations a
                                where a.reservation_id = p_reservation_id), 0));
  if v_left <= 0 then
    raise exception 'nothing left to allocate on reservation %', p_reservation_id;
  end if;

  -- Soonest expiry first, then the parcel with least left, so a part-used lot is
  -- finished rather than another one opened. Only available-status parcels, and
  -- only what is not already promised to someone else.
  for v_row in
    select su.id, su.quantity
             - coalesce((select sum(a.quantity) from public.stock_allocations a
                          where a.stock_unit_id = su.id), 0) as free
      from public.stock_units su
      join public.stock_statuses st on st.id = su.status_id
      left join public.lots l on l.id = su.lot_id
     where su.product_id = v_res.product_id
       and su.warehouse_id = v_res.warehouse_id
       and st.counts_available
       and (p_stock_unit_id is null or su.id = p_stock_unit_id)
     order by l.expiry_date asc nulls last, su.quantity, su.id
  loop
    exit when v_left <= 0;
    continue when v_row.free <= 0;
    v_take := least(v_left, v_row.free);

    insert into public.stock_allocations as sa (reservation_id, stock_unit_id, quantity)
    values (p_reservation_id, v_row.id, v_take)
    on conflict (reservation_id, stock_unit_id) do update
       set quantity = sa.quantity + excluded.quantity, updated_at = now();
    v_left := v_left - v_take;
    v_made := v_made + v_take;
  end loop;

  if v_made > 0 then
    perform public.log_audit('inventory.allocated', 'stock_reservation',
      p_reservation_id::text, v_res.warehouse_id,
      jsonb_build_object('allocated', v_made, 'short', v_left));
  end if;

  -- Reports the shortfall rather than raising on it: "I could only find 20 of
  -- the 30" is an answer a picking screen can act on, and rolling the 20 back
  -- would help nobody.
  return jsonb_build_object(
    'reservation_id', p_reservation_id,
    'allocated', v_made,
    'short', v_left,
    'allocations', public.reservation_allocations(p_reservation_id));
end;
$$;

revoke all on function public.allocate_stock(bigint, integer, bigint)
  from public, anon;
grant execute on function public.allocate_stock(bigint, integer, bigint)
  to authenticated, service_role;

create or replace function public.release_allocation(p_allocation_id bigint)
returns boolean
language plpgsql security definer set search_path = ''
as $$
declare
  v_warehouse_id bigint;
  v_reservation_id bigint;
begin
  if not (public.has_permission('pick.confirm')
          or public.has_permission('inventory.adjust')) then
    raise exception 'not permitted: inventory.adjust required';
  end if;
  select r.warehouse_id, r.id into v_warehouse_id, v_reservation_id
    from public.stock_allocations a
    join public.stock_reservations r on r.id = a.reservation_id
   where a.id = p_allocation_id;
  if v_warehouse_id is null then
    raise exception 'allocation % not found', p_allocation_id;
  end if;
  if not public.can_access_warehouse(v_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;

  delete from public.stock_allocations where id = p_allocation_id;
  perform public.log_audit('inventory.allocation_released', 'stock_reservation',
    v_reservation_id::text, v_warehouse_id,
    jsonb_build_object('allocation_id', p_allocation_id));
  return true;
end;
$$;

revoke all on function public.release_allocation(bigint) from public, anon;
grant execute on function public.release_allocation(bigint)
  to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 6. Reading it
-- ---------------------------------------------------------------------------

-- Which parcels are planned for one promise, with the lot and condition a picker
-- needs to find them.
create or replace function public.reservation_allocations(p_reservation_id bigint)
returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
begin
  return coalesce((
    select jsonb_agg(jsonb_build_object(
             'allocation_id', a.id,
             'stock_unit_id', a.stock_unit_id,
             'quantity', a.quantity,
             'status', st.code,
             'lot_id', su.lot_id,
             'lot_code', (select l.lot_code from public.lots l where l.id = su.lot_id),
             'expiry_date', (select l.expiry_date from public.lots l where l.id = su.lot_id),
             'bin_id', su.bin_id)
           order by a.id)
      from public.stock_allocations a
      join public.stock_units su on su.id = a.stock_unit_id
      join public.stock_statuses st on st.id = su.status_id
     where a.reservation_id = p_reservation_id), '[]'::jsonb);
end;
$$;

revoke all on function public.reservation_allocations(bigint)
  from public, anon, authenticated;

create or replace function public.list_reservations(
  p_warehouse_id bigint default null,
  p_product_id bigint default null,
  p_status text default 'ACTIVE'
) returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
declare
  v_status text := nullif(upper(btrim(coalesce(p_status, ''))), '');
begin
  if not public.has_permission('inventory.view') then
    raise exception 'not permitted: inventory.view required';
  end if;
  if p_warehouse_id is not null and not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;

  return coalesce((
    select jsonb_agg(jsonb_build_object(
             'id', r.id,
             'product_id', r.product_id,
             'jan_code', p.jan_code,
             'sku', p.sku,
             'product_name', p.name,
             'warehouse_id', r.warehouse_id,
             'warehouse_name', w.name,
             'quantity', r.quantity,
             'fulfilled_quantity', r.fulfilled_quantity,
             'allocated_quantity',
               coalesce((select sum(a.quantity) from public.stock_allocations a
                          where a.reservation_id = r.id), 0),
             'reference_type', r.reference_type,
             'reference_id', r.reference_id,
             'status', r.status,
             'expires_at', r.expires_at,
             -- Distinct from `status`: the row still says ACTIVE, and the clock
             -- is why it no longer holds anything.
             'is_expired', r.expires_at is not null and r.expires_at <= now(),
             'note', r.note,
             'created_at', r.created_at,
             'allocations', public.reservation_allocations(r.id))
           order by r.created_at desc)
      from public.stock_reservations r
      join public.products p on p.id = r.product_id
      join public.warehouses w on w.id = r.warehouse_id
     where (p_warehouse_id is null or r.warehouse_id = p_warehouse_id)
       and (p_product_id is null or r.product_id = p_product_id)
       and (v_status is null or r.status = v_status)
       and public.can_access_warehouse(r.warehouse_id)), '[]'::jsonb);
end;
$$;

revoke all on function public.list_reservations(bigint, bigint, text)
  from public, anon;
grant execute on function public.list_reservations(bigint, bigint, text)
  to authenticated, service_role;

-- The read that makes "an allocation never blocks a stock movement" safe to
-- mean. Every row here is a parcel promised to more than it now holds, which
-- means stock left after it was allocated. Empty is the healthy state.
create or replace function public.over_allocated_stock(
  p_warehouse_id bigint default null
) returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
begin
  if not public.has_permission('inventory.view') then
    raise exception 'not permitted: inventory.view required';
  end if;
  if p_warehouse_id is not null and not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;

  return coalesce((
    select jsonb_agg(row_to_json(t)::jsonb order by t.over desc)
      from (
        select su.id as stock_unit_id,
               su.warehouse_id,
               su.product_id,
               p.name as product_name,
               st.code as status,
               su.quantity,
               sum(a.quantity)::integer as allocated,
               (sum(a.quantity) - su.quantity)::integer as over
          from public.stock_allocations a
          join public.stock_units su on su.id = a.stock_unit_id
          join public.stock_statuses st on st.id = su.status_id
          join public.products p on p.id = su.product_id
         where (p_warehouse_id is null or su.warehouse_id = p_warehouse_id)
           and public.can_access_warehouse(su.warehouse_id)
         group by su.id, su.warehouse_id, su.product_id, p.name, st.code, su.quantity
        having sum(a.quantity) > su.quantity
      ) t), '[]'::jsonb);
end;
$$;

revoke all on function public.over_allocated_stock(bigint) from public, anon;
grant execute on function public.over_allocated_stock(bigint)
  to authenticated, service_role;

-- One product in one warehouse, the four numbers §5 asks to keep apart.
create or replace function public.stock_position(
  p_product_id bigint,
  p_warehouse_id bigint default null
) returns jsonb
language plpgsql stable security definer set search_path = ''
as $$
begin
  if not public.has_permission('inventory.view') then
    raise exception 'not permitted: inventory.view required';
  end if;
  if p_warehouse_id is not null and not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  return jsonb_build_object(
    'product_id', p_product_id,
    'warehouse_id', p_warehouse_id,
    'on_hand', public.stock_on_hand(p_product_id, p_warehouse_id),
    'reserved', public.stock_reserved(p_product_id, p_warehouse_id),
    'available', public.stock_available(p_product_id, p_warehouse_id),
    'allocated', coalesce((
      select sum(a.quantity)::integer
        from public.stock_allocations a
        join public.stock_reservations r on r.id = a.reservation_id
       where r.product_id = p_product_id
         and (p_warehouse_id is null or r.warehouse_id = p_warehouse_id)
         and public.can_access_warehouse(r.warehouse_id)), 0),
    'by_status', public.stock_status_breakdown(p_product_id, p_warehouse_id));
end;
$$;

revoke all on function public.stock_position(bigint, bigint) from public, anon;
grant execute on function public.stock_position(bigint, bigint)
  to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 7. Housekeeping
-- ---------------------------------------------------------------------------

do $tighten$
declare f record;
begin
  for f in
    select p.oid::regprocedure as sig
      from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.prorettype = 'trigger'::regtype
  loop
    execute format('revoke all on function %s from public, anon, authenticated', f.sig);
  end loop;
end $tighten$;
