-- 0077 — Phase C: §15's wave, and the walk it exists to save
--
-- §15 lists wave picking, batch picking, zone picking, priority and operator
-- assignment as what the pick-task shape should be able to grow into. A wave
-- that is only a folder for pick lists would satisfy the word and none of the
-- point, so the substance of this migration is `wave_pick_plan`:
--
--     Three orders, each wanting 10 of the same product from the same rack.
--     Three pick lists  -> three walks to that rack, 30 units carried in three
--                          trips.
--     One wave          -> one line on the picker's sheet: "R-01-A, lot L-B,
--                          take 30", and the wave knows which task each unit
--                          belongs to.
--
-- That aggregation is the entire economics of wave picking, and it is a read —
-- the same choice 0074 made for `pick_candidates` and 0069 for
-- `putaway_suggestions`. Advice lives in a function you can call again; what the
-- picker actually took lives in `pick_items`.
--
-- THE HARD PART, AND HOW IT IS HANDLED
--
-- Aggregating suggestions across tasks cannot just call `pick_candidates` per
-- task and add the results up: each call would offer the same parcel to every
-- task, and the sheet would tell one picker to take 30 from a box holding 10.
-- So the plan walks the tasks in order and carries a map of what earlier tasks
-- have already claimed, subtracting it as it goes. A task that cannot be covered
-- is reported short rather than silently rounded — "I can find 20 of the 30" is
-- something a picker can act on, and a wave that quietly promised the missing 10
-- is not.
--
-- WHAT A WAVE DOES NOT DO
--
-- It does not move stock, reserve anything, or change what a pick list means. A
-- wave's lists are ordinary pick lists: `record_pick_item` and
-- `complete_pick_list` work on them unchanged, and a list can be finished on its
-- own whether or not its wave is. Cancelling a wave releases its lists (nothing
-- has moved, so there is nothing to reverse) and leaves any picking already
-- recorded in place, because that picking happened.

-- ---------------------------------------------------------------------------
-- 1. The wave
-- ---------------------------------------------------------------------------

create table if not exists public.pick_waves (
  id bigint generated by default as identity primary key,
  warehouse_id bigint not null references public.warehouses (id) on delete cascade,
  code text,
  status text not null default 'OPEN',
  -- §15's 作業員割当. Nullable: a wave can be built before anyone is free to
  -- walk it, which is most of why you would build one in advance.
  assigned_to uuid references public.app_users (id),
  -- Lower first, the same direction `warehouse_products.pick_priority` runs.
  priority integer not null default 100,
  note text,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  constraint pick_waves_status_check
    check (status in ('OPEN', 'PICKING', 'DONE', 'CANCELLED'))
);

create index if not exists pick_waves_warehouse_idx
  on public.pick_waves (warehouse_id, status);

create unique index if not exists pick_waves_code_key
  on public.pick_waves (warehouse_id, code) where code is not null;

alter table public.pick_waves enable row level security;

-- Scoped by warehouse and nothing else, matching `pick_lists_read`: there is no
-- `pick.view` permission, and a wave is no more sensitive than the lists in it.
drop policy if exists pick_waves_read on public.pick_waves;
create policy pick_waves_read on public.pick_waves
  for select to authenticated
  using (public.can_access_warehouse(warehouse_id));

-- A list belongs to at most one wave. Set null rather than cascade: deleting a
-- wave must not take the record of what was picked with it.
alter table public.pick_lists
  add column if not exists wave_id bigint references public.pick_waves (id)
    on delete set null;

create index if not exists pick_lists_wave_idx
  on public.pick_lists (wave_id) where wave_id is not null;

-- ---------------------------------------------------------------------------
-- 2. Building and running one
-- ---------------------------------------------------------------------------

create or replace function public.create_pick_wave(
  p_warehouse_id bigint,
  p_shipment_plan_ids bigint[],
  p_code text default null,
  p_assigned_to uuid default null,
  p_priority integer default 100,
  p_note text default null
) returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  v_wave bigint;
  v_plan bigint;
  v_list bigint;
  v_lists bigint[] := '{}';
  v_skipped jsonb := '[]'::jsonb;
  v_plan_warehouse bigint;
  v_plan_status text;
begin
  if not public.has_permission('pick.confirm') then
    raise exception 'not permitted: pick.confirm required';
  end if;
  if not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  if p_shipment_plan_ids is null or array_length(p_shipment_plan_ids, 1) is null then
    raise exception 'a wave needs at least one shipment';
  end if;

  insert into public.pick_waves (
    warehouse_id, code, assigned_to, priority, note)
  values (p_warehouse_id, nullif(btrim(coalesce(p_code, '')), ''), p_assigned_to,
          coalesce(p_priority, 100), nullif(btrim(coalesce(p_note, '')), ''))
  returning id into v_wave;

  if p_code is null or btrim(p_code) = '' then
    update public.pick_waves set code = 'WV-' || lpad(v_wave::text, 6, '0')
     where id = v_wave;
  end if;

  foreach v_plan in array p_shipment_plan_ids loop
    select coalesce(warehouse_id, public.default_warehouse_id()), status
      into v_plan_warehouse, v_plan_status
      from public.shipment_plans where id = v_plan;

    -- Reported, not raised: one closed shipment in a list of twenty should not
    -- make the operator rebuild the whole wave.
    if v_plan_status is null then
      v_skipped := v_skipped || jsonb_build_object(
        'shipment_plan_id', v_plan, 'reason', 'not_found');
      continue;
    end if;
    if v_plan_warehouse is distinct from p_warehouse_id then
      v_skipped := v_skipped || jsonb_build_object(
        'shipment_plan_id', v_plan, 'reason', 'other_warehouse');
      continue;
    end if;
    if v_plan_status in ('shipped', 'cancelled') then
      v_skipped := v_skipped || jsonb_build_object(
        'shipment_plan_id', v_plan, 'reason', 'already_' || v_plan_status);
      continue;
    end if;

    -- `start_pick_list` is idempotent (0018), so a shipment already being picked
    -- joins the wave with the list it already has rather than getting a second.
    v_list := public.start_pick_list(v_plan);
    update public.pick_lists set wave_id = v_wave
     where id = v_list and status = 'PICKING';
    v_lists := v_lists || v_list;
  end loop;

  if array_length(v_lists, 1) is null then
    raise exception 'none of those shipments could be picked: %', v_skipped;
  end if;

  perform public.log_audit('pick_wave.created', 'pick_wave', v_wave::text,
    p_warehouse_id, jsonb_build_object(
      'lists', to_jsonb(v_lists), 'skipped', v_skipped,
      'assigned_to', p_assigned_to));

  return jsonb_build_object(
    'wave_id', v_wave,
    'code', (select code from public.pick_waves where id = v_wave),
    'pick_list_ids', to_jsonb(v_lists),
    'skipped', v_skipped);
end;
$$;

revoke all on function public.create_pick_wave(bigint, bigint[], text, uuid, integer, text)
  from public, anon;
grant execute on function public.create_pick_wave(bigint, bigint[], text, uuid, integer, text)
  to authenticated, service_role;

create or replace function public.assign_pick_wave(
  p_wave_id bigint,
  p_user_id uuid default null
) returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  v_warehouse bigint;
  v_status text;
begin
  if not public.has_permission('pick.confirm') then
    raise exception 'not permitted: pick.confirm required';
  end if;
  select warehouse_id, status into v_warehouse, v_status
    from public.pick_waves where id = p_wave_id;
  if v_warehouse is null then raise exception 'wave % not found', p_wave_id; end if;
  if not public.can_access_warehouse(v_warehouse) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  if v_status in ('DONE', 'CANCELLED') then
    raise exception 'wave % is %', p_wave_id, v_status;
  end if;

  -- Null un-assigns, which is how a wave goes back in the pool when someone
  -- hands it over.
  update public.pick_waves
     set assigned_to = p_user_id,
         status = case when p_user_id is not null and status = 'OPEN'
                       then 'PICKING' else status end,
         started_at = case when p_user_id is not null and started_at is null
                          then now() else started_at end
   where id = p_wave_id;

  perform public.log_audit('pick_wave.assigned', 'pick_wave', p_wave_id::text,
    v_warehouse, jsonb_build_object('assigned_to', p_user_id));

  return public.pick_wave_detail(p_wave_id);
end;
$$;

revoke all on function public.assign_pick_wave(bigint, uuid) from public, anon;
grant execute on function public.assign_pick_wave(bigint, uuid)
  to authenticated, service_role;

create or replace function public.complete_pick_wave(p_wave_id bigint)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  v_warehouse bigint;
  v_status text;
  v_list bigint;
  v_closed integer := 0;
  v_pending integer;
begin
  if not public.has_permission('pick.confirm') then
    raise exception 'not permitted: pick.confirm required';
  end if;
  select warehouse_id, status into v_warehouse, v_status
    from public.pick_waves where id = p_wave_id;
  if v_warehouse is null then raise exception 'wave % not found', p_wave_id; end if;
  if not public.can_access_warehouse(v_warehouse) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  if v_status in ('DONE', 'CANCELLED') then
    raise exception 'wave % is already %', p_wave_id, v_status;
  end if;

  -- Same refusal `complete_pick_list` makes, said once for the whole wave: an
  -- unpicked line is not a line picked as zero, and only the picker knows which.
  select count(*) into v_pending
    from public.pick_tasks t
    join public.pick_lists l on l.id = t.pick_list_id
   where l.wave_id = p_wave_id and l.status = 'PICKING'
     and t.picked_quantity is null;
  if v_pending > 0 then
    raise exception 'wave % still has % unpicked line(s)', p_wave_id, v_pending;
  end if;

  for v_list in
    select id from public.pick_lists
     where wave_id = p_wave_id and status = 'PICKING' order by id
  loop
    perform public.complete_pick_list(v_list);
    v_closed := v_closed + 1;
  end loop;

  update public.pick_waves
     set status = 'DONE', completed_at = now()
   where id = p_wave_id;

  perform public.log_audit('pick_wave.completed', 'pick_wave', p_wave_id::text,
    v_warehouse, jsonb_build_object('lists_closed', v_closed));

  return jsonb_build_object(
    'wave_id', p_wave_id, 'status', 'DONE', 'lists_closed', v_closed);
end;
$$;

revoke all on function public.complete_pick_wave(bigint) from public, anon;
grant execute on function public.complete_pick_wave(bigint)
  to authenticated, service_role;

create or replace function public.cancel_pick_wave(p_wave_id bigint)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  v_warehouse bigint;
  v_status text;
  v_list bigint;
  v_released integer := 0;
begin
  if not public.has_permission('pick.confirm') then
    raise exception 'not permitted: pick.confirm required';
  end if;
  select warehouse_id, status into v_warehouse, v_status
    from public.pick_waves where id = p_wave_id;
  if v_warehouse is null then raise exception 'wave % not found', p_wave_id; end if;
  if not public.can_access_warehouse(v_warehouse) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  if v_status = 'CANCELLED' then
    return jsonb_build_object('wave_id', p_wave_id, 'status', 'CANCELLED');
  end if;

  -- Nothing has moved, so there is nothing to reverse: the lists are released
  -- and any picking already recorded stays recorded, because it happened.
  for v_list in
    select id from public.pick_lists
     where wave_id = p_wave_id and status = 'PICKING' order by id
  loop
    perform public.cancel_pick_list(v_list);
    v_released := v_released + 1;
  end loop;

  update public.pick_waves set status = 'CANCELLED' where id = p_wave_id;

  perform public.log_audit('pick_wave.cancelled', 'pick_wave', p_wave_id::text,
    v_warehouse, jsonb_build_object('was', v_status, 'lists_released', v_released));

  return jsonb_build_object(
    'wave_id', p_wave_id, 'status', 'CANCELLED', 'lists_released', v_released);
end;
$$;

revoke all on function public.cancel_pick_wave(bigint) from public, anon;
grant execute on function public.cancel_pick_wave(bigint)
  to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 3. The walk — one line per place, not one line per order
-- ---------------------------------------------------------------------------

create or replace function public.wave_pick_plan(p_wave_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path to ''
as $$
declare
  v_warehouse bigint;
  v_task record;
  v_cand jsonb;
  v_row jsonb;
  -- stock_unit_id (as text) -> units already promised to earlier tasks in this
  -- same plan. Without it, every task would be offered the same parcel.
  v_claimed jsonb := '{}'::jsonb;
  v_free integer;
  v_take integer;
  v_left integer;
  v_picks jsonb := '[]'::jsonb;
  v_short jsonb := '[]'::jsonb;
  v_key text;
begin
  select warehouse_id into v_warehouse from public.pick_waves where id = p_wave_id;
  if v_warehouse is null then raise exception 'wave % not found', p_wave_id; end if;
  if not public.can_access_warehouse(v_warehouse) then
    raise exception 'not permitted: warehouse.scope required';
  end if;

  for v_task in
    select t.id as task_id,
           t.pick_list_id,
           l.shipment_plan_id,
           coalesce(t.product_id, public.product_for_jan(t.jan_code)) as product_id,
           t.jan_code,
           coalesce(nullif(t.product_name, ''), '') as product_name,
           greatest(t.planned_quantity - coalesce(t.picked_quantity, 0), 0) as outstanding
      from public.pick_tasks t
      join public.pick_lists l on l.id = t.pick_list_id
      left join public.warehouse_products wp
             on wp.product_id = t.product_id and wp.warehouse_id = l.warehouse_id
     where l.wave_id = p_wave_id and l.status = 'PICKING'
       -- §15's 優先順位: the product's own pick priority first, so a warehouse
       -- that has expressed an order gets it.
     order by coalesce(wp.pick_priority, 100), t.jan_code, t.id
  loop
    continue when v_task.outstanding <= 0;

    if v_task.product_id is null then
      v_short := v_short || jsonb_build_object(
        'task_id', v_task.task_id, 'jan_code', v_task.jan_code,
        'outstanding', v_task.outstanding, 'reason', 'unlinked_jan_code');
      continue;
    end if;

    v_cand := public.pick_candidates(v_task.product_id, v_warehouse, v_task.outstanding);
    v_left := v_task.outstanding;

    for v_row in select * from jsonb_array_elements(v_cand->'candidates') loop
      exit when v_left <= 0;
      v_key := v_row->>'stock_unit_id';
      v_free := (v_row->>'free')::int - coalesce((v_claimed->>v_key)::int, 0);
      continue when v_free <= 0;

      v_take := least(v_left, v_free);
      v_claimed := jsonb_set(v_claimed, array[v_key],
        to_jsonb(coalesce((v_claimed->>v_key)::int, 0) + v_take));
      v_left := v_left - v_take;

      v_picks := v_picks || jsonb_build_object(
        'task_id', v_task.task_id,
        'pick_list_id', v_task.pick_list_id,
        'shipment_plan_id', v_task.shipment_plan_id,
        'product_id', v_task.product_id,
        'jan_code', v_task.jan_code,
        'product_name', v_task.product_name,
        'stock_unit_id', (v_row->>'stock_unit_id')::bigint,
        'lot_id', nullif(v_row->>'lot_id', '')::bigint,
        'lot_code', v_row->>'lot_code',
        'expiry_date', v_row->>'expiry_date',
        'serial_number', v_row->>'serial_number',
        'bin_id', nullif(v_row->>'bin_id', '')::bigint,
        'bin_code', v_row->>'bin_code',
        'quantity', v_take,
        'rule', v_cand->>'rule');
    end loop;

    if v_left > 0 then
      v_short := v_short || jsonb_build_object(
        'task_id', v_task.task_id, 'jan_code', v_task.jan_code,
        'short', v_left, 'reason', 'not_enough_shippable_stock');
    end if;
  end loop;

  return jsonb_build_object(
    'wave_id', p_wave_id,
    'warehouse_id', v_warehouse,
    -- The sheet: one row per place-and-parcel, with the total to take there and
    -- which tasks those units are for. This is the whole reason a wave exists.
    'stops', coalesce((
      select jsonb_agg(stop order by stop->>'bin_code' nulls last,
                                 stop->>'jan_code')
        from (
          select jsonb_build_object(
                   'bin_id', (p->>'bin_id')::bigint,
                   'bin_code', p->>'bin_code',
                   'product_id', (p->>'product_id')::bigint,
                   'jan_code', p->>'jan_code',
                   'product_name', p->>'product_name',
                   'lot_id', (p->>'lot_id')::bigint,
                   'lot_code', p->>'lot_code',
                   'expiry_date', p->>'expiry_date',
                   'stock_unit_id', (p->>'stock_unit_id')::bigint,
                   'quantity', sum((p->>'quantity')::int),
                   'lines', jsonb_agg(jsonb_build_object(
                              'task_id', (p->>'task_id')::bigint,
                              'pick_list_id', (p->>'pick_list_id')::bigint,
                              'shipment_plan_id', (p->>'shipment_plan_id')::bigint,
                              'quantity', (p->>'quantity')::int)
                            order by (p->>'task_id')::bigint)) as stop
            from jsonb_array_elements(v_picks) p
           group by p->>'bin_id', p->>'bin_code', p->>'product_id', p->>'jan_code',
                    p->>'product_name', p->>'lot_id', p->>'lot_code',
                    p->>'expiry_date', p->>'stock_unit_id'
        ) g), '[]'::jsonb),
    -- Kept separate: a picker needs the sheet, a supervisor needs to know the
    -- wave cannot be filled before anyone walks it.
    'short', v_short,
    'total_units', coalesce((
      select sum((p->>'quantity')::int) from jsonb_array_elements(v_picks) p), 0));
end;
$$;

revoke all on function public.wave_pick_plan(bigint) from public, anon;
grant execute on function public.wave_pick_plan(bigint) to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 4. Reading a wave
-- ---------------------------------------------------------------------------

create or replace function public.pick_wave_detail(p_wave_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path to ''
as $$
declare
  v_warehouse bigint;
begin
  select warehouse_id into v_warehouse from public.pick_waves where id = p_wave_id;
  if v_warehouse is null then raise exception 'wave % not found', p_wave_id; end if;
  if not public.can_access_warehouse(v_warehouse) then
    raise exception 'not permitted: warehouse.scope required';
  end if;

  return (
    select jsonb_build_object(
      'id', w.id,
      'code', w.code,
      'warehouse_id', w.warehouse_id,
      'warehouse_name', wh.name,
      'status', w.status,
      'assigned_to', w.assigned_to,
      'assigned_to_name', u.name,
      'priority', w.priority,
      'note', w.note,
      'created_at', w.created_at,
      'started_at', w.started_at,
      'completed_at', w.completed_at,
      'task_count', (select count(*) from public.pick_tasks t
                      join public.pick_lists l on l.id = t.pick_list_id
                     where l.wave_id = w.id),
      'picked_count', (select count(*) from public.pick_tasks t
                        join public.pick_lists l on l.id = t.pick_list_id
                       where l.wave_id = w.id and t.picked_quantity is not null),
      'lists', coalesce((
        select jsonb_agg(jsonb_build_object(
                 'pick_list_id', l.id,
                 'shipment_plan_id', l.shipment_plan_id,
                 'shipment_number', p.shipment_number,
                 'customer_name', p.customer_name,
                 'status', l.status,
                 'task_count', (select count(*) from public.pick_tasks t
                                 where t.pick_list_id = l.id),
                 'picked_count', (select count(*) from public.pick_tasks t
                                   where t.pick_list_id = l.id
                                     and t.picked_quantity is not null))
               order by l.id)
          from public.pick_lists l
          join public.shipment_plans p on p.id = l.shipment_plan_id
         where l.wave_id = w.id), '[]'::jsonb))
    from public.pick_waves w
    left join public.warehouses wh on wh.id = w.warehouse_id
    left join public.app_users u on u.id = w.assigned_to
   where w.id = p_wave_id);
end;
$$;

revoke all on function public.pick_wave_detail(bigint) from public, anon;
grant execute on function public.pick_wave_detail(bigint) to authenticated, service_role;

create or replace function public.pick_wave_index(
  p_warehouse_id bigint default null,
  p_status text default null,
  p_limit integer default 50
) returns jsonb
language plpgsql
stable
security definer
set search_path to ''
as $$
declare
  v_status text := nullif(upper(btrim(coalesce(p_status, ''))), '');
begin
  if p_warehouse_id is not null and not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;

  return coalesce((
    select jsonb_agg(row_to_json(x)::jsonb order by x.priority, x.id desc)
      from (
        select w.id, w.code, w.warehouse_id, wh.name as warehouse_name,
               w.status, w.priority, w.assigned_to, u.name as assigned_to_name,
               w.created_at, w.started_at, w.completed_at,
               (select count(*) from public.pick_lists l where l.wave_id = w.id)
                 as list_count,
               (select count(*) from public.pick_tasks t
                  join public.pick_lists l on l.id = t.pick_list_id
                 where l.wave_id = w.id) as task_count,
               (select count(*) from public.pick_tasks t
                  join public.pick_lists l on l.id = t.pick_list_id
                 where l.wave_id = w.id and t.picked_quantity is not null)
                 as picked_count
          from public.pick_waves w
          left join public.warehouses wh on wh.id = w.warehouse_id
          left join public.app_users u on u.id = w.assigned_to
         where (p_warehouse_id is null or w.warehouse_id = p_warehouse_id)
           and (v_status is null or w.status = v_status)
           and public.can_access_warehouse(w.warehouse_id)
         order by w.priority, w.id desc
         limit greatest(1, least(coalesce(p_limit, 50), 200))
      ) x), '[]'::jsonb);
end;
$$;

revoke all on function public.pick_wave_index(bigint, text, integer) from public, anon;
grant execute on function public.pick_wave_index(bigint, text, integer)
  to authenticated, service_role;
