-- 0088 — a rough, virtual count of what sits in a warehouse abroad.
--
-- 0087 made a cross-border transfer leave this system at the source: the
-- Japan warehouse is debited and the China warehouse holds nothing, because
-- few people know what the China warehouse ships out afterwards. That keeps
-- the real stock honest, but the question "about how much is over there now?"
-- still needs an answer. This is that answer, kept apart from real stock on
-- purpose — nothing here is ever available, reserved, picked or shipped:
--
--   EXPORT_IN  what left Japan for that warehouse, recorded automatically when
--              an exporting transfer ships (0087's EXPORTED).
--   COUNT      "on this date there were N" — typed in by whoever knows. It
--              resets the running figure; the difference from what was
--              expected is the part nobody recorded (mostly what shipped out).
--   ADJUST     a known change typed in by hand (+/-), e.g. a shipment out of
--              the China warehouse someone does know about.
--
-- The figure on a date is the latest COUNT on or before it plus every other
-- entry after that count, so a count entered late (back-dated) still lands in
-- the right place. Summaries are by date range, so "from this month to that
-- month" is one call.

create table if not exists public.virtual_stock_entries (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id),
  warehouse_id bigint not null references public.warehouses (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete cascade,
  entry_type text not null check (entry_type in ('EXPORT_IN', 'COUNT', 'ADJUST')),
  quantity integer not null default 0,
  counted_quantity integer,
  occurred_on date not null,
  transfer_order_id bigint references public.transfer_orders (id) on delete set null,
  note text,
  created_by uuid,
  created_at timestamptz not null default now(),
  constraint virtual_stock_entries_count_check check (
    (entry_type = 'COUNT' and counted_quantity is not null and counted_quantity >= 0)
    or (entry_type <> 'COUNT' and counted_quantity is null))
);

create index if not exists virtual_stock_entries_lookup_idx
  on public.virtual_stock_entries (warehouse_id, product_id, occurred_on, id);
create unique index if not exists virtual_stock_entries_one_export_line
  on public.virtual_stock_entries (transfer_order_id, product_id)
  where entry_type = 'EXPORT_IN';

alter table public.virtual_stock_entries enable row level security;
drop policy if exists "read virtual stock" on public.virtual_stock_entries;
create policy "read virtual stock" on public.virtual_stock_entries
  for select to authenticated
  using (public.has_permission('inventory.view') and public.can_access_warehouse(warehouse_id));

-- "Today" where the warehouse is. Every date in this ledger is the
-- warehouse's own calendar day, so an export shipped late in the evening in
-- Japan lands on the day it is in China, and a count typed in China is not
-- refused as "in the future" because the server's clock is on UTC.
create or replace function public.warehouse_today(p_warehouse_id bigint)
returns date
language sql stable security definer set search_path = '' as $$
  select (now() at time zone coalesce(
            (select w.timezone from public.warehouses w where w.id = p_warehouse_id),
            'Asia/Tokyo'))::date;
$$;

revoke all on function public.warehouse_today(bigint) from public, anon;
grant execute on function public.warehouse_today(bigint) to authenticated, service_role;

-- The virtual figure for one product in one warehouse at the end of a day.
create or replace function public.virtual_balance(
  p_warehouse_id bigint, p_product_id bigint, p_as_of date)
returns integer
language sql stable security definer set search_path = '' as $$
  with last_count as (
    select e.id, e.occurred_on, e.counted_quantity
      from public.virtual_stock_entries e
     where e.warehouse_id = p_warehouse_id and e.product_id = p_product_id
       and e.entry_type = 'COUNT' and e.occurred_on <= p_as_of
     order by e.occurred_on desc, e.id desc
     limit 1)
  select (coalesce((select counted_quantity from last_count), 0)
          + coalesce((
              select sum(e.quantity) from public.virtual_stock_entries e
               where e.warehouse_id = p_warehouse_id and e.product_id = p_product_id
                 and e.entry_type <> 'COUNT' and e.occurred_on <= p_as_of
                 and (not exists (select 1 from last_count)
                      or (e.occurred_on, e.id) > (select lc.occurred_on, lc.id from last_count lc))), 0)
         )::integer;
$$;

revoke all on function public.virtual_balance(bigint, bigint, date) from public, anon, authenticated;
grant execute on function public.virtual_balance(bigint, bigint, date) to service_role;

-- Warehouses a virtual figure makes sense for: abroad (another country than
-- the default warehouse) and not holding real cross-border stock, or already
-- carrying virtual entries.
create or replace function public.virtual_stock_warehouses()
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.has_permission('inventory.view') then
    raise exception 'not permitted: inventory.view required';
  end if;
  return coalesce((
    select jsonb_agg(jsonb_build_object(
             'id', w.id, 'code', w.code, 'name', w.name,
             'country_code', w.country_code, 'timezone', w.timezone) order by w.id)
      from public.warehouses w
     where public.can_access_warehouse(w.id)
       and ((not w.receives_cross_border
             and w.country_code <> coalesce((select d.country_code from public.warehouses d
                                              where d.is_default limit 1), 'JP'))
            or exists (select 1 from public.virtual_stock_entries e where e.warehouse_id = w.id))),
    '[]'::jsonb);
end;
$$;

revoke all on function public.virtual_stock_warehouses() from public, anon;
grant execute on function public.virtual_stock_warehouses() to authenticated, service_role;

-- One warehouse over a date range: totals, one row per month, one row per
-- product. `count_diff` is what counts corrected — closing minus everything
-- recorded — i.e. mostly what left the warehouse without anyone telling us.
create or replace function public.virtual_stock_summary(
  p_warehouse_id bigint, p_from date, p_to date)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare
  v_from date := coalesce(p_from, date_trunc('month', public.warehouse_today(p_warehouse_id))::date);
  v_to date := coalesce(p_to, public.warehouse_today(p_warehouse_id));
begin
  if not public.has_permission('inventory.view') then
    raise exception 'not permitted: inventory.view required';
  end if;
  if not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  if v_to < v_from then
    raise exception 'the end of the range is before its start';
  end if;

  return (
    with products as (
      select distinct e.product_id from public.virtual_stock_entries e
       where e.warehouse_id = p_warehouse_id and e.occurred_on <= v_to
    ),
    per_product as (
      select p.id as product_id, p.jan_code, p.name as product_name,
             public.virtual_balance(p_warehouse_id, p.id, v_from - 1) as opening,
             coalesce((select sum(e.quantity) from public.virtual_stock_entries e
                        where e.warehouse_id = p_warehouse_id and e.product_id = p.id
                          and e.entry_type = 'EXPORT_IN'
                          and e.occurred_on between v_from and v_to), 0)::int as arrived,
             coalesce((select sum(e.quantity) from public.virtual_stock_entries e
                        where e.warehouse_id = p_warehouse_id and e.product_id = p.id
                          and e.entry_type = 'ADJUST'
                          and e.occurred_on between v_from and v_to), 0)::int as adjusted,
             public.virtual_balance(p_warehouse_id, p.id, v_to) as closing,
             (select jsonb_build_object('occurred_on', e.occurred_on, 'counted', e.counted_quantity)
                from public.virtual_stock_entries e
               where e.warehouse_id = p_warehouse_id and e.product_id = p.id
                 and e.entry_type = 'COUNT'
               order by e.occurred_on desc, e.id desc limit 1) as last_count
        from products x
        join public.products p on p.id = x.product_id
    ),
    months as (
      select m::date as month_start,
             least((m + interval '1 month' - interval '1 day')::date, v_to) as month_end,
             greatest(m::date, v_from) as range_start
        from generate_series(date_trunc('month', v_from), date_trunc('month', v_to),
                             interval '1 month') m
    ),
    per_month as (
      select to_char(mo.month_start, 'YYYY-MM') as month,
             coalesce(sum(public.virtual_balance(p_warehouse_id, x.product_id, mo.range_start - 1)), 0)::int as opening,
             coalesce((select sum(e.quantity) from public.virtual_stock_entries e
                        where e.warehouse_id = p_warehouse_id and e.entry_type = 'EXPORT_IN'
                          and e.occurred_on between mo.range_start and mo.month_end), 0)::int as arrived,
             coalesce((select sum(e.quantity) from public.virtual_stock_entries e
                        where e.warehouse_id = p_warehouse_id and e.entry_type = 'ADJUST'
                          and e.occurred_on between mo.range_start and mo.month_end), 0)::int as adjusted,
             coalesce(sum(public.virtual_balance(p_warehouse_id, x.product_id, mo.month_end)), 0)::int as closing
        from months mo
        left join products x on true
       group by mo.month_start, mo.month_end, mo.range_start
    )
    select jsonb_build_object(
      'warehouse_id', p_warehouse_id,
      'from', v_from,
      'to', v_to,
      'totals', (select jsonb_build_object(
                   'opening', coalesce(sum(opening), 0),
                   'arrived', coalesce(sum(arrived), 0),
                   'adjusted', coalesce(sum(adjusted), 0),
                   'closing', coalesce(sum(closing), 0),
                   'count_diff', coalesce(sum(closing - opening - arrived - adjusted), 0))
                   from per_product),
      'months', coalesce((select jsonb_agg(jsonb_build_object(
                   'month', month, 'opening', opening, 'arrived', arrived,
                   'adjusted', adjusted, 'closing', closing,
                   'count_diff', closing - opening - arrived - adjusted) order by month)
                   from per_month), '[]'::jsonb),
      'products', coalesce((select jsonb_agg(jsonb_build_object(
                   'product_id', product_id, 'jan_code', jan_code, 'product_name', product_name,
                   'opening', opening, 'arrived', arrived, 'adjusted', adjusted,
                   'closing', closing, 'count_diff', closing - opening - arrived - adjusted,
                   'last_count', last_count) order by product_name)
                   from per_product), '[]'::jsonb)));
end;
$$;

revoke all on function public.virtual_stock_summary(bigint, date, date) from public, anon;
grant execute on function public.virtual_stock_summary(bigint, date, date) to authenticated, service_role;

create or replace function public.virtual_stock_history(
  p_warehouse_id bigint, p_product_id bigint, p_limit integer default 100)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.has_permission('inventory.view') then
    raise exception 'not permitted: inventory.view required';
  end if;
  if not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  return coalesce((
    select jsonb_agg(row_to_json(x)::jsonb order by x.occurred_on desc, x.id desc)
      from (
        select e.id, e.entry_type, e.quantity, e.counted_quantity, e.occurred_on, e.note,
               e.transfer_order_id, o.transfer_number,
               public.virtual_balance(p_warehouse_id, p_product_id, e.occurred_on) as balance_that_day
          from public.virtual_stock_entries e
          left join public.transfer_orders o on o.id = e.transfer_order_id
         where e.warehouse_id = p_warehouse_id and e.product_id = p_product_id
         order by e.occurred_on desc, e.id desc
         limit greatest(1, least(coalesce(p_limit, 100), 500))) x), '[]'::jsonb);
end;
$$;

revoke all on function public.virtual_stock_history(bigint, bigint, integer) from public, anon;
grant execute on function public.virtual_stock_history(bigint, bigint, integer) to authenticated, service_role;

-- Typed in by whoever knows: an actual count, or a known change.
create or replace function public.record_virtual_stock(
  p_warehouse_id bigint,
  p_jan_code text,
  p_entry_type text,
  p_quantity integer,
  p_occurred_on date default null,
  p_note text default null
) returns bigint
language plpgsql security definer set search_path = '' as $$
declare
  v_product bigint;
  v_id bigint;
  v_type text := upper(coalesce(p_entry_type, ''));
begin
  if not public.has_permission('inventory.adjust') then
    raise exception 'not permitted: inventory.adjust required';
  end if;
  if not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  if v_type not in ('COUNT', 'ADJUST') then
    raise exception 'entry type must be COUNT or ADJUST';
  end if;
  if p_quantity is null or (v_type = 'COUNT' and p_quantity < 0) then
    raise exception 'a count must be zero or more';
  end if;
  if v_type = 'ADJUST' and p_quantity = 0 then
    raise exception 'an adjustment must change the figure';
  end if;
  if coalesce(p_occurred_on, public.warehouse_today(p_warehouse_id)) > public.warehouse_today(p_warehouse_id) then
    raise exception 'the date cannot be in the future';
  end if;
  v_product := public.product_for_jan(btrim(coalesce(p_jan_code, '')));
  if v_product is null then
    raise exception 'no product with JAN %', p_jan_code;
  end if;

  insert into public.virtual_stock_entries (
    company_id, warehouse_id, product_id, entry_type, quantity, counted_quantity,
    occurred_on, note, created_by)
  values (
    (select company_id from public.products where id = v_product),
    p_warehouse_id, v_product, v_type,
    case when v_type = 'ADJUST' then p_quantity else 0 end,
    case when v_type = 'COUNT' then p_quantity end,
    coalesce(p_occurred_on, public.warehouse_today(p_warehouse_id)), nullif(btrim(coalesce(p_note, '')), ''), auth.uid())
  returning id into v_id;

  perform public.log_audit('virtual_stock.' || lower(v_type), 'warehouse', p_warehouse_id::text,
    p_warehouse_id, jsonb_build_object('product_id', v_product, 'quantity', p_quantity,
                                       'occurred_on', coalesce(p_occurred_on, public.warehouse_today(p_warehouse_id))));
  return v_id;
end;
$$;

create or replace function public.delete_virtual_stock_entry(p_id bigint)
returns boolean
language plpgsql security definer set search_path = '' as $$
declare
  v_row record;
begin
  select warehouse_id, entry_type into v_row from public.virtual_stock_entries where id = p_id;
  if not found then return false; end if;
  if not public.has_permission('inventory.adjust') then
    raise exception 'not permitted: inventory.adjust required';
  end if;
  if not public.can_access_warehouse(v_row.warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  -- An export's arrival follows the transfer; only what was typed in is undone here.
  if v_row.entry_type = 'EXPORT_IN' then
    raise exception 'an export arrival comes from its transfer and cannot be deleted';
  end if;
  delete from public.virtual_stock_entries where id = p_id;
  perform public.log_audit('virtual_stock.deleted', 'warehouse', v_row.warehouse_id::text,
    v_row.warehouse_id, jsonb_build_object('entry_id', p_id));
  return true;
end;
$$;

revoke all on function public.record_virtual_stock(bigint, text, text, integer, date, text) from public, anon;
revoke all on function public.delete_virtual_stock_entry(bigint) from public, anon;
grant execute on function public.record_virtual_stock(bigint, text, text, integer, date, text) to authenticated, service_role;
grant execute on function public.delete_virtual_stock_entry(bigint) to authenticated, service_role;

-- What an exporting transfer shipped, as an arrival in the destination's
-- virtual figure, dated in the destination's own time zone.
create or replace function public.record_export_arrival(p_transfer_id bigint)
returns integer
language plpgsql security definer set search_path = '' as $$
declare
  v_count integer;
begin
  insert into public.virtual_stock_entries (
    company_id, warehouse_id, product_id, entry_type, quantity, occurred_on,
    transfer_order_id, note)
  select (select company_id from public.products where id = x.product_id),
         o.destination_warehouse_id, x.product_id, 'EXPORT_IN', x.qty,
         (coalesce(o.exported_at, o.shipped_at, now()) at time zone coalesce(dw.timezone, 'Asia/Tokyo'))::date,
         o.id, o.transfer_number
    from public.transfer_orders o
    join public.warehouses dw on dw.id = o.destination_warehouse_id
    join (select l.transfer_order_id,
                 coalesce(l.product_id, public.product_for_jan(l.jan_code)) as product_id,
                 sum(l.picked_quantity)::int as qty
            from public.transfer_order_lines l
           where l.transfer_order_id = p_transfer_id and coalesce(l.picked_quantity, 0) > 0
           group by 1, 2) x on x.transfer_order_id = o.id
   where o.id = p_transfer_id and o.status = 'EXPORTED' and x.product_id is not null
  on conflict (transfer_order_id, product_id) where entry_type = 'EXPORT_IN' do nothing;
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

revoke all on function public.record_export_arrival(bigint) from public, anon, authenticated;
grant execute on function public.record_export_arrival(bigint) to service_role;

create or replace function public.complete_transfer_picking(p_transfer_id bigint)
returns bigint
language plpgsql security definer set search_path = '' as $$
declare
  v_status  text;
  v_source  bigint;
  v_pending integer;
  v_cross   boolean;
  v_exports boolean;
  r         record;
begin
  select o.status, o.source_warehouse_id,
         sw.country_code <> dw.country_code
    into v_status, v_source, v_cross
    from public.transfer_orders o
    join public.warehouses sw on sw.id = o.source_warehouse_id
    join public.warehouses dw on dw.id = o.destination_warehouse_id
   where o.id = p_transfer_id;
  if v_status is null then raise exception 'transfer % not found', p_transfer_id; end if;
  if v_status <> 'PICKING' then
    raise exception 'transfer % is % and cannot complete picking', p_transfer_id, v_status;
  end if;

  select count(*) into v_pending from public.transfer_order_lines
   where transfer_order_id = p_transfer_id and picked_quantity is null;
  if v_pending > 0 then
    raise exception 'transfer % still has % unpicked line(s)', p_transfer_id, v_pending;
  end if;

  for r in
    select jan_code, sum(picked_quantity)::int as qty, max(product_name) as pname
      from public.transfer_order_lines
     where transfer_order_id = p_transfer_id and picked_quantity > 0
     group by jan_code
  loop
    perform public.apply_stock_movement(
      v_source, r.jan_code, -r.qty, 'TRANSFER_OUT',
      'transfer_order', p_transfer_id::text, r.pname);
  end loop;

  v_exports := public.transfer_exports(p_transfer_id);

  update public.transfer_orders
     set status = case when v_exports then 'EXPORTED' else 'IN_TRANSIT' end,
         shipped_at = now(),
         exported_at = case when v_exports then now() end,
         cross_border = v_cross
   where id = p_transfer_id;

  -- Gone from real stock, but counted into the destination's virtual figure.
  if v_exports then
    perform public.record_export_arrival(p_transfer_id);
  end if;

  perform public.log_audit(
    case when v_exports then 'transfer.exported' else 'transfer.shipped' end,
    'transfer_order', p_transfer_id::text, v_source,
    jsonb_build_object('cross_border', v_cross));
  return p_transfer_id;
end;
$$;

-- Exports made before this migration.
do $$
declare r record;
begin
  for r in select id from public.transfer_orders where status = 'EXPORTED' loop
    perform public.record_export_arrival(r.id);
  end loop;
end $$;
