-- 0109 — the product library: each product's pictures, and the first one
-- shown in front of its name wherever the product appears.
--
-- A warehouse worker recognises goods by sight long before by JAN. So every
-- product can carry pictures (`product_images`, files in the private
-- `product-images` bucket), put in the order the company wants; the first
-- is the product's face. Every screen that lists goods — receiving,
-- inspection, putaway, picking, shipping, orders — shows that face in front
-- of the name, looked up here by product id, or by JAN for lines that are
-- not linked to a product yet (a delivery note just read).
--
-- Reading is open to everyone who handles goods (the packer and the shipper
-- included, who hold no product permission); changing the library needs
-- product.manage. Nothing is deleted: a picture taken down is withdrawn and
-- kept, like every other attachment (0070).

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', false)
on conflict (id) do nothing;

-- Who may look at product pictures: anyone who handles goods.
create or replace function public.can_view_product_images()
returns boolean language sql stable security definer set search_path = '' as $$
  select public.has_permission('product.view') or public.has_permission('inventory.view')
      or public.has_permission('inspection.view') or public.has_permission('receiving.view')
      or public.has_permission('warehouse.view') or public.has_permission('sales_order.view')
      or public.has_permission('purchase_order.view') or public.has_permission('ship.complete')
      or public.has_permission('pack.complete');
$$;
revoke all on function public.can_view_product_images() from public, anon;
grant execute on function public.can_view_product_images() to authenticated, service_role;

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id),
  storage_path text not null unique,
  content_type text,
  byte_size bigint,
  width int,
  height int,
  caption text,
  -- 1 is the product's face: shown in front of its name everywhere.
  position int not null default 1,
  uploaded_by uuid,
  created_at timestamptz not null default now(),
  withdrawn_at timestamptz,
  withdrawn_by uuid
);
create index if not exists product_images_product_idx
  on public.product_images (product_id, position) where withdrawn_at is null;

alter table public.product_images enable row level security;
drop policy if exists "product_images: goods handlers can read" on public.product_images;
create policy "product_images: goods handlers can read" on public.product_images
  for select to authenticated using (public.can_view_product_images());
-- No write policy: every change goes through the functions below.

drop policy if exists "product-images: managers can write" on storage.objects;
create policy "product-images: managers can write" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'product-images' and public.has_permission('product.manage'));
drop policy if exists "product-images: goods handlers can read" on storage.objects;
create policy "product-images: goods handlers can read" on storage.objects
  for select to authenticated
  using (bucket_id = 'product-images' and public.can_view_product_images());

-- Keeps the live pictures numbered 1..n in their order.
create or replace function public.product_images_renumber(p_product_id bigint)
returns void language sql security definer set search_path = '' as $$
  update public.product_images i set position = r.n
    from (select id, row_number() over (order by position, id) as n
            from public.product_images
           where product_id = p_product_id and withdrawn_at is null) r
   where i.id = r.id and i.position <> r.n;
$$;
revoke all on function public.product_images_renumber(bigint) from public, anon, authenticated;

-- Records a picture already uploaded to Storage. [p_first] puts it in front.
create or replace function public.add_product_image(
  p_product_id bigint,
  p_storage_path text,
  p_content_type text default null,
  p_byte_size bigint default null,
  p_caption text default null,
  p_first boolean default false
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  v_id bigint;
  v_pos int;
begin
  if not public.has_permission('product.manage') then
    raise exception 'not permitted: product.manage required';
  end if;
  if not exists (select 1 from public.products where id = p_product_id) then
    raise exception 'product % not found', p_product_id;
  end if;
  if coalesce(p_storage_path, '') = '' or p_storage_path not like p_product_id || '/%' then
    raise exception 'the picture must be stored under the product''s folder';
  end if;
  if p_first then
    update public.product_images set position = position + 1
     where product_id = p_product_id and withdrawn_at is null;
    v_pos := 1;
  else
    select coalesce(max(position), 0) + 1 into v_pos
      from public.product_images where product_id = p_product_id and withdrawn_at is null;
  end if;
  insert into public.product_images (product_id, storage_path, content_type, byte_size, caption, position, uploaded_by)
  values (p_product_id, p_storage_path, p_content_type, p_byte_size, nullif(trim(p_caption), ''), v_pos, auth.uid())
  returning id into v_id;
  perform public.product_images_renumber(p_product_id);
  perform public.log_audit('product.image_added', 'product', p_product_id::text, null,
    jsonb_build_object('image_id', v_id, 'storage_path', p_storage_path, 'first', p_first));
  return public.product_images_of(p_product_id);
end;
$$;

-- Puts the pictures in the given order (ids first to last); the first is
-- the face. Ids not listed keep their relative order after those listed.
create or replace function public.reorder_product_images(p_product_id bigint, p_ids bigint[])
returns jsonb language plpgsql security definer set search_path = '' as $$
begin
  if not public.has_permission('product.manage') then
    raise exception 'not permitted: product.manage required';
  end if;
  update public.product_images i
     set position = coalesce(array_position(p_ids, i.id), 100000 + i.position)
   where i.product_id = p_product_id and i.withdrawn_at is null;
  perform public.product_images_renumber(p_product_id);
  perform public.log_audit('product.images_reordered', 'product', p_product_id::text, null,
    jsonb_build_object('order', to_jsonb(p_ids)));
  return public.product_images_of(p_product_id);
end;
$$;

create or replace function public.withdraw_product_image(p_id bigint)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  v_product bigint;
begin
  if not public.has_permission('product.manage') then
    raise exception 'not permitted: product.manage required';
  end if;
  update public.product_images set withdrawn_at = now(), withdrawn_by = auth.uid()
   where id = p_id and withdrawn_at is null
   returning product_id into v_product;
  if v_product is null then
    raise exception 'picture % not found', p_id;
  end if;
  perform public.product_images_renumber(v_product);
  perform public.log_audit('product.image_withdrawn', 'product', v_product::text, null,
    jsonb_build_object('image_id', p_id));
  return public.product_images_of(v_product);
end;
$$;

-- One product's live pictures, in order.
create or replace function public.product_images_of(p_product_id bigint)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.can_view_product_images() then
    raise exception 'not permitted: product.view required';
  end if;
  return coalesce((
    select jsonb_agg(jsonb_build_object(
             'id', id, 'product_id', product_id, 'storage_path', storage_path,
             'content_type', content_type, 'byte_size', byte_size, 'caption', caption,
             'position', position, 'created_at', created_at) order by position, id)
      from public.product_images
     where product_id = p_product_id and withdrawn_at is null), '[]'::jsonb);
end;
$$;

-- The face of each product asked for, by id and/or by JAN (lines not yet
-- linked to a product). One row per product that has a picture.
create or replace function public.product_thumbnails(
  p_product_ids bigint[] default null,
  p_jans text[] default null
) returns jsonb language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.can_view_product_images() then
    raise exception 'not permitted: product.view required';
  end if;
  return coalesce((
    with wanted as (
      select p.id, p.jan_code from public.products p
       where p.id = any(coalesce(p_product_ids, '{}'))
          or (p.jan_code is not null and p.jan_code = any(
                select public.normalize_jan(j) from unnest(coalesce(p_jans, '{}')) j))
    )
    select jsonb_agg(jsonb_build_object(
             'product_id', w.id, 'jan_code', w.jan_code, 'storage_path', f.storage_path,
             'count', f.n))
      from wanted w
      join lateral (
        select i.storage_path, count(*) over () as n
          from public.product_images i
         where i.product_id = w.id and i.withdrawn_at is null
         order by i.position, i.id limit 1
      ) f on true), '[]'::jsonb);
end;
$$;

-- The library: products with their face and how many pictures they have.
create or replace function public.product_library(
  p_query text default null,
  p_without_images boolean default false,
  p_limit int default 60,
  p_offset int default 0
) returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare
  v_q text := nullif(trim(p_query), '');
begin
  if not public.can_view_product_images() then
    raise exception 'not permitted: product.view required';
  end if;
  return coalesce((
    select jsonb_agg(row_to_json(t)::jsonb order by t.name, t.id)
      from (
        select p.id, p.jan_code, p.name, p.sku, p.maker, p.category, p.status,
               f.storage_path, coalesce(f.n, 0) as image_count
          from public.products p
          left join lateral (
            select i.storage_path, count(*) over () as n
              from public.product_images i
             where i.product_id = p.id and i.withdrawn_at is null
             order by i.position, i.id limit 1
          ) f on true
         where (v_q is null
                or p.name ilike '%' || v_q || '%'
                or p.jan_code like '%' || regexp_replace(v_q, '\D', '', 'g') || '%' and regexp_replace(v_q, '\D', '', 'g') <> ''
                or p.sku ilike '%' || v_q || '%'
                or p.maker ilike '%' || v_q || '%')
           and (not p_without_images or f.storage_path is null)
         order by p.name, p.id
         limit greatest(1, least(coalesce(p_limit, 60), 200)) offset greatest(0, coalesce(p_offset, 0))
      ) t), '[]'::jsonb);
end;
$$;

revoke all on function public.add_product_image(bigint, text, text, bigint, text, boolean) from public, anon;
revoke all on function public.reorder_product_images(bigint, bigint[]) from public, anon;
revoke all on function public.withdraw_product_image(bigint) from public, anon;
revoke all on function public.product_images_of(bigint) from public, anon;
revoke all on function public.product_thumbnails(bigint[], text[]) from public, anon;
revoke all on function public.product_library(text, boolean, int, int) from public, anon;
grant execute on function public.add_product_image(bigint, text, text, bigint, text, boolean) to authenticated, service_role;
grant execute on function public.reorder_product_images(bigint, bigint[]) to authenticated, service_role;
grant execute on function public.withdraw_product_image(bigint) to authenticated, service_role;
grant execute on function public.product_images_of(bigint) to authenticated, service_role;
grant execute on function public.product_thumbnails(bigint[], text[]) to authenticated, service_role;
grant execute on function public.product_library(text, boolean, int, int) to authenticated, service_role;
