-- 0132 — every uploaded file kept as evidence (エビデンス), and downloadable
-- again.
--
-- A delivery note, invoice, quotation or sheet read by import-plan used to
-- live only for the length of the request. Now the edge function stores the
-- file itself in the private `import-documents` bucket and records it here:
-- what it was, who sent it in, what it was read as (the supplier, its number,
-- how many lines) and, once committed, the plan it became. The same file sent
-- twice (a re-read after a column correction) is stored once.
--
--   * Rows and bytes are written by the service role only (the edge
--     function); there is no insert, update or delete policy. Evidence stays.
--   * Reading follows what the file was for: delivery and shipment files to
--     receiving.view / pack.complete, quotations, sheets and training samples
--     to product.view, everything to audit.view — and a file tied to a
--     warehouse only inside the caller's warehouse scope.
--   * `import_documents_list(...)` lists them, newest first, with the plan
--     and supplier they belong to.

insert into storage.buckets (id, name, public, file_size_limit)
values ('import-documents', 'import-documents', false, 52428800)
on conflict (id) do nothing;

create table if not exists public.import_documents (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id),
  purpose text not null default 'plan'
    check (purpose in ('plan', 'shipment', 'training', 'quote', 'price_book', 'library', 'ocr')),
  file_name text not null,
  content_type text,
  byte_size bigint,
  sha256 text not null,
  storage_path text not null,
  source text,
  supplier_id bigint references public.delivery_suppliers(id) on delete set null,
  supplier_name text,
  registration_number text,
  doc_number text,
  doc_date text,
  line_count integer,
  delivery_plan_id bigint references public.delivery_plans(id) on delete set null,
  shipment_plan_id bigint references public.shipment_plans(id) on delete set null,
  warehouse_id bigint references public.warehouses(id) on delete set null,
  uploaded_by uuid references public.app_users(id) on delete set null,
  uploaded_at timestamptz not null default now(),
  committed_at timestamptz
);

create index if not exists import_documents_sha_idx on public.import_documents (sha256);
create index if not exists import_documents_uploaded_idx on public.import_documents (uploaded_at desc);
create index if not exists import_documents_plan_idx on public.import_documents (delivery_plan_id);
create index if not exists import_documents_shipment_idx on public.import_documents (shipment_plan_id);

comment on table public.import_documents is
  'Every file uploaded to import-plan, kept as evidence (0132). Bytes in the import-documents bucket.';

-- Who may see a file, by what it was for.
create or replace function public.import_document_visible(p_purpose text, p_warehouse_id bigint)
returns boolean
language sql stable security definer set search_path = '' as $$
  select (public.has_permission('audit.view')
          or case when p_purpose in ('plan', 'ocr') then public.has_permission('receiving.view')
                                                         or public.has_permission('receiving.confirm')
                  when p_purpose = 'shipment' then public.has_permission('pack.complete')
                  else public.has_permission('product.view') end)
     and (p_warehouse_id is null or public.can_access_warehouse(p_warehouse_id));
$$;

alter table public.import_documents enable row level security;

create policy "import_documents: read by purpose"
  on public.import_documents for select
  to authenticated
  using (public.import_document_visible(purpose, warehouse_id));

grant select on public.import_documents to authenticated;

create policy "import-documents: read by purpose"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'import-documents'
    and exists (
      select 1 from public.import_documents d
       where d.storage_path = storage.objects.name
         and public.import_document_visible(d.purpose, d.warehouse_id)
    )
  );

create or replace function public.import_documents_list(
  p_purpose text default null,
  p_search text default null,
  p_limit integer default 200
)
returns jsonb
language sql stable security invoker set search_path = '' as $$
  select coalesce(jsonb_agg(x order by (x->>'uploaded_at') desc), '[]'::jsonb)
    from (
      select jsonb_build_object(
               'id', d.id, 'purpose', d.purpose, 'file_name', d.file_name,
               'content_type', d.content_type, 'byte_size', d.byte_size,
               'storage_path', d.storage_path, 'source', d.source,
               'supplier_id', d.supplier_id,
               'supplier_name', coalesce(s.name, d.supplier_name),
               'registration_number', d.registration_number,
               'doc_number', d.doc_number, 'doc_date', d.doc_date, 'line_count', d.line_count,
               'delivery_plan_id', d.delivery_plan_id, 'shipment_plan_id', d.shipment_plan_id,
               'reference_no', coalesce(dp.reference_no, sp.reference_no),
               'warehouse_id', d.warehouse_id,
               'uploaded_by', d.uploaded_by, 'uploaded_by_name', coalesce(u.name, u.email),
               'uploaded_at', d.uploaded_at, 'committed_at', d.committed_at) as x
        from public.import_documents d
        left join public.delivery_suppliers s on s.id = d.supplier_id
        left join public.delivery_plans dp on dp.id = d.delivery_plan_id
        left join public.shipment_plans sp on sp.id = d.shipment_plan_id
        left join public.app_users u on u.id = d.uploaded_by
       where (p_purpose is null or d.purpose = p_purpose)
         and (p_search is null or p_search = ''
              or d.file_name ilike '%' || p_search || '%'
              or coalesce(s.name, d.supplier_name, '') ilike '%' || p_search || '%'
              or coalesce(d.doc_number, '') ilike '%' || p_search || '%'
              or coalesce(dp.reference_no, sp.reference_no, '') ilike '%' || p_search || '%')
       order by d.uploaded_at desc
       limit greatest(1, least(coalesce(p_limit, 200), 1000))
    ) t;
$$;

revoke all on function public.import_document_visible(text, bigint) from public, anon;
revoke all on function public.import_documents_list(text, text, integer) from public, anon;
grant execute on function public.import_document_visible(text, bigint) to authenticated, service_role;
grant execute on function public.import_documents_list(text, text, integer) to authenticated, service_role;

-- The company a document was addressed to (〇〇御中) — us. Kept so our own
-- name can be inferred while it is not set yet, and offered on 自社情報.
alter table public.import_documents add column if not exists addressee text;
comment on column public.import_documents.addressee is
  'The company the document was addressed to (〇〇御中) — us. Read when our own name is not set yet (0132).';

-- What our documents were addressed to, most often first: offered on the
-- 自社情報 screen as our name or one of its other spellings.
create or replace function public.own_company_suggestions()
returns jsonb
language sql stable security invoker set search_path = '' as $$
  select coalesce(jsonb_agg(jsonb_build_object('name', name, 'count', n, 'last_seen', last_seen) order by n desc, last_seen desc), '[]'::jsonb)
    from (
      select min(addressee) as name, count(*) as n, max(uploaded_at) as last_seen
        from public.import_documents
       where addressee is not null and length(trim(addressee)) >= 2
       group by regexp_replace(normalize(addressee, NFKC), '\s|株式会社|有限会社|合同会社|\(株\)|\(有\)|㈱|㈲', '', 'g')
       order by count(*) desc
       limit 10
    ) t;
$$;
revoke all on function public.own_company_suggestions() from public, anon;
grant execute on function public.own_company_suggestions() to authenticated, service_role;
