-- 0133 — is the AI working? (AIの稼働状況)
--
-- Every call the edge functions make to the AI (Gemini) is recorded in
-- `ai_calls`: what it was for, whether it answered, how long it took, how
-- many tokens it used, and — when it failed — what kind of failure it was:
--
--   no_key      GEMINI_API_KEY is not set on the server
--   auth        the key was refused (invalid, revoked, wrong project)
--   quota       too many requests / the free tier's limits (429)
--   overload    the AI service was busy or failing (5xx)
--   bad_request the request was refused for another reason (4xx)
--   network     the AI service could not be reached
--   parse       it answered, but not with the JSON asked for
--
-- Every read file also gets a `quality` summary on its `import_documents` row
-- (lines, how many the two AI readings disagreed on, added or dropped by the
-- check, whether the lines add up to the document's total).
--
-- `ai_health(p_hours)` turns both into a verdict per measure and overall:
--
--   availability = answered calls / all calls
--                  good >= 98%, warn >= 90%, else bad
--   latency p95  = the slowest 5% of answered calls
--                  good <= 20 s, warn <= 45 s, else bad
--   agreement    = 1 - (lines the check disagreed on, added or dropped)
--                      / lines read by the AI          (AI-read files only)
--                  good >= 90%, warn >= 75%, else bad
--   totals match = files whose lines add up to the document's total
--                  / files where that could be compared
--                  good >= 90%, warn >= 70%, else bad
--
--   overall      = the worst of the four (a measure with no data is
--                  "unknown" and does not count); the last call failing for
--                  a missing or refused key, or for quota, makes it bad at
--                  once, since nothing will work until that is fixed.
--
-- Rows are written by the edge functions (service role) only. Reading needs
-- ai.review, user.manage or audit.view.

create table if not exists public.ai_calls (
  id bigint generated by default as identity primary key,
  called_at timestamptz not null default now(),
  function_name text,
  task text,
  model text,
  ok boolean not null,
  http_status integer,
  error_kind text check (error_kind in ('no_key', 'auth', 'quota', 'overload', 'bad_request', 'network', 'parse', 'other')),
  error text,
  attempts integer not null default 1,
  latency_ms integer,
  input_tokens integer,
  output_tokens integer
);

create index if not exists ai_calls_called_idx on public.ai_calls (called_at desc);

comment on table public.ai_calls is
  'Every AI (Gemini) call made by the edge functions, with its outcome (0133).';

alter table public.ai_calls enable row level security;

create policy "ai_calls: AI reviewers and admins read"
  on public.ai_calls for select
  to authenticated
  using (public.has_permission('ai.review') or public.has_permission('user.manage') or public.has_permission('audit.view'));

grant select on public.ai_calls to authenticated;

alter table public.import_documents add column if not exists quality jsonb;
comment on column public.import_documents.quality is
  'How the reading went (0133): lines, disagree/added/dropped by the check, totals_ok, agreement.';

create or replace function public.ai_health(p_hours integer default 168)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare
  v_since timestamptz := now() - make_interval(hours => greatest(1, least(coalesce(p_hours, 168), 24 * 90)));
  v_calls jsonb;
  v_docs jsonb;
  v_last jsonb;
  v_errors jsonb;
  v_by_kind jsonb;
  v_avail numeric;
  v_p95 numeric;
  v_agree numeric;
  v_totals numeric;
  v_measures jsonb;
  v_overall text;
  v_blocking text;
  v_rank int := 0;
  v_m jsonb;
begin
  if not (public.has_permission('ai.review') or public.has_permission('user.manage') or public.has_permission('audit.view')) then
    raise exception 'not permitted: ai.review required';
  end if;

  select jsonb_build_object(
           'total', count(*),
           'ok', count(*) filter (where ok),
           'failed', count(*) filter (where not ok),
           'p50_ms', percentile_cont(0.5) within group (order by latency_ms) filter (where ok),
           'p95_ms', percentile_cont(0.95) within group (order by latency_ms) filter (where ok),
           'input_tokens', coalesce(sum(input_tokens), 0),
           'output_tokens', coalesce(sum(output_tokens), 0),
           'last_call_at', max(called_at),
           'last_ok_at', max(called_at) filter (where ok)),
         case when count(*) > 0 then (count(*) filter (where ok))::numeric / count(*) end,
         percentile_cont(0.95) within group (order by latency_ms) filter (where ok)
    into v_calls, v_avail, v_p95
    from public.ai_calls where called_at >= v_since;

  select coalesce(jsonb_object_agg(error_kind, n), '{}'::jsonb) into v_by_kind
    from (select error_kind, count(*) n from public.ai_calls
           where called_at >= v_since and not ok group by error_kind) k;

  select to_jsonb(c) - 'id' into v_last
    from (select id, called_at, task, model, ok, http_status, error_kind, error, latency_ms
            from public.ai_calls order by called_at desc, id desc limit 1) c;

  select coalesce(jsonb_agg(to_jsonb(e) - 'id' order by e.called_at desc), '[]'::jsonb) into v_errors
    from (select id, called_at, function_name, task, http_status, error_kind, left(error, 300) as error
            from public.ai_calls where not ok and called_at >= v_since
           order by called_at desc limit 10) e;

  select jsonb_build_object(
           'files', count(*),
           'ai_files', count(*) filter (where (quality->>'source') = 'gemini'),
           'ai_lines', coalesce(sum((quality->>'lines')::int) filter (where (quality->>'source') = 'gemini'), 0),
           'ai_problem_lines', coalesce(sum(coalesce((quality->>'disagree')::int, 0) + coalesce((quality->>'added')::int, 0)
                                         + coalesce((quality->>'dropped')::int, 0)) filter (where (quality->>'source') = 'gemini'), 0),
           'not_verified_files', count(*) filter (where (quality->>'verified') = 'false'),
           'totals_compared', count(*) filter (where quality ? 'totals_ok' and quality->'totals_ok' <> 'null'::jsonb),
           'totals_ok', count(*) filter (where (quality->>'totals_ok') = 'true')),
         case when coalesce(sum((quality->>'lines')::int) filter (where (quality->>'source') = 'gemini'), 0) > 0
              then 1 - (coalesce(sum(coalesce((quality->>'disagree')::int, 0) + coalesce((quality->>'added')::int, 0)
                                     + coalesce((quality->>'dropped')::int, 0)) filter (where (quality->>'source') = 'gemini'), 0))::numeric
                       / sum((quality->>'lines')::int) filter (where (quality->>'source') = 'gemini') end,
         case when count(*) filter (where (quality->>'totals_ok') in ('true', 'false')) > 0
              then (count(*) filter (where (quality->>'totals_ok') = 'true'))::numeric
                   / count(*) filter (where (quality->>'totals_ok') in ('true', 'false')) end
    into v_docs, v_agree, v_totals
    from public.import_documents where uploaded_at >= v_since and quality is not null;

  v_measures := jsonb_build_array(
    jsonb_build_object('key', 'availability', 'value', v_avail, 'good', 0.98, 'warn', 0.90, 'higher_is_better', true,
      'verdict', case when v_avail is null then 'unknown' when v_avail >= 0.98 then 'good' when v_avail >= 0.90 then 'warn' else 'bad' end),
    jsonb_build_object('key', 'latency_p95', 'value', v_p95, 'good', 20000, 'warn', 45000, 'higher_is_better', false,
      'verdict', case when v_p95 is null then 'unknown' when v_p95 <= 20000 then 'good' when v_p95 <= 45000 then 'warn' else 'bad' end),
    jsonb_build_object('key', 'agreement', 'value', v_agree, 'good', 0.90, 'warn', 0.75, 'higher_is_better', true,
      'verdict', case when v_agree is null then 'unknown' when v_agree >= 0.90 then 'good' when v_agree >= 0.75 then 'warn' else 'bad' end),
    jsonb_build_object('key', 'totals_match', 'value', v_totals, 'good', 0.90, 'warn', 0.70, 'higher_is_better', true,
      'verdict', case when v_totals is null then 'unknown' when v_totals >= 0.90 then 'good' when v_totals >= 0.70 then 'warn' else 'bad' end)
  );

  for v_m in select * from jsonb_array_elements(v_measures) loop
    v_rank := greatest(v_rank, case v_m->>'verdict' when 'bad' then 3 when 'warn' then 2 when 'good' then 1 else 0 end);
  end loop;

  -- Nothing works until a missing or refused key, or a spent quota, is fixed.
  if v_last is not null and (v_last->>'ok')::boolean = false
     and (v_last->>'error_kind') in ('no_key', 'auth', 'quota') then
    v_blocking := v_last->>'error_kind';
    v_rank := 3;
  end if;
  v_overall := case v_rank when 3 then 'bad' when 2 then 'warn' when 1 then 'good' else 'unknown' end;

  return jsonb_build_object(
    'hours', extract(epoch from (now() - v_since)) / 3600,
    'overall', v_overall,
    'blocking', v_blocking,
    'measures', v_measures,
    'calls', v_calls,
    'errors_by_kind', v_by_kind,
    'last_call', v_last,
    'recent_errors', v_errors,
    'documents', v_docs);
end;
$$;

revoke all on function public.ai_health(integer) from public, anon;
grant execute on function public.ai_health(integer) to authenticated, service_role;
