-- 0138 — one file, two stages: 商品マスタ first, then the stock in
-- 商品ライブラリー.
--
-- A file listing the goods to put in the warehouse (Excel, PDF, photo) is
-- chosen once and goes through:
--
--   1. 商品マスタ — every line's product is registered or brought up to date
--      by its JAN: our name, the English standard name, maker, 品番, unit, and
--      what this supplier calls it (supplier_product_names). Nothing is
--      written unless every line passes: a line without a valid JAN or a
--      name, or a JAN twice in the file, stops the whole file
--      (`master_import_commit` answers with the problems and changes
--      nothing). The screen then offers the other ways: correct the lines by
--      hand, or have the reading turned into an Excel sheet, check it, and
--      send that back. The original file and every converted or corrected
--      sheet are kept with the import and can be downloaded again.
--   2. 在庫 — once the master is through, each line's quantity is added to
--      that product's stock in the chosen warehouse, found by JAN. The stock
--      already there is shown first and can be corrected by hand before the
--      quantity is added. For every line the import keeps the stock it found,
--      the corrected figure, what was added and what it came to.
--
-- Both stages go through the ledger (apply_stock_movement_detail, ADJUST)
-- and stock_adjustments, so before + quantity = after still holds and the
-- stock_units projection follows. `stock_set_on_hand` corrects one product's
-- stock to a figure by hand at any time, the same way.

insert into storage.buckets (id, name, public, file_size_limit)
values ('master-import-files', 'master-import-files', false, 52428800)
on conflict (id) do nothing;

create table if not exists public.master_imports (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies (id),
  status text not null default 'reading'
    check (status in ('reading', 'stopped', 'master_done', 'stock_done', 'cancelled')),
  source text,
  supplier_id bigint references public.delivery_suppliers (id) on delete set null,
  warehouse_id bigint references public.warehouses (id),
  document_id bigint,
  original_name text,
  original_path text,
  original_type text,
  converted_name text,
  converted_path text,
  corrected_name text,
  corrected_path text,
  line_count integer not null default 0,
  issues jsonb not null default '[]'::jsonb,
  master_created integer not null default 0,
  master_updated integer not null default 0,
  master_mapped integer not null default 0,
  stock_lines integer not null default 0,
  stock_added integer not null default 0,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  master_at timestamptz,
  master_by uuid,
  stock_at timestamptz,
  stock_by uuid,
  updated_at timestamptz not null default now()
);
create index if not exists master_imports_created_idx on public.master_imports (created_at desc);

create table if not exists public.master_import_lines (
  id bigint generated by default as identity primary key,
  import_id bigint not null references public.master_imports (id) on delete cascade,
  line_no integer not null,
  jan_code text not null,
  product_id bigint references public.products (id) on delete set null,
  supplier_name text,
  name_en text,
  quantity integer not null default 0,
  master_status text check (master_status in ('new', 'updated')),
  -- Stage 2: the stock as found, as corrected by hand, what was added, and
  -- what it came to. Null until the stock is put in.
  on_hand_before integer,
  on_hand_set integer,
  added integer,
  on_hand_after integer,
  movement_ids bigint[] not null default '{}',
  created_at timestamptz not null default now(),
  unique (import_id, line_no)
);
create index if not exists master_import_lines_product_idx on public.master_import_lines (product_id);

alter table public.master_imports enable row level security;
alter table public.master_import_lines enable row level security;

create or replace function public.master_import_viewer()
returns boolean language sql stable security definer set search_path = '' as $$
  select public.has_permission('product.manage') or public.has_permission('product.view')
      or public.has_permission('inventory.adjust') or public.has_permission('inventory.view');
$$;
revoke all on function public.master_import_viewer() from public, anon;
grant execute on function public.master_import_viewer() to authenticated, service_role;

do $$
begin
  create policy "master_imports: viewers read" on public.master_imports
    for select to authenticated using (public.master_import_viewer());
exception when duplicate_object then null;
end $$;
do $$
begin
  create policy "master_import_lines: viewers read" on public.master_import_lines
    for select to authenticated using (public.master_import_viewer());
exception when duplicate_object then null;
end $$;
-- No write policies: every change goes through the functions below.

do $$
begin
  create policy "master-import-files: managers upload" on storage.objects
    for insert to authenticated
    with check (bucket_id = 'master-import-files' and public.has_permission('product.manage'));
exception when duplicate_object then null;
end $$;
do $$
begin
  create policy "master-import-files: viewers read" on storage.objects
    for select to authenticated
    using (bucket_id = 'master-import-files' and public.master_import_viewer());
exception when duplicate_object then null;
end $$;

comment on table public.master_imports is
  'One file through 商品マスタ then stock (0138): its files, what stopped it, and what each stage did.';
comment on table public.master_import_lines is
  'A line of a master/stock import (0138): its product, quantity, and the stock before, as corrected, added and after.';

-- ------------------------------------------------------------ the import
create or replace function public.master_import_start(
  p_original_name text, p_original_type text default null, p_source text default null,
  p_document_id bigint default null, p_supplier_id bigint default null)
returns bigint
language plpgsql security definer set search_path = '' as $$
declare
  v_id bigint;
begin
  if not public.has_permission('product.manage') then
    raise exception 'not permitted: product.manage required';
  end if;
  insert into public.master_imports (company_id, original_name, original_type, source, document_id, supplier_id)
  values ((select id from public.companies order by id limit 1), public.tidy_text(p_original_name),
          public.tidy_text(p_original_type), public.tidy_text(p_source), p_document_id, p_supplier_id)
  returning id into v_id;
  return v_id;
end;
$$;

-- A file kept with the import: the one chosen, the sheet the reading was
-- turned into, or the sheet a person corrected and sent back.
create or replace function public.master_import_attach(p_id bigint, p_kind text, p_name text, p_path text)
returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not public.has_permission('product.manage') then
    raise exception 'not permitted: product.manage required';
  end if;
  if p_kind not in ('original', 'converted', 'corrected') then
    raise exception 'unknown file kind %', p_kind;
  end if;
  if p_path is null or p_path not like 'imports/' || p_id || '/%' then
    raise exception 'the file must be kept under imports/%/', p_id;
  end if;
  update public.master_imports set
    original_name = case when p_kind = 'original' then coalesce(public.tidy_text(p_name), original_name) else original_name end,
    original_path = case when p_kind = 'original' then p_path else original_path end,
    converted_name = case when p_kind = 'converted' then public.tidy_text(p_name) else converted_name end,
    converted_path = case when p_kind = 'converted' then p_path else converted_path end,
    corrected_name = case when p_kind = 'corrected' then public.tidy_text(p_name) else corrected_name end,
    corrected_path = case when p_kind = 'corrected' then p_path else corrected_path end,
    updated_at = now()
   where id = p_id and status in ('reading', 'stopped');
  if not found then
    raise exception 'import % not found or already registered', p_id;
  end if;
  return true;
end;
$$;

-- Stopped before anything was written: what was wrong, kept on the import.
create or replace function public.master_import_stop(p_id bigint, p_issues jsonb, p_line_count integer default null)
returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not public.has_permission('product.manage') then
    raise exception 'not permitted: product.manage required';
  end if;
  update public.master_imports set
    status = 'stopped',
    issues = case when jsonb_typeof(p_issues) = 'array' then p_issues else '[]'::jsonb end,
    line_count = coalesce(p_line_count, line_count),
    updated_at = now()
   where id = p_id and status in ('reading', 'stopped');
  return found;
end;
$$;

create or replace function public.master_import_cancel(p_id bigint)
returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not public.has_permission('product.manage') then
    raise exception 'not permitted: product.manage required';
  end if;
  update public.master_imports set status = 'cancelled', updated_at = now()
   where id = p_id and status in ('reading', 'stopped');
  return found;
end;
$$;

-- The imports, newest first, with their files and what each stage did.
create or replace function public.master_imports_list(p_limit integer default 50)
returns jsonb
language sql stable security definer set search_path = '' as $$
  select case when not public.master_import_viewer() then '[]'::jsonb else coalesce((
    select jsonb_agg(to_jsonb(x) order by x.created_at desc, x.id desc)
      from (select m.id, m.status, m.source, m.supplier_id, s.name as supplier_name, m.warehouse_id,
                   w.name as warehouse_name, m.original_name, m.original_path, m.converted_name, m.converted_path,
                   m.corrected_name, m.corrected_path, m.line_count, m.issues, m.master_created, m.master_updated,
                   m.master_mapped, m.stock_lines, m.stock_added, m.created_at, m.master_at, m.stock_at,
                   (select coalesce(u.name, u.email) from public.app_users u where u.id = m.created_by) as created_by_name
              from public.master_imports m
              left join public.delivery_suppliers s on s.id = m.supplier_id
              left join public.warehouses w on w.id = m.warehouse_id
             order by m.created_at desc, m.id desc
             limit greatest(1, least(coalesce(p_limit, 50), 200))) x), '[]'::jsonb) end;
$$;

-- One import with its lines; with a warehouse, each line also carries the
-- stock that product has there now (for the second stage).
create or replace function public.master_import_detail(p_id bigint, p_warehouse_id bigint default null)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare
  v_head jsonb;
begin
  if not public.master_import_viewer() then
    raise exception 'not permitted: product.view required';
  end if;
  if p_warehouse_id is not null and not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  select to_jsonb(m) - 'company_id' into v_head from public.master_imports m where m.id = p_id;
  if v_head is null then
    raise exception 'import % not found', p_id;
  end if;
  return v_head || jsonb_build_object('lines', coalesce((
    select jsonb_agg(jsonb_build_object(
             'line_no', l.line_no, 'jan_code', l.jan_code, 'product_id', l.product_id,
             -- The name comes from 商品マスタ, not from the file.
             'name', p.name, 'name_en', p.name_en, 'maker', p.maker, 'sku', p.sku,
             'supplier_name', l.supplier_name, 'quantity', l.quantity, 'master_status', l.master_status,
             'on_hand_before', l.on_hand_before, 'on_hand_set', l.on_hand_set, 'added', l.added,
             'on_hand_after', l.on_hand_after,
             'on_hand_now', case when p_warehouse_id is null then null else coalesce((
                select sl.on_hand from public.stock_levels sl
                 where sl.warehouse_id = p_warehouse_id and sl.jan_code = l.jan_code), 0) end)
           order by l.line_no)
      from public.master_import_lines l
      left join public.products p on p.id = l.product_id
     where l.import_id = p_id), '[]'::jsonb));
end;
$$;

revoke all on function public.master_import_start(text, text, text, bigint, bigint) from public, anon;
revoke all on function public.master_import_attach(bigint, text, text, text) from public, anon;
revoke all on function public.master_import_stop(bigint, jsonb, integer) from public, anon;
revoke all on function public.master_import_cancel(bigint) from public, anon;
revoke all on function public.master_imports_list(integer) from public, anon;
revoke all on function public.master_import_detail(bigint, bigint) from public, anon;
grant execute on function public.master_import_start(text, text, text, bigint, bigint) to authenticated, service_role;
grant execute on function public.master_import_attach(bigint, text, text, text) to authenticated, service_role;
grant execute on function public.master_import_stop(bigint, jsonb, integer) to authenticated, service_role;
grant execute on function public.master_import_cancel(bigint) to authenticated, service_role;
grant execute on function public.master_imports_list(integer) to authenticated, service_role;
grant execute on function public.master_import_detail(bigint, bigint) to authenticated, service_role;

-- ------------------------------------------------------------ stage 1
-- What would stop a file: every problem of every line, nothing written.
-- Codes: jan_missing, jan_invalid, jan_duplicate, name_missing, qty_invalid.
create or replace function public.master_import_problems(p_lines jsonb)
returns jsonb
language plpgsql stable set search_path = '' as $$
declare
  e jsonb;
  v_no int := 0;
  v_jan text;
  v_raw text;
  v_qty text;
  v_seen text[] := '{}';
  v_out jsonb := '[]'::jsonb;
begin
  for e in select * from jsonb_array_elements(case when jsonb_typeof(p_lines) = 'array' then p_lines else '[]'::jsonb end) loop
    v_no := coalesce(nullif(e->>'line_no', '')::int, v_no + 1);
    v_raw := public.tidy_text(coalesce(nullif(e->>'jan_code', ''), e->>'raw_jan_code'));
    v_jan := public.normalize_jan(v_raw);
    if v_raw is null then
      v_out := v_out || jsonb_build_object('line_no', v_no, 'code', 'jan_missing');
    elsif length(coalesce(v_jan, '')) not in (8, 13) or not public.jan_check_ok(v_jan) then
      v_out := v_out || jsonb_build_object('line_no', v_no, 'code', 'jan_invalid', 'value', v_raw);
    elsif v_jan = any(v_seen) then
      v_out := v_out || jsonb_build_object('line_no', v_no, 'code', 'jan_duplicate', 'value', v_jan);
    end if;
    if v_jan is not null then v_seen := v_seen || v_jan; end if;
    if coalesce(public.tidy_text(e->>'supplier_name'), public.tidy_text(e->>'name'),
                public.tidy_text(e->>'product_name')) is null then
      v_out := v_out || jsonb_build_object('line_no', v_no, 'code', 'name_missing');
    end if;
    v_qty := btrim(coalesce(e->>'quantity', ''));
    if v_qty <> '' and (v_qty !~ '^\d+$') then
      v_out := v_out || jsonb_build_object('line_no', v_no, 'code', 'qty_invalid', 'value', v_qty);
    end if;
  end loop;
  return v_out;
end;
$$;
grant execute on function public.master_import_problems(jsonb) to authenticated, service_role;

-- Stage 1: the file's products into 商品マスタ, all or nothing. A line is
-- {line_no, jan_code, supplier_name, name?, name_en?, maker?, product_code?,
-- supplier_code?, spec?, unit?, list_price?, quantity?, attributes?}.
--   * A JAN we have: the product keeps its name; the English name is set when
--     the line gives one, and maker / 品番 / unit / spec fill what is empty.
--   * A JAN we do not have: a product is made, named as the line says (our
--     name when given, else the supplier's), with its English name.
--   * With a supplier, what it calls the product is kept for it
--     (supplier_product_names), so its next file is recognised.
-- Any problem (`master_import_problems`) stops the file: nothing is written
-- and the problems come back with ok = false.
create or replace function public.master_import_commit(p_id bigint, p_lines jsonb, p_supplier_id bigint default null)
returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_imp public.master_imports;
  v_problems jsonb;
  e jsonb;
  v_no int := 0;
  v_jan text;
  v_pid bigint;
  v_name text;
  v_sup_name text;
  v_en text;
  v_code text;
  v_sup_code text;
  v_qty int;
  v_new boolean;
  v_created int := 0;
  v_updated int := 0;
  v_mapped int := 0;
  v_company bigint;
  v_supplier bigint;
  v_out jsonb := '[]'::jsonb;
begin
  if not public.has_permission('product.manage') then
    raise exception 'not permitted: product.manage required';
  end if;
  select * into v_imp from public.master_imports where id = p_id for update;
  if v_imp.id is null then
    raise exception 'import % not found', p_id;
  end if;
  if v_imp.status not in ('reading', 'stopped') then
    raise exception 'import % is already registered', p_id;
  end if;
  if jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) = 0 then
    v_problems := jsonb_build_array(jsonb_build_object('line_no', 0, 'code', 'no_lines'));
  else
    v_problems := public.master_import_problems(p_lines);
  end if;
  if jsonb_array_length(v_problems) > 0 then
    update public.master_imports set status = 'stopped', issues = v_problems,
           line_count = coalesce(jsonb_array_length(case when jsonb_typeof(p_lines) = 'array' then p_lines end), 0),
           updated_at = now()
     where id = p_id;
    return jsonb_build_object('ok', false, 'problems', v_problems);
  end if;

  select id into v_company from public.companies order by id limit 1;
  -- The UNKNOWN placeholder is nobody's: nothing is learned for it.
  select s.id into v_supplier from public.delivery_suppliers s
   where s.id = coalesce(p_supplier_id, v_imp.supplier_id) and coalesce(s.code, '') <> 'UNKNOWN';

  for e in select * from jsonb_array_elements(p_lines) loop
    v_no := coalesce(nullif(e->>'line_no', '')::int, v_no + 1);
    v_jan := public.normalize_jan(public.tidy_text(coalesce(nullif(e->>'jan_code', ''), e->>'raw_jan_code')));
    v_sup_name := coalesce(public.tidy_text(e->>'supplier_name'), public.tidy_text(e->>'product_name'));
    v_name := coalesce(public.tidy_text(e->>'name'), v_sup_name);
    v_sup_name := coalesce(v_sup_name, v_name);
    v_en := public.tidy_text(e->>'name_en');
    v_code := public.tidy_text(e->>'product_code');
    v_sup_code := coalesce(public.tidy_text(e->>'supplier_code'), v_code);
    v_qty := coalesce(nullif(btrim(coalesce(e->>'quantity', '')), '')::int, 0);

    select id into v_pid from public.products where company_id = v_company and jan_code = v_jan;
    v_new := v_pid is null;
    if v_new then
      -- A 品番 another product already carries stays with the supplier's
      -- writing only.
      if v_code is not null and exists (select 1 from public.products where company_id = v_company and sku = v_code) then
        v_code := null;
      end if;
      v_pid := public.product_insert_from(
        (e - 'product_code' - 'sku') || jsonb_build_object('product_name', v_name, 'product_code', v_code),
        v_jan, 'file', v_imp.original_name);
      if v_en is not null then
        update public.products set name_en = v_en where id = v_pid;
      end if;
      v_created := v_created + 1;
    else
      update public.products p set
        name_en = coalesce(v_en, p.name_en),
        maker = coalesce(p.maker, public.tidy_text(e->>'maker')),
        sku = coalesce(p.sku, case when v_code is not null and not exists (
                 select 1 from public.products o where o.company_id = v_company and o.sku = v_code and o.id <> p.id)
               then v_code end),
        unit = coalesce(p.unit, public.tidy_text(e->>'unit')),
        base_name = coalesce(p.base_name, public.tidy_text(e->>'base_name')),
        list_price = coalesce(p.list_price, nullif(e->>'list_price', '')::numeric),
        updated_at = now()
       where p.id = v_pid;
      perform public.product_put_attributes(v_pid, e->'attributes');
      v_updated := v_updated + 1;
    end if;

    if v_supplier is not null and v_sup_name is not null then
      if v_sup_code is not null and exists (
           select 1 from public.supplier_product_names
            where supplier_id = v_supplier and supplier_code = v_sup_code and product_id <> v_pid) then
        v_sup_code := null;
      end if;
      insert into public.supplier_product_names
        (supplier_id, product_id, supplier_code, supplier_name, supplier_jan_code, supplier_maker,
         supplier_unit, source, last_seen_at, seen_count)
      values (v_supplier, v_pid, v_sup_code, v_sup_name, v_jan, public.tidy_text(e->>'maker'),
              public.tidy_text(e->>'unit'), 'file', now(), 1)
      on conflict (supplier_id, product_id) do update set
        supplier_name = excluded.supplier_name,
        supplier_code = coalesce(excluded.supplier_code, public.supplier_product_names.supplier_code),
        supplier_jan_code = coalesce(public.supplier_product_names.supplier_jan_code, excluded.supplier_jan_code),
        supplier_maker = coalesce(public.supplier_product_names.supplier_maker, excluded.supplier_maker),
        supplier_unit = coalesce(excluded.supplier_unit, public.supplier_product_names.supplier_unit),
        last_seen_at = now(),
        seen_count = public.supplier_product_names.seen_count + 1,
        is_active = true,
        updated_at = now();
      v_mapped := v_mapped + 1;
    end if;

    insert into public.master_import_lines
      (import_id, line_no, jan_code, product_id, supplier_name, name_en, quantity, master_status)
    values (p_id, v_no, v_jan, v_pid, v_sup_name, v_en, v_qty, case when v_new then 'new' else 'updated' end);
    v_out := v_out || jsonb_build_object('line_no', v_no, 'jan_code', v_jan, 'product_id', v_pid,
                                         'status', case when v_new then 'new' else 'updated' end);
  end loop;

  update public.master_imports set
    status = 'master_done', issues = '[]'::jsonb, supplier_id = coalesce(v_supplier, supplier_id),
    line_count = jsonb_array_length(p_lines),
    master_created = v_created, master_updated = v_updated, master_mapped = v_mapped,
    master_at = now(), master_by = auth.uid(), updated_at = now()
   where id = p_id;
  perform public.log_audit('product.master_imported', 'master_import', p_id::text, null,
    jsonb_build_object('created', v_created, 'updated', v_updated, 'mapped', v_mapped,
                       'file', v_imp.original_name));
  return jsonb_build_object('ok', true, 'created', v_created, 'updated', v_updated, 'mapped', v_mapped,
                            'lines', v_out);
end;
$$;
revoke all on function public.master_import_commit(bigint, jsonb, bigint) from public, anon;
grant execute on function public.master_import_commit(bigint, jsonb, bigint) to authenticated, service_role;

-- ------------------------------------------------------------ stock
-- One ledger posting with its reason, as a stock adjustment. Internal.
create or replace function public.master_import_post(
  p_warehouse_id bigint, p_jan text, p_product_id bigint, p_delta integer, p_reason text, p_note text,
  p_reference text, p_name text)
returns bigint
language plpgsql security definer set search_path = '' as $$
declare
  v_mov bigint;
  v_after integer;
begin
  if coalesce(p_delta, 0) = 0 then
    return null;
  end if;
  v_mov := public.apply_stock_movement_detail(
    p_warehouse_id, p_jan, p_delta, 'ADJUST', 'master_import', p_reference, p_name, null, p_note,
    null, null, null, p_product_id);
  if v_mov is null then
    return null;
  end if;
  select quantity_after into v_after from public.stock_movements where id = v_mov;
  insert into public.stock_adjustments
    (company_id, warehouse_id, jan_code, product_name, quantity_delta, reason, note, movement_id, actor_user_id)
  values ((select id from public.companies order by id limit 1), p_warehouse_id, p_jan, p_name, p_delta,
          p_reason, p_note, v_mov, auth.uid());
  return v_mov;
end;
$$;
revoke all on function public.master_import_post(bigint, text, bigint, integer, text, text, text, text)
  from public, anon, authenticated;

-- Stage 2: each line's quantity onto its product's stock in the warehouse.
-- p_lines: [{line_no, quantity?, on_hand_set?}] — a quantity changes what
-- the file said; on_hand_set corrects the stock already there before the
-- quantity is added. Lines not given are added as the file said.
create or replace function public.master_import_apply_stock(p_id bigint, p_warehouse_id bigint, p_lines jsonb default '[]'::jsonb)
returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_imp public.master_imports;
  l record;
  e jsonb;
  v_before int;
  v_set int;
  v_base int;
  v_qty int;
  v_after int;
  v_name text;
  v_m1 bigint;
  v_m2 bigint;
  v_lines int := 0;
  v_added int := 0;
  v_out jsonb := '[]'::jsonb;
begin
  if not public.has_permission('inventory.adjust') then
    raise exception 'not permitted: inventory.adjust required';
  end if;
  if p_warehouse_id is null or not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  select * into v_imp from public.master_imports where id = p_id for update;
  if v_imp.id is null then
    raise exception 'import % not found', p_id;
  end if;
  if v_imp.status = 'stock_done' then
    raise exception 'the stock of import % is already in', p_id;
  end if;
  if v_imp.status <> 'master_done' then
    raise exception 'register import % in 商品マスタ first', p_id;
  end if;

  for l in select * from public.master_import_lines where import_id = p_id order by line_no loop
    select x.value into e
      from jsonb_array_elements(case when jsonb_typeof(p_lines) = 'array' then p_lines else '[]'::jsonb end) as x(value)
     where (x.value->>'line_no')::int = l.line_no limit 1;
    v_qty := coalesce(nullif(btrim(coalesce(e->>'quantity', '')), '')::int, l.quantity);
    v_set := nullif(btrim(coalesce(e->>'on_hand_set', '')), '')::int;
    if v_qty < 0 or v_set < 0 then
      raise exception 'line %: a quantity cannot be negative', l.line_no;
    end if;
    select name into v_name from public.products where id = l.product_id;
    select on_hand into v_before from public.stock_levels
     where warehouse_id = p_warehouse_id and jan_code = l.jan_code for update;
    v_before := coalesce(v_before, 0);
    v_base := coalesce(v_set, v_before);
    v_m1 := public.master_import_post(p_warehouse_id, l.jan_code, l.product_id, v_base - v_before, 'CORRECTION',
      '既存在庫を手動で修正（ファイル取込 #' || p_id || '）', p_id::text, v_name);
    v_m2 := public.master_import_post(p_warehouse_id, l.jan_code, l.product_id, v_qty, 'OTHER',
      'ファイル取込 #' || p_id || ' で追加', p_id::text, v_name);
    v_after := v_base + v_qty;
    -- 商品ライブラリー shows the name 商品マスタ gives.
    update public.stock_levels set product_name = coalesce(v_name, product_name), product_id = coalesce(product_id, l.product_id)
     where warehouse_id = p_warehouse_id and jan_code = l.jan_code;
    update public.master_import_lines set
      on_hand_before = v_before, on_hand_set = v_set, added = v_qty, on_hand_after = v_after,
      quantity = v_qty, movement_ids = array_remove(array[v_m1, v_m2], null)
     where id = l.id;
    v_lines := v_lines + 1;
    v_added := v_added + v_qty;
    v_out := v_out || jsonb_build_object('line_no', l.line_no, 'jan_code', l.jan_code, 'before', v_before,
                                         'set', v_set, 'added', v_qty, 'after', v_after);
  end loop;

  update public.master_imports set status = 'stock_done', warehouse_id = p_warehouse_id,
         stock_lines = v_lines, stock_added = v_added, stock_at = now(), stock_by = auth.uid(), updated_at = now()
   where id = p_id;
  perform public.log_audit('inventory.master_import_stocked', 'master_import', p_id::text, p_warehouse_id,
    jsonb_build_object('lines', v_lines, 'added', v_added));
  return jsonb_build_object('lines', v_lines, 'added', v_added, 'detail', v_out);
end;
$$;
revoke all on function public.master_import_apply_stock(bigint, bigint, jsonb) from public, anon;
grant execute on function public.master_import_apply_stock(bigint, bigint, jsonb) to authenticated, service_role;

-- One product's stock in a warehouse, set to a figure by hand.
create or replace function public.stock_set_on_hand(
  p_warehouse_id bigint, p_jan_code text, p_quantity integer, p_note text default null)
returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_jan text := public.normalize_jan(public.tidy_text(p_jan_code));
  v_before int;
  v_pid bigint;
  v_name text;
  v_mov bigint;
begin
  if not public.has_permission('inventory.adjust') then
    raise exception 'not permitted: inventory.adjust required';
  end if;
  if p_warehouse_id is null or not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  if v_jan is null or p_quantity is null or p_quantity < 0 then
    raise exception 'a JAN and a quantity of 0 or more are required';
  end if;
  select id, name into v_pid, v_name from public.products where jan_code = v_jan limit 1;
  select on_hand into v_before from public.stock_levels
   where warehouse_id = p_warehouse_id and jan_code = v_jan for update;
  v_before := coalesce(v_before, 0);
  v_mov := public.master_import_post(p_warehouse_id, v_jan, v_pid, p_quantity - v_before, 'CORRECTION',
    coalesce(public.tidy_text(p_note), '在庫数を手動で変更'), null, v_name);
  if v_mov is not null then
    perform public.log_audit('inventory.on_hand_set', 'stock_level', v_jan, p_warehouse_id,
      jsonb_build_object('before', v_before, 'after', p_quantity, 'note', public.tidy_text(p_note)));
  end if;
  return jsonb_build_object('jan_code', v_jan, 'before', v_before, 'after', p_quantity, 'movement_id', v_mov);
end;
$$;
revoke all on function public.stock_set_on_hand(bigint, text, integer, text) from public, anon;
grant execute on function public.stock_set_on_hand(bigint, text, integer, text) to authenticated, service_role;
