-- 0139 — 出庫の提案: an outbound worked out from the stock, to a saved
-- destination, and sheets to send.
--
--   * `ship_destinations`: the companies and addresses goods often go to
--     (会社名, 部署, 担当, 〒, 住所, 電話, メール, 国), kept so a shipment picks
--     one instead of typing it again. The most used come first.
--   * `outbound_stock(warehouse)`: what each product has in a warehouse — on
--     hand, reserved, already on open shipments, and what is free to send.
--     The screen proposes quantities from it: a percentage of the stock (or of
--     what is free), or a quantity typed per product.
--   * `outbound_create(...)`: the proposal becomes an open shipment
--     (shipment_plans / shipment_lines, number OUT-000123) with its
--     destination kept as it was at the time (`ship_to`). It then goes through
--     packing and shipping like any other; stock moves when it ships. No line
--     may ask for more than is free.
--   * `outbound_sheet(shipment)`: a shipment's destination and lines, for the
--     Excel sheet sent to the other company — any shipment, imported or not.
--   * `stock_export(warehouse)`: every product's stock in the warehouses the
--     caller may see, for the stock list in Excel.

create table if not exists public.ship_destinations (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies (id),
  party_id bigint references public.delivery_suppliers (id) on delete set null,
  name text not null check (btrim(name) <> ''),
  department text,
  contact_name text,
  postal_code text,
  address1 text,
  address2 text,
  phone text,
  email text,
  country_code text,
  note text,
  use_count integer not null default 0,
  last_used_at timestamptz,
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ship_destinations_used_idx
  on public.ship_destinations (status, last_used_at desc nulls last, use_count desc);

alter table public.ship_destinations enable row level security;

create or replace function public.outbound_can_view()
returns boolean language sql stable security definer set search_path = '' as $$
  select public.has_permission('pack.complete') or public.has_permission('ship.complete')
      or public.has_permission('sales_order.view') or public.has_permission('sales_order.manage')
      or public.has_permission('inventory.view');
$$;
create or replace function public.outbound_can_edit()
returns boolean language sql stable security definer set search_path = '' as $$
  select public.has_permission('pack.complete') or public.has_permission('ship.complete')
      or public.has_permission('sales_order.manage');
$$;
revoke all on function public.outbound_can_view() from public, anon;
revoke all on function public.outbound_can_edit() from public, anon;
grant execute on function public.outbound_can_view() to authenticated, service_role;
grant execute on function public.outbound_can_edit() to authenticated, service_role;

do $$
begin
  create policy "ship_destinations: shippers read" on public.ship_destinations
    for select to authenticated using (public.outbound_can_view());
exception when duplicate_object then null;
end $$;
-- No write policies: saved through the functions below.

comment on table public.ship_destinations is
  'Saved ship-to destinations (0139): company, department, contact, address, phone. The most used come first.';

alter table public.shipment_plans
  add column if not exists destination_id bigint references public.ship_destinations (id) on delete set null,
  add column if not exists ship_to jsonb,
  add column if not exists proposal jsonb,
  add column if not exists note text;

comment on column public.shipment_plans.ship_to is
  'The destination as it was when the shipment was made (0139): name, department, contact, postal_code, address1, address2, phone, email, country_code.';

-- ------------------------------------------------------------ destinations
create or replace function public.ship_destinations_list(p_search text default null)
returns jsonb
language sql stable security definer set search_path = '' as $$
  select case when not public.outbound_can_view() then '[]'::jsonb else coalesce((
    select jsonb_agg(to_jsonb(d) - 'company_id' order by d.last_used_at desc nulls last, d.use_count desc, d.name)
      from public.ship_destinations d
     where d.status = 'active'
       and (nullif(btrim(coalesce(p_search, '')), '') is null
            or concat_ws(' ', d.name, d.department, d.contact_name, d.postal_code, d.address1, d.address2, d.phone)
               ilike '%' || btrim(p_search) || '%')), '[]'::jsonb) end;
$$;

-- Saves one: a new one without an id, else changes the one with it.
create or replace function public.ship_destination_save(p jsonb)
returns bigint
language plpgsql security definer set search_path = '' as $$
declare
  v_id bigint := nullif(p->>'id', '')::bigint;
  v_name text := public.tidy_text(p->>'name');
begin
  if not public.outbound_can_edit() then
    raise exception 'not permitted: pack.complete required';
  end if;
  if v_name is null then
    raise exception 'a company name is required';
  end if;
  if v_id is null then
    insert into public.ship_destinations
      (company_id, party_id, name, department, contact_name, postal_code, address1, address2, phone, email,
       country_code, note)
    values ((select id from public.companies order by id limit 1), nullif(p->>'party_id', '')::bigint, v_name,
            public.tidy_text(p->>'department'), public.tidy_text(p->>'contact_name'), public.tidy_text(p->>'postal_code'),
            public.tidy_text(p->>'address1'), public.tidy_text(p->>'address2'), public.tidy_text(p->>'phone'),
            public.tidy_text(p->>'email'), upper(public.tidy_text(p->>'country_code')), public.tidy_text(p->>'note'))
    returning id into v_id;
    perform public.log_audit('ship_destination.created', 'ship_destination', v_id::text, null,
      jsonb_build_object('name', v_name));
  else
    update public.ship_destinations set
      party_id = nullif(p->>'party_id', '')::bigint,
      name = v_name,
      department = public.tidy_text(p->>'department'),
      contact_name = public.tidy_text(p->>'contact_name'),
      postal_code = public.tidy_text(p->>'postal_code'),
      address1 = public.tidy_text(p->>'address1'),
      address2 = public.tidy_text(p->>'address2'),
      phone = public.tidy_text(p->>'phone'),
      email = public.tidy_text(p->>'email'),
      country_code = upper(public.tidy_text(p->>'country_code')),
      note = public.tidy_text(p->>'note'),
      updated_at = now()
     where id = v_id and status = 'active';
    if not found then
      raise exception 'destination % not found', v_id;
    end if;
    perform public.log_audit('ship_destination.updated', 'ship_destination', v_id::text, null,
      jsonb_build_object('name', v_name));
  end if;
  return v_id;
end;
$$;

-- Taken off the list; shipments that went there keep their address.
create or replace function public.ship_destination_retire(p_id bigint)
returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not public.outbound_can_edit() then
    raise exception 'not permitted: pack.complete required';
  end if;
  update public.ship_destinations set status = 'inactive', updated_at = now() where id = p_id and status = 'active';
  if found then
    perform public.log_audit('ship_destination.retired', 'ship_destination', p_id::text, null, '{}'::jsonb);
  end if;
  return found;
end;
$$;

revoke all on function public.ship_destinations_list(text) from public, anon;
revoke all on function public.ship_destination_save(jsonb) from public, anon;
revoke all on function public.ship_destination_retire(bigint) from public, anon;
grant execute on function public.ship_destinations_list(text) to authenticated, service_role;
grant execute on function public.ship_destination_save(jsonb) to authenticated, service_role;
grant execute on function public.ship_destination_retire(bigint) to authenticated, service_role;

-- ------------------------------------------------------------ stock
-- One warehouse's stock, product by product: on hand, reserved, already on
-- shipments that have not shipped, and what is free to send.
create or replace function public.outbound_stock(p_warehouse_id bigint)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.outbound_can_view() then
    raise exception 'not permitted: inventory.view required';
  end if;
  if p_warehouse_id is null or not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  return coalesce((
    select jsonb_agg(to_jsonb(x) order by x.name, x.jan_code)
      from (
        select s.jan_code, p.id as product_id,
               coalesce(nullif(p.name, ''), nullif(s.product_name, ''), s.jan_code) as name,
               p.name_en, p.maker, p.sku, p.unit,
               s.on_hand,
               r.reserved,
               o.in_open,
               greatest(s.on_hand - r.reserved - o.in_open, 0) as free
          from public.stock_levels s
          left join public.products p on p.id = coalesce(s.product_id,
                    (select pp.id from public.products pp where pp.jan_code = s.jan_code limit 1))
          cross join lateral (
            select case when p.id is null then 0 else coalesce(public.stock_reserved(p.id, p_warehouse_id), 0) end as reserved
          ) r
          cross join lateral (
            select coalesce(sum(l.quantity), 0)::int as in_open
              from public.shipment_lines l
              join public.shipment_plans sp on sp.id = l.shipment_plan_id
             where sp.warehouse_id = p_warehouse_id and sp.status not in ('shipped', 'cancelled')
               and l.jan_code = s.jan_code
          ) o
         where s.warehouse_id = p_warehouse_id and s.on_hand > 0
      ) x), '[]'::jsonb);
end;
$$;
revoke all on function public.outbound_stock(bigint) from public, anon;
grant execute on function public.outbound_stock(bigint) to authenticated, service_role;

-- ------------------------------------------------------------ shipment
-- The proposal as an open shipment. p_lines: [{jan_code, quantity}]; a line
-- over what is free stops the whole shipment ("over_free:<jan>:<free>").
-- p_ship_to overrides the saved destination's fields for this shipment only.
create or replace function public.outbound_create(
  p_warehouse_id bigint,
  p_lines jsonb,
  p_destination_id bigint default null,
  p_ship_to jsonb default null,
  p_ship_date text default null,
  p_note text default null,
  p_proposal jsonb default null)
returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_dest public.ship_destinations;
  v_to jsonb;
  v_id bigint;
  v_no text;
  e jsonb;
  v_jan text;
  v_qty int;
  v_free int;
  v_pid bigint;
  v_name text;
  v_sku text;
  v_maker text;
  v_count int := 0;
  v_units int := 0;
  v_seen text[] := '{}';
begin
  if not public.outbound_can_edit() then
    raise exception 'not permitted: pack.complete required';
  end if;
  if p_warehouse_id is null or not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  if p_destination_id is not null then
    select * into v_dest from public.ship_destinations where id = p_destination_id and status = 'active';
    if v_dest.id is null then
      raise exception 'destination % not found', p_destination_id;
    end if;
  end if;
  v_to := jsonb_strip_nulls(jsonb_build_object(
            'name', v_dest.name, 'department', v_dest.department, 'contact_name', v_dest.contact_name,
            'postal_code', v_dest.postal_code, 'address1', v_dest.address1, 'address2', v_dest.address2,
            'phone', v_dest.phone, 'email', v_dest.email, 'country_code', v_dest.country_code))
          || jsonb_strip_nulls(coalesce(case when jsonb_typeof(p_ship_to) = 'object' then p_ship_to end, '{}'::jsonb));
  if public.tidy_text(v_to->>'name') is null then
    raise exception 'a destination (company name) is required';
  end if;
  if jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) = 0 then
    raise exception 'no lines to ship';
  end if;

  insert into public.shipment_plans
    (shipment_number, party_id, customer_name, warehouse_id, ship_date, status, destination_id, ship_to, proposal, note)
  values ('', v_dest.party_id, v_to->>'name', p_warehouse_id, public.tidy_text(p_ship_date), 'open',
          v_dest.id, v_to, case when jsonb_typeof(p_proposal) = 'object' then p_proposal end, public.tidy_text(p_note))
  returning id into v_id;
  v_no := 'OUT-' || lpad(v_id::text, 6, '0');
  update public.shipment_plans set shipment_number = v_no where id = v_id;

  for e in select * from jsonb_array_elements(p_lines) loop
    v_jan := public.normalize_jan(public.tidy_text(e->>'jan_code'));
    v_qty := coalesce(nullif(btrim(coalesce(e->>'quantity', '')), '')::int, 0);
    continue when v_qty = 0;
    if v_qty < 0 then
      raise exception 'a quantity cannot be negative (%)', v_jan;
    end if;
    if v_jan is null or v_jan = any(v_seen) then
      raise exception 'line_jan:%', coalesce(v_jan, '');
    end if;
    v_seen := v_seen || v_jan;
    select pp.id, coalesce(nullif(pp.name, ''), nullif(sl.product_name, ''), v_jan), pp.sku, pp.maker,
           greatest(coalesce(sl.on_hand, 0)
                    - case when pp.id is null then 0 else coalesce(public.stock_reserved(pp.id, p_warehouse_id), 0) end
                    - coalesce((select sum(l.quantity) from public.shipment_lines l
                                  join public.shipment_plans sp on sp.id = l.shipment_plan_id
                                 where sp.warehouse_id = p_warehouse_id and sp.status not in ('shipped', 'cancelled')
                                   and sp.id <> v_id and l.jan_code = v_jan), 0), 0)
      into v_pid, v_name, v_sku, v_maker, v_free
      from (select 1) one
      left join public.stock_levels sl on sl.warehouse_id = p_warehouse_id and sl.jan_code = v_jan
      left join public.products pp on pp.id = coalesce(sl.product_id,
                (select x.id from public.products x where x.jan_code = v_jan limit 1));
    if v_qty > v_free then
      raise exception 'over_free:%:%', v_jan, v_free;
    end if;
    insert into public.shipment_lines (shipment_plan_id, jan_code, product_id, product_name, product_code, maker, quantity)
    values (v_id, v_jan, v_pid, coalesce(v_name, v_jan), v_sku, v_maker, v_qty);
    v_count := v_count + 1;
    v_units := v_units + v_qty;
  end loop;
  if v_count = 0 then
    raise exception 'no lines to ship';
  end if;

  if v_dest.id is not null then
    update public.ship_destinations set use_count = use_count + 1, last_used_at = now() where id = v_dest.id;
  end if;
  perform public.log_audit('shipment.proposed', 'shipment_plan', v_id::text, p_warehouse_id,
    jsonb_build_object('number', v_no, 'lines', v_count, 'units', v_units, 'destination', v_to->>'name',
                       'proposal', p_proposal));
  return jsonb_build_object('id', v_id, 'shipment_number', v_no, 'lines', v_count, 'units', v_units);
end;
$$;
revoke all on function public.outbound_create(bigint, jsonb, bigint, jsonb, text, text, jsonb) from public, anon;
grant execute on function public.outbound_create(bigint, jsonb, bigint, jsonb, text, text, jsonb) to authenticated, service_role;

-- A shipment's destination and lines, for the sheet sent to the other side.
create or replace function public.outbound_sheet(p_shipment_id bigint)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare
  v_plan public.shipment_plans;
  v_s public.delivery_suppliers;
begin
  if not public.outbound_can_view() then
    raise exception 'not permitted: pack.complete required';
  end if;
  select * into v_plan from public.shipment_plans where id = p_shipment_id;
  if v_plan.id is null then
    raise exception 'shipment % not found', p_shipment_id;
  end if;
  if not public.can_access_warehouse(v_plan.warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  select * into v_s from public.delivery_suppliers where id = v_plan.party_id;
  return jsonb_build_object(
    'id', v_plan.id, 'shipment_number', v_plan.shipment_number, 'status', v_plan.status,
    'ship_date', v_plan.ship_date, 'order_date', v_plan.order_date, 'doc_number', v_plan.doc_number,
    'note', v_plan.note, 'created_at', v_plan.created_at, 'shipped_at', v_plan.shipped_at,
    'carrier', v_plan.carrier, 'tracking_number', v_plan.tracking_number,
    'warehouse_name', (select w.name from public.warehouses w where w.id = v_plan.warehouse_id),
    'ship_to', coalesce(v_plan.ship_to, jsonb_strip_nulls(jsonb_build_object(
        'name', coalesce(v_plan.customer_name, v_s.name), 'address1', v_s.address, 'phone', v_s.phone,
        'email', v_s.email, 'contact_name', v_s.contact_name, 'country_code', v_s.country_code))),
    'lines', coalesce((
      select jsonb_agg(jsonb_build_object(
               'jan_code', l.jan_code, 'name', coalesce(p.name, l.product_name), 'name_en', p.name_en,
               'maker', coalesce(l.maker, p.maker), 'product_code', coalesce(l.product_code, p.sku),
               'unit', p.unit, 'quantity', l.quantity, 'unit_price', l.unit_price, 'amount', l.amount)
             order by l.id)
        from public.shipment_lines l
        left join public.products p on p.id = coalesce(l.product_id,
                  (select pp.id from public.products pp where pp.jan_code = l.jan_code limit 1))
       where l.shipment_plan_id = v_plan.id), '[]'::jsonb));
end;
$$;
revoke all on function public.outbound_sheet(bigint) from public, anon;
grant execute on function public.outbound_sheet(bigint) to authenticated, service_role;

-- Every product's stock in the warehouses the caller may see (or one).
create or replace function public.stock_export(p_warehouse_id bigint default null)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.has_permission('inventory.view') and not public.outbound_can_view() then
    raise exception 'not permitted: inventory.view required';
  end if;
  if p_warehouse_id is not null and not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  return coalesce((
    select jsonb_agg(to_jsonb(x) order by x.warehouse_name, x.name, x.jan_code)
      from (
        select w.id as warehouse_id, w.code as warehouse_code, w.name as warehouse_name,
               s.jan_code, p.id as product_id,
               coalesce(nullif(p.name, ''), nullif(s.product_name, ''), s.jan_code) as name,
               p.name_en, p.maker, p.sku, p.unit, s.on_hand,
               case when p.id is null then 0 else coalesce(public.stock_reserved(p.id, w.id), 0) end as reserved,
               s.updated_at
          from public.stock_levels s
          join public.warehouses w on w.id = s.warehouse_id
          left join public.products p on p.id = coalesce(s.product_id,
                    (select pp.id from public.products pp where pp.jan_code = s.jan_code limit 1))
         where (p_warehouse_id is null or s.warehouse_id = p_warehouse_id)
           and public.can_access_warehouse(s.warehouse_id)
           and s.on_hand <> 0
      ) x), '[]'::jsonb);
end;
$$;
revoke all on function public.stock_export(bigint) from public, anon;
grant execute on function public.stock_export(bigint) to authenticated, service_role;
