-- 0140 — 入荷希望リスト: what we would like to receive, worked out from the
-- product master and the stock, to ask a supplier whether they have it.
--
--   * `request_candidates(warehouse, supplier)`: every product in 商品マスタ
--     (not only those in stock), with its stock — in one warehouse, or in all
--     the caller may see — its min / reorder point / max for that warehouse,
--     and, when a supplier is chosen, what that supplier calls it and its
--     code for it (supplier_product_names). The screen sets quantities from
--     it in bulk (a percentage of the stock, the same number for all, or up to
--     the maximum stock) or by hand.
--   * `purchase_requests` / `purchase_request_lines`: a list kept to come
--     back to — the supplier is optional — numbered REQ-000001. A line can be
--     a product of ours or one typed by hand (a JAN, a name).
--   * `purchase_request_save(p)` saves a whole list as a new revision of
--     its lines (the earlier ones stay, as a history);
--     `purchase_requests_list()`, `purchase_request_get(id)`,
--     `purchase_request_remove(id)` (taken off the list, not erased).
-- Nothing here orders anything: the list is a question to the supplier,
-- downloaded as Excel.

create table if not exists public.purchase_requests (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies (id),
  request_number text not null default '',
  supplier_id bigint references public.delivery_suppliers (id) on delete set null,
  supplier_name text,
  warehouse_id bigint references public.warehouses (id) on delete set null,
  title text,
  note text,
  reply_by date,
  status text not null default 'draft' check (status in ('draft', 'sent', 'closed', 'removed')),
  settings jsonb,
  -- Each save is a revision; the lines of the current one are the list.
  revision integer not null default 1,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_by uuid,
  updated_at timestamptz not null default now()
);
create index if not exists purchase_requests_created_idx on public.purchase_requests (created_at desc);

create table if not exists public.purchase_request_lines (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.purchase_requests (id) on delete cascade,
  line_no integer not null,
  product_id bigint references public.products (id) on delete set null,
  jan_code text,
  name text not null check (btrim(name) <> ''),
  name_en text,
  maker text,
  sku text,
  supplier_code text,
  supplier_product_name text,
  unit text,
  quantity integer not null check (quantity > 0),
  on_hand integer,
  note text,
  revision integer not null default 1
);
create unique index if not exists purchase_request_lines_rev_key
  on public.purchase_request_lines (request_id, revision, line_no);

alter table public.purchase_requests enable row level security;
alter table public.purchase_request_lines enable row level security;

create or replace function public.purchase_request_can_view()
returns boolean language sql stable security definer set search_path = '' as $$
  select public.has_permission('purchase_order.view') or public.has_permission('purchase_order.manage')
      or public.has_permission('product.view') or public.has_permission('product.manage');
$$;
create or replace function public.purchase_request_can_edit()
returns boolean language sql stable security definer set search_path = '' as $$
  select public.has_permission('purchase_order.manage') or public.has_permission('product.manage');
$$;
revoke all on function public.purchase_request_can_view() from public, anon;
revoke all on function public.purchase_request_can_edit() from public, anon;
grant execute on function public.purchase_request_can_view() to authenticated, service_role;
grant execute on function public.purchase_request_can_edit() to authenticated, service_role;

do $$
begin
  create policy "purchase_requests: buyers read" on public.purchase_requests
    for select to authenticated using (public.purchase_request_can_view());
exception when duplicate_object then null;
end $$;
do $$
begin
  create policy "purchase_request_lines: buyers read" on public.purchase_request_lines
    for select to authenticated using (public.purchase_request_can_view());
exception when duplicate_object then null;
end $$;

comment on table public.purchase_requests is
  '入荷希望リスト (0140): what we would like to receive, to ask a supplier about. The supplier is optional; nothing is ordered.';

-- ------------------------------------------------------------ candidates
create or replace function public.request_candidates(p_warehouse_id bigint default null, p_supplier_id bigint default null)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.purchase_request_can_view() then
    raise exception 'not permitted: purchase_order.view required';
  end if;
  if p_warehouse_id is not null and not public.can_access_warehouse(p_warehouse_id) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  return coalesce((
    select jsonb_agg(to_jsonb(x) order by x.name, x.jan_code)
      from (
        select p.id as product_id, p.jan_code, p.name, p.name_en, p.maker, p.sku, p.unit, p.lifecycle,
               coalesce((select sum(s.on_hand) from public.stock_levels s
                          where s.jan_code = p.jan_code
                            and (case when p_warehouse_id is null then public.can_access_warehouse(s.warehouse_id)
                                      else s.warehouse_id = p_warehouse_id end)), 0)::int as on_hand,
               wp.min_stock, wp.reorder_point, wp.max_stock,
               n.supplier_code, n.supplier_name as supplier_product_name,
               (n.id is not null) as from_supplier
          from public.products p
          left join public.warehouse_products wp
                 on p_warehouse_id is not null and wp.warehouse_id = p_warehouse_id and wp.product_id = p.id
                and coalesce(wp.is_active, true)
          left join public.supplier_product_names n
                 on p_supplier_id is not null and n.supplier_id = p_supplier_id and n.product_id = p.id
                and coalesce(n.is_active, true)
         where coalesce(p.status, 'active') <> 'inactive'
           and coalesce(p.lifecycle, 'active') <> 'archived'
      ) x), '[]'::jsonb);
end;
$$;
revoke all on function public.request_candidates(bigint, bigint) from public, anon;
grant execute on function public.request_candidates(bigint, bigint) to authenticated, service_role;

-- ------------------------------------------------------------ lists
-- p: {id?, supplier_id?, supplier_name?, warehouse_id?, title?, note?,
--     reply_by?, status?, settings?, lines: [{product_id?, jan_code?, name,
--     name_en?, maker?, sku?, supplier_code?, supplier_product_name?, unit?,
--     quantity, on_hand?, note?}]}
create or replace function public.purchase_request_save(p jsonb)
returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_id bigint := nullif(p->>'id', '')::bigint;
  v_sup bigint := nullif(p->>'supplier_id', '')::bigint;
  v_sup_name text := public.tidy_text(p->>'supplier_name');
  v_wh bigint := nullif(p->>'warehouse_id', '')::bigint;
  e jsonb;
  v_no int := 0;
  v_qty int;
  v_units int := 0;
  v_number text;
  v_rev int := 1;
begin
  if not public.purchase_request_can_edit() then
    raise exception 'not permitted: purchase_order.manage required';
  end if;
  if jsonb_typeof(p->'lines') <> 'array' or jsonb_array_length(p->'lines') = 0 then
    raise exception 'no lines in the request';
  end if;
  if v_wh is not null and not public.can_access_warehouse(v_wh) then
    raise exception 'not permitted: warehouse.scope required';
  end if;
  if v_sup is not null then
    select coalesce(v_sup_name, s.name) into v_sup_name from public.delivery_suppliers s where s.id = v_sup;
  end if;

  if v_id is null then
    insert into public.purchase_requests (company_id, supplier_id, supplier_name, warehouse_id, title, note, reply_by,
                                          status, settings)
    values ((select id from public.companies order by id limit 1), v_sup, v_sup_name, v_wh,
            public.tidy_text(p->>'title'), public.tidy_text(p->>'note'), nullif(p->>'reply_by', '')::date,
            coalesce(nullif(p->>'status', ''), 'draft'),
            case when jsonb_typeof(p->'settings') = 'object' then p->'settings' end)
    returning id into v_id;
    update public.purchase_requests set request_number = 'REQ-' || lpad(v_id::text, 6, '0') where id = v_id;
  else
    update public.purchase_requests set
      supplier_id = v_sup, supplier_name = v_sup_name, warehouse_id = v_wh,
      title = public.tidy_text(p->>'title'), note = public.tidy_text(p->>'note'),
      reply_by = nullif(p->>'reply_by', '')::date,
      status = coalesce(nullif(p->>'status', ''), status),
      settings = case when jsonb_typeof(p->'settings') = 'object' then p->'settings' else settings end,
      revision = revision + 1,
      updated_by = auth.uid(), updated_at = now()
     where id = v_id and status <> 'removed'
     returning revision into v_rev;
    if v_rev is null then
      raise exception 'request % not found', v_id;
    end if;
  end if;

  for e in select * from jsonb_array_elements(p->'lines') loop
    v_qty := coalesce(nullif(btrim(coalesce(e->>'quantity', '')), '')::int, 0);
    continue when v_qty <= 0;
    v_no := v_no + 1;
    insert into public.purchase_request_lines
      (request_id, line_no, product_id, jan_code, name, name_en, maker, sku, supplier_code, supplier_product_name,
       unit, quantity, on_hand, note, revision)
    values (v_id, v_no, nullif(e->>'product_id', '')::bigint, public.tidy_text(e->>'jan_code'),
            coalesce(public.tidy_text(e->>'name'), public.tidy_text(e->>'jan_code'), '（名称なし）'),
            public.tidy_text(e->>'name_en'), public.tidy_text(e->>'maker'), public.tidy_text(e->>'sku'),
            public.tidy_text(e->>'supplier_code'), public.tidy_text(e->>'supplier_product_name'),
            public.tidy_text(e->>'unit'), v_qty, nullif(e->>'on_hand', '')::int, public.tidy_text(e->>'note'), v_rev);
    v_units := v_units + v_qty;
  end loop;
  if v_no = 0 then
    raise exception 'no lines in the request';
  end if;

  select request_number into v_number from public.purchase_requests where id = v_id;
  perform public.log_audit('purchase_request.saved', 'purchase_request', v_id::text, v_wh,
    jsonb_build_object('number', v_number, 'lines', v_no, 'units', v_units, 'supplier', v_sup_name));
  return jsonb_build_object('id', v_id, 'request_number', v_number, 'lines', v_no, 'units', v_units, 'revision', v_rev);
end;
$$;

create or replace function public.purchase_requests_list(p_limit integer default 100)
returns jsonb
language sql stable security definer set search_path = '' as $$
  select case when not public.purchase_request_can_view() then '[]'::jsonb else coalesce((
    select jsonb_agg(to_jsonb(x) order by x.updated_at desc, x.id desc)
      from (select r.id, r.request_number, r.supplier_id, r.supplier_name, r.warehouse_id,
                   (select w.name from public.warehouses w where w.id = r.warehouse_id) as warehouse_name,
                   r.title, r.note, r.reply_by, r.status, r.created_at, r.updated_at,
                   (select coalesce(u.name, u.email) from public.app_users u where u.id = r.created_by) as created_by_name,
                   (select count(*) from public.purchase_request_lines l
                     where l.request_id = r.id and l.revision = r.revision) as line_count,
                   (select coalesce(sum(l.quantity), 0) from public.purchase_request_lines l
                     where l.request_id = r.id and l.revision = r.revision) as units
              from public.purchase_requests r
             where r.status <> 'removed'
             order by r.updated_at desc, r.id desc
             limit greatest(1, least(coalesce(p_limit, 100), 500))) x), '[]'::jsonb) end;
$$;

create or replace function public.purchase_request_get(p_id bigint)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare
  v jsonb;
begin
  if not public.purchase_request_can_view() then
    raise exception 'not permitted: purchase_order.view required';
  end if;
  select to_jsonb(r) - 'company_id' into v from public.purchase_requests r where r.id = p_id and r.status <> 'removed';
  if v is null then
    raise exception 'request % not found', p_id;
  end if;
  return v || jsonb_build_object(
    'warehouse_name', (select w.name from public.warehouses w where w.id = (v->>'warehouse_id')::bigint),
    'lines', coalesce((select jsonb_agg(to_jsonb(l) - 'request_id' order by l.line_no)
                         from public.purchase_request_lines l
                        where l.request_id = p_id and l.revision = (v->>'revision')::int), '[]'::jsonb));
end;
$$;

create or replace function public.purchase_request_remove(p_id bigint)
returns boolean
language plpgsql security definer set search_path = '' as $$
declare
  v_number text;
begin
  if not public.purchase_request_can_edit() then
    raise exception 'not permitted: purchase_order.manage required';
  end if;
  update public.purchase_requests set status = 'removed', updated_by = auth.uid(), updated_at = now()
   where id = p_id and status <> 'removed'
   returning request_number into v_number;
  if v_number is not null then
    perform public.log_audit('purchase_request.removed', 'purchase_request', p_id::text, null,
      jsonb_build_object('number', v_number));
  end if;
  return v_number is not null;
end;
$$;

revoke all on function public.purchase_request_save(jsonb) from public, anon;
revoke all on function public.purchase_requests_list(integer) from public, anon;
revoke all on function public.purchase_request_get(bigint) from public, anon;
revoke all on function public.purchase_request_remove(bigint) from public, anon;
grant execute on function public.purchase_request_save(jsonb) to authenticated, service_role;
grant execute on function public.purchase_requests_list(integer) to authenticated, service_role;
grant execute on function public.purchase_request_get(bigint) to authenticated, service_role;
grant execute on function public.purchase_request_remove(bigint) to authenticated, service_role;
